import { Country, InsurancePlan } from "./types";

export const countries: Country[] = [
  {
    code: "us",
    name: "United States",
    flag: "🇺🇸",
    region: "North America",
    planCount: 8,
    description:
      "The US health insurance market is the largest in the world, with a mix of employer-sponsored, individual, and government programs.",
    healthcareSystem:
      "Private insurance-based system with public programs (Medicare, Medicaid). The ACA marketplace offers subsidized plans.",
  },
  {
    code: "uk",
    name: "United Kingdom",
    flag: "🇬🇧",
    region: "Europe",
    planCount: 6,
    description:
      "While the NHS provides universal coverage, many UK residents opt for private health insurance for faster access and specialist care.",
    healthcareSystem:
      "Universal public healthcare (NHS) with optional private insurance for supplementary coverage.",
  },
  {
    code: "de",
    name: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    planCount: 6,
    description:
      "Germany has one of the oldest universal healthcare systems. Private insurance (PKV) is available for higher earners and self-employed.",
    healthcareSystem:
      "Dual system: Statutory Health Insurance (GKV) for most residents, Private Health Insurance (PKV) for high earners.",
  },
  {
    code: "ae",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    region: "Middle East",
    planCount: 5,
    description:
      "Health insurance is mandatory for all residents in the UAE. Employers must provide coverage for their employees.",
    healthcareSystem:
      "Mandatory private insurance for all residents, with government-funded care for nationals.",
  },
  {
    code: "sg",
    name: "Singapore",
    flag: "🇸🇬",
    region: "Asia Pacific",
    planCount: 5,
    description:
      "Singapore has a highly efficient healthcare system combining government subsidies with mandatory savings and private insurance.",
    healthcareSystem:
      "Multi-tier system: MediShield Life (universal), MediSave (mandatory savings), and optional private Integrated Shield Plans.",
  },
  {
    code: "ca",
    name: "Canada",
    flag: "🇨🇦",
    region: "North America",
    planCount: 5,
    description:
      "Canada provides universal public health coverage, but private insurance supplements areas not covered by provincial plans.",
    healthcareSystem:
      "Universal public healthcare (Medicare) with private insurance for dental, vision, prescription drugs, and other supplementary coverage.",
  },
  {
    code: "au",
    name: "Australia",
    flag: "🇦🇺",
    region: "Asia Pacific",
    planCount: 5,
    description:
      "Australia combines universal public healthcare with a strong private insurance market encouraged by tax incentives.",
    healthcareSystem:
      "Universal public healthcare (Medicare) supplemented by private health insurance with government rebates and tax incentives.",
  },
  {
    code: "fr",
    name: "France",
    flag: "🇫🇷",
    region: "Europe",
    planCount: 5,
    description:
      "France's healthcare system is often ranked among the best in the world. Complementary private insurance (mutuelle) covers co-pays.",
    healthcareSystem:
      "Universal public healthcare with mandatory complementary private insurance (mutuelle) covering co-payments.",
  },
  {
    code: "jp",
    name: "Japan",
    flag: "🇯🇵",
    region: "Asia Pacific",
    planCount: 4,
    description:
      "Japan provides universal coverage through employment-based or national health insurance, with optional private supplements.",
    healthcareSystem:
      "Universal public health insurance (NHI or employer-based) with optional private insurance for additional coverage.",
  },
  {
    code: "br",
    name: "Brazil",
    flag: "🇧🇷",
    region: "Latin America",
    planCount: 4,
    description:
      "Brazil has a universal public system (SUS) alongside a large private insurance market serving about 25% of the population.",
    healthcareSystem:
      "Universal public healthcare (SUS) with private insurance plans (planos de saude) for faster access and wider networks.",
  },
  {
    code: "za",
    name: "South Africa",
    flag: "🇿🇦",
    region: "Africa",
    planCount: 4,
    description:
      "South Africa has a two-tier system with public healthcare and private medical schemes covering about 16% of the population.",
    healthcareSystem:
      "Two-tier system: public healthcare for all, private medical schemes for those who can afford it.",
  },
  {
    code: "in",
    name: "India",
    flag: "🇮🇳",
    region: "Asia Pacific",
    planCount: 5,
    description:
      "India's health insurance market is rapidly growing, with both government schemes and private insurers serving a large population.",
    healthcareSystem:
      "Mix of public programs (Ayushman Bharat) and private insurance, with growing digital health platforms.",
  },
];

export const insurancePlans: InsurancePlan[] = [
  // United States
  {
    id: "us-blue-cross",
    name: "Blue Cross Blue Shield PPO",
    provider: "Blue Cross Blue Shield",
    country: "United States",
    countryCode: "us",
    logo: "/logos/bcbs.svg",
    rating: 4.5,
    reviewCount: 12453,
    monthlyPremium: "$450 - $850",
    deductible: "$1,500 - $6,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular", "Best Network"],
    highlights: [
      "Largest provider network in the US",
      "Available in all 50 states",
      "Strong preventive care coverage",
    ],
    pros: [
      "Extensive nationwide network",
      "Wide range of plan options",
      "Strong customer service ratings",
      "Comprehensive preventive care",
    ],
    cons: [
      "Higher premiums than some competitors",
      "Complex plan structures",
      "Out-of-network costs can be high",
    ],
    affiliateUrl: "#",
    description:
      "Blue Cross Blue Shield is the largest health insurance provider in the US, offering a wide range of plans through 36 independent companies nationwide.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Consistently ranked as a top choice for comprehensive coverage with the broadest provider networks available.",
    editorialSource: "US News Health Insurance Rankings 2025",
  },
  {
    id: "us-kaiser",
    name: "Kaiser Permanente HMO",
    provider: "Kaiser Permanente",
    country: "United States",
    countryCode: "us",
    logo: "/logos/kaiser.svg",
    rating: 4.6,
    reviewCount: 9821,
    monthlyPremium: "$350 - $750",
    deductible: "$0 - $3,000",
    coverageType: "comprehensive",
    badges: ["Best Value", "Top Rated", "Best Preventive Care"],
    highlights: [
      "Integrated care model",
      "Low out-of-pocket costs",
      "Excellent preventive care programs",
    ],
    pros: [
      "Lower premiums and deductibles",
      "Integrated healthcare system",
      "Top-rated preventive programs",
      "Award-winning digital tools",
    ],
    cons: [
      "Limited to specific regions",
      "Must use Kaiser facilities",
      "Less flexibility in provider choice",
    ],
    affiliateUrl: "#",
    description:
      "Kaiser Permanente is known for its integrated care model where insurance and care delivery are combined, leading to better coordinated care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Kaiser Permanente leads in patient satisfaction and preventive care quality, consistently earning top marks from NCQA.",
    editorialSource: "NCQA Health Plan Ratings 2025",
  },
  {
    id: "us-unitedhealthcare",
    name: "UnitedHealthcare Choice Plus",
    provider: "UnitedHealthcare",
    country: "United States",
    countryCode: "us",
    logo: "/logos/uhc.svg",
    rating: 4.2,
    reviewCount: 11234,
    monthlyPremium: "$400 - $900",
    deductible: "$2,000 - $7,000",
    coverageType: "comprehensive",
    badges: ["Largest Insurer", "Best Digital Tools"],
    highlights: [
      "Largest single health insurer in the US",
      "Extensive digital health platform",
      "Flexible plan designs",
    ],
    pros: [
      "Very large provider network",
      "Innovative digital health tools",
      "Many plan options",
      "Strong employer plan offerings",
    ],
    cons: [
      "Customer service complaints",
      "Prior authorization frustrations",
      "Complex claims process",
    ],
    affiliateUrl: "#",
    description:
      "UnitedHealthcare is the largest single health insurance company in the US, serving over 50 million members with diverse plan options.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "UnitedHealthcare offers the widest reach and most diverse plan portfolio, though customer satisfaction varies by region.",
    editorialSource: "Forbes Health Insurance Guide 2025",
  },
  {
    id: "us-aetna",
    name: "Aetna CVS Health",
    provider: "Aetna",
    country: "United States",
    countryCode: "us",
    logo: "/logos/aetna.svg",
    rating: 4.1,
    reviewCount: 7654,
    monthlyPremium: "$380 - $820",
    deductible: "$1,500 - $5,500",
    coverageType: "premium",
    badges: ["Best Pharmacy Integration", "Innovation Award"],
    highlights: [
      "CVS pharmacy integration",
      "MinuteClinic access included",
      "Strong mental health coverage",
    ],
    pros: [
      "Seamless CVS/pharmacy integration",
      "Good mental health coverage",
      "MinuteClinic walk-in access",
      "Competitive pricing",
    ],
    cons: [
      "Network can be limited in rural areas",
      "Plan complexity varies",
      "Some specialist referral requirements",
    ],
    affiliateUrl: "#",
    description:
      "Aetna, now part of CVS Health, combines traditional health insurance with pharmacy benefits and retail clinic access.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "The CVS-Aetna merger creates unique advantages in pharmacy integration and accessible care through MinuteClinics.",
    editorialSource: "Healthline Best Insurance 2025",
  },
  {
    id: "us-cigna",
    name: "Cigna Healthcare",
    provider: "Cigna",
    country: "United States",
    countryCode: "us",
    logo: "/logos/cigna.svg",
    rating: 4.3,
    reviewCount: 6789,
    monthlyPremium: "$420 - $880",
    deductible: "$1,500 - $6,500",
    coverageType: "comprehensive",
    badges: ["Best International", "Best Employer Plans"],
    highlights: [
      "Strong international coverage options",
      "Excellent employer group plans",
      "Comprehensive wellness programs",
    ],
    pros: [
      "Top-tier international coverage",
      "Strong wellness incentive programs",
      "Good behavioral health services",
      "Global network of providers",
    ],
    cons: [
      "Premium pricing",
      "Limited individual plan availability",
      "Complex prior authorization",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Healthcare excels in employer-sponsored and international coverage, with a strong focus on whole-person health.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna stands out for international coverage and its commitment to behavioral health and wellness programs.",
    editorialSource: "NerdWallet Health Insurance Ratings 2025",
  },
  {
    id: "us-humana",
    name: "Humana Gold Plus",
    provider: "Humana",
    country: "United States",
    countryCode: "us",
    logo: "/logos/humana.svg",
    rating: 4.0,
    reviewCount: 5432,
    monthlyPremium: "$320 - $720",
    deductible: "$1,000 - $5,000",
    coverageType: "standard",
    badges: ["Best Medicare Plans", "Best for Seniors"],
    highlights: [
      "Top-rated Medicare Advantage plans",
      "Strong chronic care management",
      "Affordable premium options",
    ],
    pros: [
      "Excellent Medicare Advantage offerings",
      "Good value for money",
      "Strong chronic disease programs",
      "Growing telehealth options",
    ],
    cons: [
      "Limited in some markets",
      "Fewer individual plan options",
      "Network restrictions in rural areas",
    ],
    affiliateUrl: "#",
    description:
      "Humana is best known for its Medicare Advantage plans and focus on senior healthcare, with growing individual and group offerings.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Humana's Medicare Advantage plans consistently rank among the highest rated, with exceptional chronic care management.",
    editorialSource: "Medicare.gov Plan Ratings 2025",
  },
  {
    id: "us-anthem",
    name: "Anthem Blue Cross",
    provider: "Anthem",
    country: "United States",
    countryCode: "us",
    logo: "/logos/anthem.svg",
    rating: 4.1,
    reviewCount: 8765,
    monthlyPremium: "$400 - $850",
    deductible: "$1,500 - $6,500",
    coverageType: "comprehensive",
    badges: ["Best Regional Coverage"],
    highlights: [
      "Strong regional networks",
      "LiveHealth Online telehealth",
      "Comprehensive family plans",
    ],
    pros: [
      "Strong in 14 states",
      "Good telehealth platform",
      "Competitive family plan pricing",
      "Blue Cross Blue Shield network access",
    ],
    cons: [
      "Not available nationwide",
      "Customer service variability",
      "Claims processing delays reported",
    ],
    affiliateUrl: "#",
    description:
      "Anthem is one of the largest Blue Cross Blue Shield affiliates, serving 14 states with comprehensive health insurance options.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Anthem provides solid regional coverage with the added benefit of Blue Cross Blue Shield network interoperability.",
    editorialSource: "Consumer Reports Health Insurance 2025",
  },
  {
    id: "us-oscar",
    name: "Oscar Health",
    provider: "Oscar",
    country: "United States",
    countryCode: "us",
    logo: "/logos/oscar.svg",
    rating: 4.4,
    reviewCount: 3456,
    monthlyPremium: "$350 - $750",
    deductible: "$2,000 - $7,500",
    coverageType: "standard",
    badges: ["Best Tech", "Best User Experience", "Rising Star"],
    highlights: [
      "Tech-first health insurance",
      "Free virtual primary care",
      "Intuitive mobile app",
    ],
    pros: [
      "Industry-leading mobile app",
      "Free 24/7 virtual care",
      "Transparent pricing",
      "Simple plan structures",
    ],
    cons: [
      "Limited availability (18 states)",
      "Smaller provider network",
      "Higher deductibles on some plans",
    ],
    affiliateUrl: "#",
    description:
      "Oscar Health is a technology-focused health insurer that aims to make health insurance simple and accessible through innovative digital tools.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Oscar's technology-first approach and transparent pricing model make it a standout choice for digitally-savvy consumers.",
    editorialSource: "TechCrunch Health Insurance Review 2025",
  },

  // United Kingdom
  {
    id: "uk-bupa",
    name: "Bupa Health Insurance",
    provider: "Bupa",
    country: "United Kingdom",
    countryCode: "uk",
    logo: "/logos/bupa.svg",
    rating: 4.5,
    reviewCount: 8234,
    monthlyPremium: "£80 - £250",
    deductible: "£0 - £500",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Best Overall UK", "Most Trusted"],
    highlights: [
      "Largest private healthcare provider in UK",
      "Direct access to specialists",
      "24/7 GP helpline",
    ],
    pros: [
      "Widest hospital network in UK",
      "No GP referral needed for specialists",
      "Excellent cancer care coverage",
      "Digital GP services",
    ],
    cons: [
      "Premium pricing",
      "Pre-existing conditions excluded initially",
      "Some treatments require pre-approval",
    ],
    affiliateUrl: "#",
    description:
      "Bupa is the UK's largest private health insurer, offering comprehensive plans with direct access to specialists and a vast network of hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa remains the gold standard in UK private health insurance, with the broadest network and most comprehensive coverage options.",
    editorialSource: "Which? Health Insurance Guide 2025",
  },
  {
    id: "uk-axa",
    name: "AXA Health",
    provider: "AXA PPP Healthcare",
    country: "United Kingdom",
    countryCode: "uk",
    logo: "/logos/axa.svg",
    rating: 4.3,
    reviewCount: 5678,
    monthlyPremium: "£60 - £200",
    deductible: "£0 - £250",
    coverageType: "premium",
    badges: ["Best Value UK", "Best Mental Health"],
    highlights: [
      "Competitive pricing",
      "Strong mental health support",
      "Fast claims processing",
    ],
    pros: [
      "More affordable than Bupa",
      "Excellent mental health coverage",
      "Quick claims processing",
      "Good digital tools",
    ],
    cons: [
      "Smaller hospital network than Bupa",
      "Some exclusions on basic plans",
      "Waiting periods for some conditions",
    ],
    affiliateUrl: "#",
    description:
      "AXA Health offers competitive private health insurance in the UK with strong mental health support and fast claims processing.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Health offers some of the best value in UK private health insurance, especially for mental health coverage.",
    editorialSource: "MoneySuperMarket Insurance Awards 2025",
  },
  {
    id: "uk-vitality",
    name: "Vitality Health",
    provider: "Vitality",
    country: "United Kingdom",
    countryCode: "uk",
    logo: "/logos/vitality.svg",
    rating: 4.4,
    reviewCount: 6543,
    monthlyPremium: "£70 - £220",
    deductible: "£0 - £500",
    coverageType: "premium",
    badges: ["Most Innovative", "Best Wellness Rewards"],
    highlights: [
      "Wellness rewards program",
      "Discounts for healthy living",
      "Partner rewards (Apple Watch, gym)",
    ],
    pros: [
      "Unique wellness incentive program",
      "Discounts for active lifestyle",
      "Apple Watch and gym rewards",
      "Good online tools",
    ],
    cons: [
      "Can be complex to understand",
      "Rewards require active participation",
      "Some exclusions apply",
    ],
    affiliateUrl: "#",
    description:
      "Vitality Health combines health insurance with a wellness rewards program that incentivizes healthy living with discounts and partner benefits.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Vitality's innovative rewards program makes it unique in the UK market, genuinely incentivizing healthier lifestyles.",
    editorialSource: "The Telegraph Best Health Insurance 2025",
  },
  {
    id: "uk-aviva",
    name: "Aviva Health Insurance",
    provider: "Aviva",
    country: "United Kingdom",
    countryCode: "uk",
    logo: "/logos/aviva.svg",
    rating: 4.2,
    reviewCount: 4567,
    monthlyPremium: "£55 - £180",
    deductible: "£0 - £500",
    coverageType: "standard",
    badges: ["Most Affordable UK", "Best Family Plans"],
    highlights: [
      "Most affordable major insurer",
      "Family-friendly plans",
      "Good GP access",
    ],
    pros: [
      "Competitive pricing",
      "Good family plan discounts",
      "Straightforward plans",
      "No referral needed",
    ],
    cons: [
      "Fewer specialist hospitals",
      "Basic mental health on cheaper plans",
      "Limited international coverage",
    ],
    affiliateUrl: "#",
    description:
      "Aviva offers affordable private health insurance with straightforward plans that are particularly good value for families.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Aviva strikes the best balance between affordability and coverage in the UK market, especially for families.",
    editorialSource: "Compare the Market Awards 2025",
  },
  {
    id: "uk-wpa",
    name: "WPA Health Insurance",
    provider: "WPA",
    country: "United Kingdom",
    countryCode: "uk",
    logo: "/logos/wpa.svg",
    rating: 4.6,
    reviewCount: 2345,
    monthlyPremium: "£90 - £300",
    deductible: "£0 - £250",
    coverageType: "comprehensive",
    badges: ["Best Customer Service UK", "Premium Choice"],
    highlights: [
      "Highest customer satisfaction",
      "Not-for-profit insurer",
      "Personal service approach",
    ],
    pros: [
      "Exceptional customer service",
      "Not-for-profit (profits reinvested)",
      "Personal claims handlers",
      "Comprehensive coverage",
    ],
    cons: [
      "Higher premiums",
      "Smaller brand recognition",
      "Limited digital tools compared to larger insurers",
    ],
    affiliateUrl: "#",
    description:
      "WPA is a not-for-profit health insurer known for exceptional customer service and comprehensive coverage with a personal touch.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "WPA's not-for-profit model delivers consistently superior customer service and claims handling experience.",
    editorialSource: "Defaqto Expert Ratings 2025",
  },
  {
    id: "uk-freedom",
    name: "Freedom Health Insurance",
    provider: "Freedom",
    country: "United Kingdom",
    countryCode: "uk",
    logo: "/logos/freedom.svg",
    rating: 4.0,
    reviewCount: 1234,
    monthlyPremium: "£45 - £150",
    deductible: "£100 - £500",
    coverageType: "basic",
    badges: ["Budget Pick"],
    highlights: [
      "Budget-friendly option",
      "Flexible excess options",
      "Good basic coverage",
    ],
    pros: [
      "Very affordable premiums",
      "Flexible plan customization",
      "Good value for basic needs",
      "Quick online quotes",
    ],
    cons: [
      "Limited hospital network",
      "Basic customer support",
      "Fewer extra benefits",
    ],
    affiliateUrl: "#",
    description:
      "Freedom Health Insurance offers budget-friendly private health cover with flexible options for those who want basic coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Freedom provides a solid entry point into private health insurance for budget-conscious consumers.",
    editorialSource: "Money.co.uk Insurance Comparison 2025",
  },

  // Germany
  {
    id: "de-tk",
    name: "Techniker Krankenkasse (TK)",
    provider: "TK",
    country: "Germany",
    countryCode: "de",
    logo: "/logos/tk.svg",
    rating: 4.7,
    reviewCount: 15678,
    monthlyPremium: "€180 - €450",
    deductible: "€0",
    coverageType: "comprehensive",
    badges: ["#1 in Germany", "Editor's Choice", "Best Digital"],
    highlights: [
      "Largest public health insurer in Germany",
      "Lowest additional contribution rate",
      "Award-winning TK-App",
    ],
    pros: [
      "Excellent digital services (TK-App)",
      "Low additional contribution rate",
      "Wide range of bonus programs",
      "Top-rated customer service",
    ],
    cons: [
      "Statutory insurance limitations apply",
      "Some specialist wait times",
      "Limited private room options",
    ],
    affiliateUrl: "#",
    description:
      "Techniker Krankenkasse is Germany's largest and highest-rated statutory health insurance fund, known for innovation and digital services.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "TK has been voted Germany's best health insurance fund for 15 consecutive years, setting the standard for digital healthcare.",
    editorialSource: "Focus Money Krankenkassen-Test 2025",
  },
  {
    id: "de-aok",
    name: "AOK Plus",
    provider: "AOK",
    country: "Germany",
    countryCode: "de",
    logo: "/logos/aok.svg",
    rating: 4.3,
    reviewCount: 9876,
    monthlyPremium: "€190 - €460",
    deductible: "€0",
    coverageType: "comprehensive",
    badges: ["Best Regional Coverage", "Family Friendly"],
    highlights: [
      "Strong regional presence",
      "Excellent family programs",
      "Good preventive care coverage",
    ],
    pros: [
      "Strong local presence",
      "Good family health programs",
      "Comprehensive preventive care",
      "Personal advisor service",
    ],
    cons: [
      "Higher additional contribution than TK",
      "Varying quality by region",
      "Less innovative digital tools",
    ],
    affiliateUrl: "#",
    description:
      "AOK is a group of regional statutory health insurers in Germany, known for strong local presence and family-oriented health programs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AOK's regional expertise and family programs make it a strong choice for families seeking personalized healthcare support.",
    editorialSource: "Stiftung Warentest Krankenkassen 2025",
  },
  {
    id: "de-debeka",
    name: "Debeka PKV Premium",
    provider: "Debeka",
    country: "Germany",
    countryCode: "de",
    logo: "/logos/debeka.svg",
    rating: 4.5,
    reviewCount: 7654,
    monthlyPremium: "€350 - €800",
    deductible: "€0 - €1,200",
    coverageType: "comprehensive",
    badges: ["Best Private Insurance DE", "Top Rated PKV"],
    highlights: [
      "Top-rated private health insurer",
      "Chief physician treatment",
      "Private hospital rooms",
    ],
    pros: [
      "Excellent private coverage",
      "Chief physician treatment standard",
      "Private room guarantee",
      "Stable premium development",
    ],
    cons: [
      "Only available for eligible individuals",
      "Higher cost than statutory",
      "Premium increases with age",
    ],
    affiliateUrl: "#",
    description:
      "Debeka is Germany's largest private health insurer, offering premium coverage with chief physician treatment and private room guarantees.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Debeka consistently achieves top ratings for private health insurance in Germany, with particularly stable premiums over time.",
    editorialSource: "Franke und Bornberg PKV-Rating 2025",
  },
  {
    id: "de-allianz",
    name: "Allianz Private Health",
    provider: "Allianz",
    country: "Germany",
    countryCode: "de",
    logo: "/logos/allianz.svg",
    rating: 4.4,
    reviewCount: 6543,
    monthlyPremium: "€380 - €850",
    deductible: "€0 - €1,500",
    coverageType: "premium",
    badges: ["Global Brand", "Best International DE"],
    highlights: [
      "Global insurance brand",
      "Worldwide coverage included",
      "Flexible tariff options",
    ],
    pros: [
      "Strong international coverage",
      "Flexible deductible options",
      "Worldwide network",
      "Strong financial stability",
    ],
    cons: [
      "Higher premiums than some PKV",
      "Complex tariff structures",
      "Long-term premium increases",
    ],
    affiliateUrl: "#",
    description:
      "Allianz Private Health Insurance offers flexible private coverage with global reach, backed by one of the world's largest insurers.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Allianz leverages its global network to offer private health insurance with unmatched international coverage options.",
    editorialSource: "Handelsblatt Versicherungstest 2025",
  },
  {
    id: "de-barmer",
    name: "BARMER",
    provider: "BARMER",
    country: "Germany",
    countryCode: "de",
    logo: "/logos/barmer.svg",
    rating: 4.2,
    reviewCount: 8765,
    monthlyPremium: "€185 - €455",
    deductible: "€0",
    coverageType: "comprehensive",
    badges: ["Best Preventive Programs", "Innovation Leader"],
    highlights: [
      "Strong preventive health programs",
      "Digital health innovations",
      "Good telemedicine services",
    ],
    pros: [
      "Innovative preventive programs",
      "Good digital health offerings",
      "Comprehensive basic coverage",
      "Active health bonuses",
    ],
    cons: [
      "Higher additional contribution",
      "Some bonus programs complex",
      "Limited extras vs. TK",
    ],
    affiliateUrl: "#",
    description:
      "BARMER is one of Germany's largest statutory health insurers, known for innovative preventive health programs and digital services.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "BARMER leads in preventive health innovation and has been recognized for its commitment to digital health transformation.",
    editorialSource: "DFSI Krankenkassen-Rating 2025",
  },
  {
    id: "de-dak",
    name: "DAK-Gesundheit",
    provider: "DAK",
    country: "Germany",
    countryCode: "de",
    logo: "/logos/dak.svg",
    rating: 4.1,
    reviewCount: 5432,
    monthlyPremium: "€195 - €470",
    deductible: "€0",
    coverageType: "standard",
    badges: ["Best for Young Professionals"],
    highlights: [
      "Good for young professionals",
      "Online coaching programs",
      "Flexible bonus model",
    ],
    pros: [
      "Strong online health programs",
      "Good for career starters",
      "Flexible activity bonuses",
      "Good nationwide service",
    ],
    cons: [
      "Higher additional contribution rate",
      "Service quality varies",
      "Digital tools lag behind TK",
    ],
    affiliateUrl: "#",
    description:
      "DAK-Gesundheit offers solid statutory health insurance with programs tailored to young professionals and active individuals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "DAK's focus on young professionals and digital health programs makes it a solid choice for career-oriented individuals.",
    editorialSource: "Euro am Sonntag Krankenkassen 2025",
  },

  // UAE
  {
    id: "ae-daman",
    name: "Daman Enhanced",
    provider: "National Health Insurance (Daman)",
    country: "United Arab Emirates",
    countryCode: "ae",
    logo: "/logos/daman.svg",
    rating: 4.4,
    reviewCount: 4567,
    monthlyPremium: "AED 500 - AED 2,000",
    deductible: "AED 0 - AED 500",
    coverageType: "comprehensive",
    badges: ["#1 in UAE", "Government Backed"],
    highlights: [
      "Largest health insurer in UAE",
      "Government-backed",
      "Comprehensive network in Abu Dhabi",
    ],
    pros: [
      "Backed by Abu Dhabi government",
      "Extensive network",
      "Comprehensive coverage options",
      "Fast claims processing",
    ],
    cons: [
      "Primarily Abu Dhabi focused",
      "Limited plan customization",
      "Basic plans have restrictions",
    ],
    affiliateUrl: "#",
    description:
      "Daman is the national health insurer of Abu Dhabi, providing mandatory and enhanced health coverage for UAE residents.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "As the government-backed national insurer, Daman provides the most reliable and comprehensive coverage in Abu Dhabi.",
    editorialSource: "Gulf News Health Insurance Guide 2025",
  },
  {
    id: "ae-cigna-global",
    name: "Cigna Global Health",
    provider: "Cigna",
    country: "United Arab Emirates",
    countryCode: "ae",
    logo: "/logos/cigna.svg",
    rating: 4.5,
    reviewCount: 3456,
    monthlyPremium: "AED 800 - AED 3,500",
    deductible: "AED 0 - AED 2,000",
    coverageType: "comprehensive",
    badges: ["Best Expat Coverage", "Best International"],
    highlights: [
      "Global coverage for expats",
      "Direct billing worldwide",
      "Comprehensive maternity",
    ],
    pros: [
      "Worldwide coverage",
      "Direct billing in 200+ countries",
      "Excellent expat support",
      "Flexible plan design",
    ],
    cons: [
      "Premium pricing",
      "Complex plan tiers",
      "Some exclusions on basic plans",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Global Health offers comprehensive international health insurance for expats in the UAE with worldwide coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna Global remains the top choice for UAE expats seeking comprehensive worldwide coverage with direct billing.",
    editorialSource: "ExpatFocus Insurance Rankings 2025",
  },
  {
    id: "ae-oman-insurance",
    name: "Oman Insurance Premium",
    provider: "Oman Insurance Company",
    country: "United Arab Emirates",
    countryCode: "ae",
    logo: "/logos/oman-ins.svg",
    rating: 4.2,
    reviewCount: 2345,
    monthlyPremium: "AED 400 - AED 1,800",
    deductible: "AED 0 - AED 500",
    coverageType: "premium",
    badges: ["Best Local Network"],
    highlights: [
      "Strong local network",
      "Good value plans",
      "Fast local claims",
    ],
    pros: [
      "Excellent UAE network",
      "Competitive pricing",
      "Fast claims settlement",
      "Good customer service",
    ],
    cons: [
      "Limited international coverage",
      "Less known outside UAE",
      "Fewer plan tiers",
    ],
    affiliateUrl: "#",
    description:
      "Oman Insurance Company offers strong local health coverage in the UAE with competitive pricing and a well-established provider network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Oman Insurance offers excellent value within the UAE, particularly strong for those who don't need international coverage.",
    editorialSource: "Insurance Business Middle East 2025",
  },
  {
    id: "ae-axa-gulf",
    name: "AXA Gulf Health",
    provider: "AXA",
    country: "United Arab Emirates",
    countryCode: "ae",
    logo: "/logos/axa.svg",
    rating: 4.3,
    reviewCount: 2890,
    monthlyPremium: "AED 600 - AED 2,500",
    deductible: "AED 0 - AED 1,000",
    coverageType: "premium",
    badges: ["Best Claims Process"],
    highlights: [
      "Efficient claims processing",
      "Global brand backing",
      "Good specialist access",
    ],
    pros: [
      "Fast claims processing",
      "Strong global brand",
      "Good specialist network",
      "Comprehensive plans available",
    ],
    cons: [
      "Premium pricing tier",
      "Some plans have co-payments",
      "Limited dental on basic plans",
    ],
    affiliateUrl: "#",
    description:
      "AXA Gulf provides health insurance backed by one of the world's largest insurance groups, with efficient claims processing in the UAE.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Gulf combines global insurance expertise with strong local service, particularly excelling in claims efficiency.",
    editorialSource: "Arabian Business Insurance Awards 2025",
  },
  {
    id: "ae-metlife",
    name: "MetLife UAE Health",
    provider: "MetLife",
    country: "United Arab Emirates",
    countryCode: "ae",
    logo: "/logos/metlife.svg",
    rating: 4.1,
    reviewCount: 1987,
    monthlyPremium: "AED 500 - AED 2,200",
    deductible: "AED 0 - AED 750",
    coverageType: "standard",
    badges: ["Best Group Plans UAE"],
    highlights: [
      "Strong group/employer plans",
      "Good wellness programs",
      "Competitive pricing",
    ],
    pros: [
      "Excellent employer plans",
      "Good wellness incentives",
      "Competitive pricing",
      "Strong brand reputation",
    ],
    cons: [
      "Individual plans limited",
      "Network smaller than Daman",
      "Basic plans restrictive",
    ],
    affiliateUrl: "#",
    description:
      "MetLife provides health insurance in the UAE with particular strength in employer/group plans and wellness programs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "MetLife excels in group health insurance for UAE employers, offering competitive plans with strong wellness components.",
    editorialSource: "MENA Insurance Review 2025",
  },

  // Singapore
  {
    id: "sg-aia",
    name: "AIA HealthShield Gold Max",
    provider: "AIA",
    country: "Singapore",
    countryCode: "sg",
    logo: "/logos/aia.svg",
    rating: 4.5,
    reviewCount: 6789,
    monthlyPremium: "SGD 200 - SGD 600",
    deductible: "SGD 0 - SGD 3,500",
    coverageType: "comprehensive",
    badges: ["Best Shield Plan", "Top Rated SG"],
    highlights: [
      "Top-rated Integrated Shield Plan",
      "Private hospital coverage",
      "MediSave payable",
    ],
    pros: [
      "Comprehensive private coverage",
      "MediSave compatible",
      "Wide hospital network",
      "Good rider options",
    ],
    cons: [
      "Premiums increase with age",
      "Co-payment requirements",
      "Rider costs add up",
    ],
    affiliateUrl: "#",
    description:
      "AIA HealthShield Gold Max is one of Singapore's top Integrated Shield Plans, offering comprehensive private hospital coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AIA's HealthShield Gold Max consistently ranks as one of the best Integrated Shield Plans in Singapore.",
    editorialSource: "MoneySmart Singapore Insurance Guide 2025",
  },
  {
    id: "sg-prudential",
    name: "PRUShield Premier",
    provider: "Prudential",
    country: "Singapore",
    countryCode: "sg",
    logo: "/logos/prudential.svg",
    rating: 4.4,
    reviewCount: 5432,
    monthlyPremium: "SGD 180 - SGD 550",
    deductible: "SGD 0 - SGD 3,500",
    coverageType: "comprehensive",
    badges: ["Best Coverage Limits", "Editor's Pick SG"],
    highlights: [
      "Highest coverage limits",
      "No lifetime cap",
      "Strong critical illness add-ons",
    ],
    pros: [
      "Generous coverage limits",
      "No lifetime claim cap",
      "Good critical illness coverage",
      "MediSave compatible",
    ],
    cons: [
      "Premium pricing",
      "Age-based premium increases",
      "Some riders expensive",
    ],
    affiliateUrl: "#",
    description:
      "PRUShield Premier offers some of the highest coverage limits among Singapore's Integrated Shield Plans with no lifetime cap.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "PRUShield Premier stands out for its industry-leading coverage limits and no lifetime cap on claims.",
    editorialSource: "SingSaver Insurance Comparison 2025",
  },
  {
    id: "sg-great-eastern",
    name: "Great Eastern Supreme Health",
    provider: "Great Eastern",
    country: "Singapore",
    countryCode: "sg",
    logo: "/logos/great-eastern.svg",
    rating: 4.3,
    reviewCount: 4321,
    monthlyPremium: "SGD 170 - SGD 520",
    deductible: "SGD 0 - SGD 3,500",
    coverageType: "premium",
    badges: ["Most Trusted SG", "Heritage Brand"],
    highlights: [
      "Singapore's oldest insurer",
      "Strong brand trust",
      "Competitive premiums",
    ],
    pros: [
      "Long-standing reputation",
      "Competitive pricing",
      "Good claims experience",
      "MediSave compatible",
    ],
    cons: [
      "Less innovative than competitors",
      "Digital tools improving but behind",
      "Standard rider options",
    ],
    affiliateUrl: "#",
    description:
      "Great Eastern is Singapore's oldest and most trusted insurer, offering reliable Integrated Shield Plans with competitive premiums.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Great Eastern's heritage and reliability make it a trusted choice for Singaporeans seeking dependable health coverage.",
    editorialSource: "The Straits Times Insurance Awards 2025",
  },
  {
    id: "sg-ntuc",
    name: "NTUC Income Enhanced IncomeShield",
    provider: "NTUC Income",
    country: "Singapore",
    countryCode: "sg",
    logo: "/logos/ntuc.svg",
    rating: 4.2,
    reviewCount: 5678,
    monthlyPremium: "SGD 150 - SGD 480",
    deductible: "SGD 0 - SGD 3,500",
    coverageType: "standard",
    badges: ["Best Value SG", "Most Affordable"],
    highlights: [
      "Most affordable Shield Plan",
      "Social enterprise insurer",
      "Good basic coverage",
    ],
    pros: [
      "Most affordable premiums",
      "Social enterprise values",
      "Good basic coverage",
      "MediSave compatible",
    ],
    cons: [
      "Lower coverage limits",
      "Fewer rider options",
      "Basic digital tools",
    ],
    affiliateUrl: "#",
    description:
      "NTUC Income offers the most affordable Integrated Shield Plans in Singapore as a social enterprise insurer.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "NTUC Income provides the best value Integrated Shield Plan for budget-conscious Singaporeans.",
    editorialSource: "Seedly Insurance Comparison 2025",
  },
  {
    id: "sg-raffles",
    name: "Raffles Shield",
    provider: "Raffles Health Insurance",
    country: "Singapore",
    countryCode: "sg",
    logo: "/logos/raffles.svg",
    rating: 4.1,
    reviewCount: 2345,
    monthlyPremium: "SGD 190 - SGD 570",
    deductible: "SGD 0 - SGD 3,500",
    coverageType: "premium",
    badges: ["Best Hospital Network SG"],
    highlights: [
      "Raffles Hospital network",
      "Integrated care experience",
      "Good specialist access",
    ],
    pros: [
      "Raffles Hospital access",
      "Integrated healthcare",
      "Good specialist referrals",
      "MediSave compatible",
    ],
    cons: [
      "Smaller insurer",
      "Limited to Raffles network benefits",
      "Fewer plan options",
    ],
    affiliateUrl: "#",
    description:
      "Raffles Shield offers health insurance integrated with the renowned Raffles Hospital network in Singapore.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Raffles Shield uniquely integrates insurance with one of Southeast Asia's premier hospital networks.",
    editorialSource: "Asia Insurance Review 2025",
  },

  // Canada
  {
    id: "ca-sunlife",
    name: "Sun Life Assurance",
    provider: "Sun Life",
    country: "Canada",
    countryCode: "ca",
    logo: "/logos/sunlife.svg",
    rating: 4.4,
    reviewCount: 7654,
    monthlyPremium: "CAD 80 - CAD 350",
    deductible: "CAD 0 - CAD 500",
    coverageType: "comprehensive",
    badges: ["#1 in Canada", "Best Overall CA", "Most Trusted"],
    highlights: [
      "Canada's largest health insurer",
      "Comprehensive supplementary coverage",
      "Lumino Health platform",
    ],
    pros: [
      "Most comprehensive benefits",
      "Lumino Health digital platform",
      "Wide provider network",
      "Excellent group plans",
    ],
    cons: [
      "Individual plans can be pricey",
      "Wait periods for some benefits",
      "Complex plan structures",
    ],
    affiliateUrl: "#",
    description:
      "Sun Life is Canada's largest health benefits provider, offering comprehensive supplementary coverage for dental, vision, and prescription drugs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Sun Life continues to dominate Canadian health benefits with its comprehensive coverage and innovative Lumino Health platform.",
    editorialSource: "Benefits Canada Awards 2025",
  },
  {
    id: "ca-manulife",
    name: "Manulife Flexcare",
    provider: "Manulife",
    country: "Canada",
    countryCode: "ca",
    logo: "/logos/manulife.svg",
    rating: 4.3,
    reviewCount: 6543,
    monthlyPremium: "CAD 70 - CAD 300",
    deductible: "CAD 0 - CAD 250",
    coverageType: "premium",
    badges: ["Best Flexibility CA", "Innovation Award"],
    highlights: [
      "Highly flexible plan design",
      "Vitality wellness program",
      "Good individual plans",
    ],
    pros: [
      "Very flexible plan customization",
      "Vitality wellness rewards",
      "Good individual coverage",
      "Competitive pricing",
    ],
    cons: [
      "Some benefits need waiting periods",
      "Wellness program requires effort",
      "Network varies by province",
    ],
    affiliateUrl: "#",
    description:
      "Manulife Flexcare offers highly customizable health benefit plans with an integrated wellness rewards program.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Manulife's Flexcare stands out for its customization options, allowing Canadians to build coverage that fits their specific needs.",
    editorialSource: "Canadian Underwriter Insurance Awards 2025",
  },
  {
    id: "ca-greenshield",
    name: "Green Shield Canada",
    provider: "Green Shield",
    country: "Canada",
    countryCode: "ca",
    logo: "/logos/greenshield.svg",
    rating: 4.2,
    reviewCount: 4321,
    monthlyPremium: "CAD 65 - CAD 250",
    deductible: "CAD 0 - CAD 200",
    coverageType: "standard",
    badges: ["Best Value CA", "Social Enterprise"],
    highlights: [
      "Not-for-profit insurer",
      "Affordable premiums",
      "Integrated health platform",
    ],
    pros: [
      "Not-for-profit (better value)",
      "Affordable premiums",
      "Good digital platform",
      "Social impact focus",
    ],
    cons: [
      "Smaller network",
      "Less brand recognition",
      "Fewer plan tiers",
    ],
    affiliateUrl: "#",
    description:
      "Green Shield Canada is a not-for-profit health benefits provider offering affordable coverage with a social enterprise mission.",
    coverageDetails: {
      hospitalization: false,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Green Shield's not-for-profit model delivers excellent value and has been a pioneer in integrating health services with benefits.",
    editorialSource: "Globe and Mail Benefits Review 2025",
  },
  {
    id: "ca-canada-life",
    name: "Canada Life Health",
    provider: "Canada Life",
    country: "Canada",
    countryCode: "ca",
    logo: "/logos/canadalife.svg",
    rating: 4.1,
    reviewCount: 5678,
    monthlyPremium: "CAD 75 - CAD 320",
    deductible: "CAD 0 - CAD 500",
    coverageType: "comprehensive",
    badges: ["Best Group Plans CA"],
    highlights: [
      "Strong group benefits",
      "Comprehensive coverage",
      "Long heritage in Canada",
    ],
    pros: [
      "Strong employer group plans",
      "Comprehensive coverage options",
      "Long Canadian heritage",
      "Good financial stability",
    ],
    cons: [
      "Individual plans less competitive",
      "Customer service varies",
      "Digital tools improving",
    ],
    affiliateUrl: "#",
    description:
      "Canada Life is one of the country's largest insurers, offering comprehensive group and individual health benefits with deep Canadian roots.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Canada Life offers robust group health benefits backed by over 175 years of insurance experience in Canada.",
    editorialSource: "Insurance Business Canada Awards 2025",
  },
  {
    id: "ca-bluecross",
    name: "Blue Cross Individual Health",
    provider: "Blue Cross",
    country: "Canada",
    countryCode: "ca",
    logo: "/logos/bcbs.svg",
    rating: 4.0,
    reviewCount: 3456,
    monthlyPremium: "CAD 60 - CAD 280",
    deductible: "CAD 0 - CAD 500",
    coverageType: "standard",
    badges: ["Best Individual Plans CA"],
    highlights: [
      "Strong individual plan focus",
      "Travel health included",
      "Provincial availability",
    ],
    pros: [
      "Good individual plan options",
      "Travel health coverage included",
      "Available across provinces",
      "Straightforward plans",
    ],
    cons: [
      "Provincial organizations vary",
      "Group plans less competitive",
      "Benefits vary by province",
    ],
    affiliateUrl: "#",
    description:
      "Blue Cross operates provincially across Canada, offering individual and travel health insurance with straightforward plan structures.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Blue Cross is a reliable choice for individual Canadians seeking supplementary coverage, especially with travel benefits.",
    editorialSource: "Ratehub Insurance Review 2025",
  },

  // Australia
  {
    id: "au-medibank",
    name: "Medibank Private",
    provider: "Medibank",
    country: "Australia",
    countryCode: "au",
    logo: "/logos/medibank.svg",
    rating: 4.3,
    reviewCount: 8765,
    monthlyPremium: "AUD 120 - AUD 450",
    deductible: "AUD 0 - AUD 750",
    coverageType: "comprehensive",
    badges: ["#1 in Australia", "Most Members"],
    highlights: [
      "Australia's largest health insurer",
      "Comprehensive hospital + extras",
      "Telehealth included",
    ],
    pros: [
      "Largest provider in Australia",
      "Comprehensive plan range",
      "Good telehealth services",
      "Wide hospital agreements",
    ],
    cons: [
      "Premium pricing",
      "Waiting periods apply",
      "Some extras have limits",
    ],
    affiliateUrl: "#",
    description:
      "Medibank is Australia's largest private health insurer, offering a comprehensive range of hospital and extras cover plans.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Medibank remains Australia's go-to private health insurer with the widest range of plans and hospital agreements.",
    editorialSource: "Canstar Outstanding Value Awards 2025",
  },
  {
    id: "au-bupa-au",
    name: "Bupa Australia",
    provider: "Bupa",
    country: "Australia",
    countryCode: "au",
    logo: "/logos/bupa.svg",
    rating: 4.4,
    reviewCount: 7654,
    monthlyPremium: "AUD 110 - AUD 420",
    deductible: "AUD 0 - AUD 750",
    coverageType: "comprehensive",
    badges: ["Best Extras Cover", "Best International AU"],
    highlights: [
      "Strong extras coverage",
      "Global brand with local expertise",
      "Bupa owned hospitals",
    ],
    pros: [
      "Excellent extras cover",
      "Own hospital network",
      "International brand backing",
      "Good preventive coverage",
    ],
    cons: [
      "Can be pricier than budget options",
      "Waiting periods",
      "Some plans complex",
    ],
    affiliateUrl: "#",
    description:
      "Bupa Australia offers comprehensive private health insurance with strong extras coverage and its own network of hospitals and clinics.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa's combination of owned hospitals and comprehensive extras cover makes it a premium choice in Australia.",
    editorialSource: "Finder Insurance Awards 2025",
  },
  {
    id: "au-hcf",
    name: "HCF Health Insurance",
    provider: "HCF",
    country: "Australia",
    countryCode: "au",
    logo: "/logos/hcf.svg",
    rating: 4.5,
    reviewCount: 5432,
    monthlyPremium: "AUD 100 - AUD 380",
    deductible: "AUD 0 - AUD 750",
    coverageType: "premium",
    badges: ["Best Value AU", "Most Satisfied Members"],
    highlights: [
      "Highest member satisfaction",
      "Not-for-profit value",
      "Good value premiums",
    ],
    pros: [
      "Best value for money",
      "Highest customer satisfaction",
      "Not-for-profit model",
      "Good dental extras",
    ],
    cons: [
      "Primarily NSW focused",
      "Smaller network than Medibank",
      "Limited in some states",
    ],
    affiliateUrl: "#",
    description:
      "HCF is a not-for-profit health insurer consistently rated highest for member satisfaction and value in Australia.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "HCF delivers the best combination of value and satisfaction in Australian private health insurance.",
    editorialSource: "Choice Magazine Insurance Review 2025",
  },
  {
    id: "au-nib",
    name: "nib Health Insurance",
    provider: "nib",
    country: "Australia",
    countryCode: "au",
    logo: "/logos/nib.svg",
    rating: 4.2,
    reviewCount: 4321,
    monthlyPremium: "AUD 95 - AUD 370",
    deductible: "AUD 0 - AUD 750",
    coverageType: "standard",
    badges: ["Best Digital AU", "Rising Star"],
    highlights: [
      "Strong digital experience",
      "Competitive pricing",
      "Growing provider network",
    ],
    pros: [
      "Best-in-class mobile app",
      "Competitive premiums",
      "Growing network",
      "Good for young people",
    ],
    cons: [
      "Smaller than Medibank/Bupa",
      "Network still growing",
      "Some limits on extras",
    ],
    affiliateUrl: "#",
    description:
      "nib offers competitive private health insurance with an award-winning digital experience and growing provider network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "nib's digital-first approach and competitive pricing make it increasingly popular with younger Australians.",
    editorialSource: "Mozo Experts Choice Awards 2025",
  },
  {
    id: "au-ahm",
    name: "ahm Health Insurance",
    provider: "ahm (Medibank subsidiary)",
    country: "Australia",
    countryCode: "au",
    logo: "/logos/ahm.svg",
    rating: 4.0,
    reviewCount: 3456,
    monthlyPremium: "AUD 80 - AUD 320",
    deductible: "AUD 250 - AUD 750",
    coverageType: "basic",
    badges: ["Budget Pick AU"],
    highlights: [
      "Most affordable major insurer",
      "Medibank network access",
      "Simple plan structures",
    ],
    pros: [
      "Very affordable premiums",
      "Medibank hospital agreements",
      "Simple easy-to-understand plans",
      "Good for young and healthy",
    ],
    cons: [
      "Limited extras coverage",
      "Basic customer service",
      "Fewer plan options",
    ],
    affiliateUrl: "#",
    description:
      "ahm (a Medibank subsidiary) offers affordable private health insurance with access to Medibank's hospital network at lower premiums.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "ahm provides an affordable entry point into private health insurance, ideal for young Australians avoiding the Medicare Levy Surcharge.",
    editorialSource: "Finder Budget Insurance Awards 2025",
  },

  // France
  {
    id: "fr-axa-fr",
    name: "AXA Mutuelle Santé",
    provider: "AXA France",
    country: "France",
    countryCode: "fr",
    logo: "/logos/axa.svg",
    rating: 4.3,
    reviewCount: 6789,
    monthlyPremium: "€50 - €180",
    deductible: "€0",
    coverageType: "comprehensive",
    badges: ["#1 in France", "Best Overall FR"],
    highlights: [
      "France's largest health insurer",
      "Comprehensive complementary coverage",
      "Fast reimbursements",
    ],
    pros: [
      "Widest coverage options",
      "Fast reimbursement process",
      "Comprehensive dental/optical",
      "Strong brand stability",
    ],
    cons: [
      "Premium pricing",
      "Complex plan tiers",
      "Customer service can be slow",
    ],
    affiliateUrl: "#",
    description:
      "AXA is France's leading complementary health insurer (mutuelle), covering co-payments and providing additional benefits beyond the public system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA dominates the French mutuelle market with the most comprehensive complementary coverage options available.",
    editorialSource: "Que Choisir Assurance Santé 2025",
  },
  {
    id: "fr-harmonie",
    name: "Harmonie Mutuelle",
    provider: "Harmonie",
    country: "France",
    countryCode: "fr",
    logo: "/logos/harmonie.svg",
    rating: 4.4,
    reviewCount: 5432,
    monthlyPremium: "€40 - €150",
    deductible: "€0",
    coverageType: "premium",
    badges: ["Best Mutuelle", "Best Value FR"],
    highlights: [
      "Largest mutual health insurer",
      "Excellent value",
      "Strong social commitment",
    ],
    pros: [
      "Excellent value for money",
      "Largest mutual insurer in France",
      "Good dental coverage",
      "Social enterprise values",
    ],
    cons: [
      "Less international coverage",
      "Basic digital tools",
      "Processing times variable",
    ],
    affiliateUrl: "#",
    description:
      "Harmonie Mutuelle is France's largest mutual health insurer, offering excellent value complementary coverage with a social enterprise ethos.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Harmonie Mutuelle offers the best balance of coverage and cost in the French complementary health insurance market.",
    editorialSource: "60 Millions de Consommateurs 2025",
  },
  {
    id: "fr-alan",
    name: "Alan Health Insurance",
    provider: "Alan",
    country: "France",
    countryCode: "fr",
    logo: "/logos/alan.svg",
    rating: 4.5,
    reviewCount: 3456,
    monthlyPremium: "€45 - €160",
    deductible: "€0",
    coverageType: "premium",
    badges: ["Most Innovative FR", "Best Digital FR", "Rising Star"],
    highlights: [
      "100% digital health insurer",
      "Instant reimbursements",
      "Best-in-class app",
    ],
    pros: [
      "Fully digital experience",
      "Instant reimbursements",
      "Transparent pricing",
      "Excellent user experience",
    ],
    cons: [
      "Newer company (less track record)",
      "Primarily employer-focused",
      "Limited physical presence",
    ],
    affiliateUrl: "#",
    description:
      "Alan is France's first fully digital health insurer, offering instant reimbursements and a seamless digital experience.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Alan has revolutionized French health insurance with its fully digital model, instant reimbursements, and transparent pricing.",
    editorialSource: "Les Echos Innovation Santé 2025",
  },
  {
    id: "fr-generali",
    name: "Generali Vitality Santé",
    provider: "Generali",
    country: "France",
    countryCode: "fr",
    logo: "/logos/generali.svg",
    rating: 4.1,
    reviewCount: 4567,
    monthlyPremium: "€45 - €170",
    deductible: "€0",
    coverageType: "standard",
    badges: ["Best Wellness FR"],
    highlights: [
      "Vitality wellness program",
      "International brand",
      "Good employer plans",
    ],
    pros: [
      "Wellness incentive program",
      "Strong employer plans",
      "International backing",
      "Competitive pricing",
    ],
    cons: [
      "Less established than mutuelle competitors",
      "Wellness program adds complexity",
      "Customer service varies",
    ],
    affiliateUrl: "#",
    description:
      "Generali offers health insurance in France with a focus on wellness incentives through its Vitality program.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Generali's Vitality program brings a unique wellness dimension to French complementary health insurance.",
    editorialSource: "Le Figaro Santé Insurance Guide 2025",
  },
  {
    id: "fr-malakoff",
    name: "Malakoff Humanis Santé",
    provider: "Malakoff Humanis",
    country: "France",
    countryCode: "fr",
    logo: "/logos/malakoff.svg",
    rating: 4.0,
    reviewCount: 3890,
    monthlyPremium: "€42 - €155",
    deductible: "€0",
    coverageType: "standard",
    badges: ["Best Employer Plans FR"],
    highlights: [
      "Leading employer group insurer",
      "Strong social protection",
      "Comprehensive collective plans",
    ],
    pros: [
      "Top employer group plans",
      "Strong social protection focus",
      "Good collective bargaining rates",
      "Comprehensive options",
    ],
    cons: [
      "Individual plans less competitive",
      "Brand less known to individuals",
      "Digital experience improving",
    ],
    affiliateUrl: "#",
    description:
      "Malakoff Humanis is a leading French social protection group, particularly strong in employer-sponsored health insurance.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Malakoff Humanis excels in collective health insurance for French employers, with competitive group rates.",
    editorialSource: "L'Argus de l'Assurance 2025",
  },

  // Japan
  {
    id: "jp-nippon",
    name: "Nippon Life Insurance",
    provider: "Nippon Life",
    country: "Japan",
    countryCode: "jp",
    logo: "/logos/nippon.svg",
    rating: 4.4,
    reviewCount: 12345,
    monthlyPremium: "¥3,000 - ¥15,000",
    deductible: "¥0",
    coverageType: "comprehensive",
    badges: ["#1 in Japan", "Most Trusted JP"],
    highlights: [
      "Japan's largest life/health insurer",
      "Comprehensive medical insurance",
      "Strong financial stability",
    ],
    pros: [
      "Largest insurer in Japan",
      "Very strong financial stability",
      "Comprehensive medical coverage",
      "Extensive agent network",
    ],
    cons: [
      "Traditional sales approach",
      "Complex product structures",
      "Premium pricing",
    ],
    affiliateUrl: "#",
    description:
      "Nippon Life is Japan's largest insurance company, offering comprehensive supplementary medical insurance to complement the national health system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Nippon Life remains the gold standard in Japanese medical insurance, trusted by millions for comprehensive supplementary coverage.",
    editorialSource: "Nikkei Insurance Rankings 2025",
  },
  {
    id: "jp-aflac",
    name: "Aflac Japan Medical",
    provider: "Aflac",
    country: "Japan",
    countryCode: "jp",
    logo: "/logos/aflac.svg",
    rating: 4.3,
    reviewCount: 9876,
    monthlyPremium: "¥2,500 - ¥12,000",
    deductible: "¥0",
    coverageType: "premium",
    badges: ["Best Cancer Insurance", "Innovation Leader JP"],
    highlights: [
      "Pioneer in cancer insurance",
      "Affordable supplementary plans",
      "Strong brand recognition",
    ],
    pros: [
      "Leading cancer insurance coverage",
      "Affordable premiums",
      "Simple product design",
      "Strong brand trust",
    ],
    cons: [
      "Focused mainly on specific conditions",
      "Less comprehensive than some",
      "Limited hospitalization coverage",
    ],
    affiliateUrl: "#",
    description:
      "Aflac Japan pioneered cancer insurance and is one of the most recognized supplementary health insurers in Japan.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Aflac's cancer insurance products remain unmatched in Japan, with innovative coverage that has set industry standards.",
    editorialSource: "Toyo Keizai Insurance Rankings 2025",
  },
  {
    id: "jp-sompo",
    name: "Sompo Japan Health",
    provider: "Sompo Japan",
    country: "Japan",
    countryCode: "jp",
    logo: "/logos/sompo.svg",
    rating: 4.2,
    reviewCount: 6543,
    monthlyPremium: "¥2,800 - ¥13,000",
    deductible: "¥0",
    coverageType: "standard",
    badges: ["Best Digital JP", "Best for Seniors"],
    highlights: [
      "Digital health innovations",
      "Good senior care coverage",
      "Nursing care insurance",
    ],
    pros: [
      "Strong digital health tools",
      "Good nursing care coverage",
      "Innovative senior products",
      "Comprehensive options",
    ],
    cons: [
      "Complex product lineup",
      "Premium increases with age",
      "Less competitive for young people",
    ],
    affiliateUrl: "#",
    description:
      "Sompo Japan offers innovative health and nursing care insurance, particularly strong in coverage for Japan's aging population.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Sompo Japan leads in digital health innovation and nursing care coverage, addressing Japan's demographic challenges.",
    editorialSource: "Diamond Weekly Insurance Review 2025",
  },
  {
    id: "jp-dai-ichi",
    name: "Dai-ichi Life Medical",
    provider: "Dai-ichi Life",
    country: "Japan",
    countryCode: "jp",
    logo: "/logos/dai-ichi.svg",
    rating: 4.1,
    reviewCount: 5432,
    monthlyPremium: "¥3,200 - ¥14,000",
    deductible: "¥0",
    coverageType: "comprehensive",
    badges: ["Best Financial Stability JP"],
    highlights: [
      "Strong financial ratings",
      "Comprehensive medical plans",
      "Global insurance group",
    ],
    pros: [
      "Very strong financial stability",
      "Comprehensive medical coverage",
      "Global group backing",
      "Good claims processing",
    ],
    cons: [
      "Traditional business model",
      "Higher premiums",
      "Complex applications",
    ],
    affiliateUrl: "#",
    description:
      "Dai-ichi Life is one of Japan's top insurance groups, offering comprehensive medical insurance backed by strong financial stability.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Dai-ichi Life's financial strength and comprehensive coverage make it a reliable choice for long-term medical insurance.",
    editorialSource: "S&P Japan Insurance Ratings 2025",
  },

  // Brazil
  {
    id: "br-amil",
    name: "Amil Saúde",
    provider: "Amil (UnitedHealth)",
    country: "Brazil",
    countryCode: "br",
    logo: "/logos/amil.svg",
    rating: 4.2,
    reviewCount: 8765,
    monthlyPremium: "R$ 400 - R$ 2,000",
    deductible: "R$ 0",
    coverageType: "comprehensive",
    badges: ["#1 in Brazil", "Largest Network BR"],
    highlights: [
      "Brazil's largest health insurer",
      "Extensive hospital network",
      "UnitedHealth Group backed",
    ],
    pros: [
      "Largest network in Brazil",
      "International backing",
      "Wide range of plans",
      "Good specialist access",
    ],
    cons: [
      "Premium pricing",
      "Customer service complaints",
      "Wait times at popular facilities",
    ],
    affiliateUrl: "#",
    description:
      "Amil (part of UnitedHealth Group) is Brazil's largest private health insurer with the most extensive hospital and clinic network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Amil's vast network and UnitedHealth backing make it Brazil's most comprehensive private health insurance option.",
    editorialSource: "Folha de São Paulo Health Insurance Guide 2025",
  },
  {
    id: "br-sulamerica",
    name: "SulAmérica Saúde",
    provider: "SulAmérica",
    country: "Brazil",
    countryCode: "br",
    logo: "/logos/sulamerica.svg",
    rating: 4.3,
    reviewCount: 6543,
    monthlyPremium: "R$ 350 - R$ 1,800",
    deductible: "R$ 0",
    coverageType: "premium",
    badges: ["Best Premium BR", "Best Service BR"],
    highlights: [
      "Premium service quality",
      "Excellent hospital partnerships",
      "Strong digital platform",
    ],
    pros: [
      "Superior service quality",
      "Top hospital partnerships",
      "Good digital experience",
      "Comprehensive premium plans",
    ],
    cons: [
      "Higher pricing tier",
      "Limited budget options",
      "Regional availability varies",
    ],
    affiliateUrl: "#",
    description:
      "SulAmérica is known for premium health insurance service quality in Brazil, with partnerships with the country's best hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "SulAmérica delivers the premium health insurance experience in Brazil, consistently rated highest for service quality.",
    editorialSource: "Exame Melhores Planos de Saúde 2025",
  },
  {
    id: "br-bradesco",
    name: "Bradesco Saúde",
    provider: "Bradesco Seguros",
    country: "Brazil",
    countryCode: "br",
    logo: "/logos/bradesco.svg",
    rating: 4.1,
    reviewCount: 7654,
    monthlyPremium: "R$ 300 - R$ 1,600",
    deductible: "R$ 0",
    coverageType: "standard",
    badges: ["Best Value BR", "Bank Integration"],
    highlights: [
      "Banking integration advantages",
      "Competitive pricing",
      "Wide regional coverage",
    ],
    pros: [
      "Competitive pricing",
      "Bradesco bank integration",
      "Good regional coverage",
      "Solid plan range",
    ],
    cons: [
      "Service quality varies",
      "Less premium feel",
      "Network varies by region",
    ],
    affiliateUrl: "#",
    description:
      "Bradesco Saúde offers competitive health insurance through Brazil's banking network, with good value across a range of plans.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Bradesco Saúde leverages Brazil's banking infrastructure to offer well-priced health insurance with convenient access.",
    editorialSource: "Valor Econômico Insurance Rankings 2025",
  },
  {
    id: "br-unimed",
    name: "Unimed Nacional",
    provider: "Unimed",
    country: "Brazil",
    countryCode: "br",
    logo: "/logos/unimed.svg",
    rating: 4.0,
    reviewCount: 9876,
    monthlyPremium: "R$ 250 - R$ 1,400",
    deductible: "R$ 0",
    coverageType: "standard",
    badges: ["Largest Cooperative", "Best Regional BR"],
    highlights: [
      "Medical cooperative model",
      "Nationwide cooperative network",
      "Doctor-owned and operated",
    ],
    pros: [
      "Unique cooperative model",
      "Nationwide presence",
      "Doctor-centric approach",
      "Good local networks",
    ],
    cons: [
      "Quality varies by cooperative",
      "Fragmented experience",
      "Digital tools lag behind",
    ],
    affiliateUrl: "#",
    description:
      "Unimed is the world's largest medical cooperative, operating across Brazil with a doctor-owned model providing local healthcare networks.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Unimed's cooperative model gives it unmatched local presence across Brazil, though service consistency varies.",
    editorialSource: "Proteste Consumer Guide 2025",
  },

  // South Africa
  {
    id: "za-discovery",
    name: "Discovery Health",
    provider: "Discovery",
    country: "South Africa",
    countryCode: "za",
    logo: "/logos/discovery.svg",
    rating: 4.6,
    reviewCount: 8765,
    monthlyPremium: "ZAR 2,500 - ZAR 12,000",
    deductible: "ZAR 0 - ZAR 5,000",
    coverageType: "comprehensive",
    badges: ["#1 in South Africa", "Best Innovation", "Vitality Pioneer"],
    highlights: [
      "South Africa's largest medical scheme",
      "Pioneer of Vitality wellness",
      "Comprehensive plan range",
    ],
    pros: [
      "Industry-leading Vitality program",
      "Largest medical scheme in SA",
      "Comprehensive coverage options",
      "Innovative digital tools",
    ],
    cons: [
      "Premium pricing",
      "Complex plan structures",
      "Vitality engagement required for best value",
    ],
    affiliateUrl: "#",
    description:
      "Discovery Health is South Africa's largest open medical scheme administrator, famous for pioneering the Vitality wellness incentive program.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Discovery Health has transformed South African healthcare with its Vitality model, now exported to 40+ countries.",
    editorialSource: "Financial Mail Top Medical Schemes 2025",
  },
  {
    id: "za-bonitas",
    name: "Bonitas Medical Fund",
    provider: "Bonitas",
    country: "South Africa",
    countryCode: "za",
    logo: "/logos/bonitas.svg",
    rating: 4.2,
    reviewCount: 4567,
    monthlyPremium: "ZAR 2,000 - ZAR 8,000",
    deductible: "ZAR 0 - ZAR 3,000",
    coverageType: "standard",
    badges: ["Best Value ZA", "Most Affordable Open Scheme"],
    highlights: [
      "Affordable open medical scheme",
      "Good value for money",
      "Solid hospital coverage",
    ],
    pros: [
      "Most affordable open scheme",
      "Good value for money",
      "Solid hospital plan options",
      "No waiting period for newborns",
    ],
    cons: [
      "Smaller network than Discovery",
      "Fewer digital tools",
      "Limited extras on basic plans",
    ],
    affiliateUrl: "#",
    description:
      "Bonitas is one of South Africa's largest open medical schemes, offering affordable coverage with good value across multiple plan options.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Bonitas offers the best value among South Africa's open medical schemes, making private healthcare more accessible.",
    editorialSource: "Business Day Medical Schemes Review 2025",
  },
  {
    id: "za-momentum",
    name: "Momentum Health",
    provider: "Momentum Metropolitan",
    country: "South Africa",
    countryCode: "za",
    logo: "/logos/momentum.svg",
    rating: 4.3,
    reviewCount: 5432,
    monthlyPremium: "ZAR 2,200 - ZAR 10,000",
    deductible: "ZAR 0 - ZAR 4,000",
    coverageType: "premium",
    badges: ["Best Customer Service ZA", "Innovation Award"],
    highlights: [
      "Strong customer service",
      "Multiply wellness rewards",
      "Good chronic condition coverage",
    ],
    pros: [
      "Excellent customer service",
      "Multiply wellness program",
      "Good chronic care coverage",
      "Strong digital platform",
    ],
    cons: [
      "Mid-range pricing",
      "Network smaller than Discovery",
      "Some plan restrictions",
    ],
    affiliateUrl: "#",
    description:
      "Momentum Health Solutions offers medical scheme administration with strong customer service and the Multiply wellness rewards program.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Momentum Health delivers excellent customer service and solid coverage, with the Multiply program adding genuine value.",
    editorialSource: "Sunday Times Top Brands Survey 2025",
  },
  {
    id: "za-medshield",
    name: "Medshield Medical Scheme",
    provider: "Medshield",
    country: "South Africa",
    countryCode: "za",
    logo: "/logos/medshield.svg",
    rating: 4.0,
    reviewCount: 2345,
    monthlyPremium: "ZAR 1,800 - ZAR 7,500",
    deductible: "ZAR 0 - ZAR 3,000",
    coverageType: "basic",
    badges: ["Budget Pick ZA"],
    highlights: [
      "Budget-friendly medical scheme",
      "Good hospital plans",
      "Long-standing scheme",
    ],
    pros: [
      "Affordable contributions",
      "Good hospital plan options",
      "Long operating history",
      "Simple plan structures",
    ],
    cons: [
      "Limited extras",
      "Smaller network",
      "Basic digital experience",
    ],
    affiliateUrl: "#",
    description:
      "Medshield is a long-standing South African medical scheme offering affordable healthcare coverage with straightforward plan options.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Medshield provides affordable medical scheme cover for South Africans seeking reliable hospital and day-to-day benefits.",
    editorialSource: "CMS Annual Report Medical Schemes 2025",
  },

  // India
  {
    id: "in-star",
    name: "Star Health Insurance",
    provider: "Star Health",
    country: "India",
    countryCode: "in",
    logo: "/logos/star.svg",
    rating: 4.4,
    reviewCount: 15678,
    monthlyPremium: "₹500 - ₹3,000",
    deductible: "₹0 - ₹25,000",
    coverageType: "comprehensive",
    badges: ["#1 in India", "Best Health Insurer", "Most Trusted"],
    highlights: [
      "India's largest standalone health insurer",
      "13,000+ network hospitals",
      "Cashless claims",
    ],
    pros: [
      "Largest dedicated health insurer",
      "Massive hospital network",
      "Fast cashless claims",
      "Wide range of plans",
    ],
    cons: [
      "Some co-payment on plans",
      "Premium increases with claims",
      "Room rent limits on some plans",
    ],
    affiliateUrl: "#",
    description:
      "Star Health is India's largest standalone health insurance company, with over 13,000 network hospitals and a focus on cashless treatment.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Star Health dominates India's health insurance market with the widest hospital network and fastest cashless claims processing.",
    editorialSource: "IRDA Insurance Rankings 2025",
  },
  {
    id: "in-hdfc-ergo",
    name: "HDFC ERGO Health",
    provider: "HDFC ERGO",
    country: "India",
    countryCode: "in",
    logo: "/logos/hdfc.svg",
    rating: 4.3,
    reviewCount: 12345,
    monthlyPremium: "₹450 - ₹2,800",
    deductible: "₹0 - ₹20,000",
    coverageType: "comprehensive",
    badges: ["Best Digital IN", "Innovation Leader"],
    highlights: [
      "Best digital health platform",
      "HDFC banking integration",
      "Innovative product design",
    ],
    pros: [
      "Excellent digital platform",
      "HDFC bank integration",
      "Innovative products",
      "Good claims ratio",
    ],
    cons: [
      "Newer to health insurance",
      "Network still growing",
      "Some plans have sub-limits",
    ],
    affiliateUrl: "#",
    description:
      "HDFC ERGO offers innovative health insurance with industry-leading digital tools, backed by the trusted HDFC brand.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "HDFC ERGO leads India's digital health insurance transformation with innovative products and seamless online experiences.",
    editorialSource: "Economic Times Insurance Awards 2025",
  },
  {
    id: "in-icici-lombard",
    name: "ICICI Lombard Health",
    provider: "ICICI Lombard",
    country: "India",
    countryCode: "in",
    logo: "/logos/icici.svg",
    rating: 4.2,
    reviewCount: 9876,
    monthlyPremium: "₹400 - ₹2,500",
    deductible: "₹0 - ₹20,000",
    coverageType: "standard",
    badges: ["Best Claims Process IN", "Trusted Brand"],
    highlights: [
      "Fast claims settlement",
      "ICICI banking network",
      "Comprehensive coverage options",
    ],
    pros: [
      "Quick claims processing",
      "ICICI banking integration",
      "Good network hospitals",
      "Reliable brand",
    ],
    cons: [
      "Room rent capping on some plans",
      "Co-payment requirements",
      "Limited customization",
    ],
    affiliateUrl: "#",
    description:
      "ICICI Lombard provides reliable health insurance with fast claims settlement and the backing of India's ICICI banking network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "ICICI Lombard's claims settlement speed and reliability make it one of India's most trusted health insurers.",
    editorialSource: "Mint Insurance Rankings 2025",
  },
  {
    id: "in-niva-bupa",
    name: "Niva Bupa Health Insurance",
    provider: "Niva Bupa",
    country: "India",
    countryCode: "in",
    logo: "/logos/niva-bupa.svg",
    rating: 4.1,
    reviewCount: 6543,
    monthlyPremium: "₹500 - ₹3,200",
    deductible: "₹0 - ₹30,000",
    coverageType: "premium",
    badges: ["Best International IN", "Premium Choice"],
    highlights: [
      "Bupa global expertise",
      "Premium plan options",
      "Good international coverage",
    ],
    pros: [
      "Bupa international backing",
      "Premium coverage options",
      "Some international coverage",
      "Good for senior citizens",
    ],
    cons: [
      "Higher premiums",
      "Smaller network than Star",
      "Complex plan tiers",
    ],
    affiliateUrl: "#",
    description:
      "Niva Bupa (formerly Max Bupa) combines Bupa's global healthcare expertise with local Indian market knowledge for premium health coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Niva Bupa brings global insurance expertise to India, offering some of the most comprehensive premium health plans available.",
    editorialSource: "Business Standard Insurance Guide 2025",
  },
  {
    id: "in-care",
    name: "Care Health Insurance",
    provider: "Care Health (formerly Religare)",
    country: "India",
    countryCode: "in",
    logo: "/logos/care.svg",
    rating: 4.0,
    reviewCount: 8765,
    monthlyPremium: "₹350 - ₹2,200",
    deductible: "₹0 - ₹15,000",
    coverageType: "standard",
    badges: ["Best Value IN", "Best for Families"],
    highlights: [
      "Affordable family plans",
      "No room rent limits on top plans",
      "Good claims ratio",
    ],
    pros: [
      "Very affordable premiums",
      "Good family floater plans",
      "No room rent limits (top plans)",
      "High claims settlement ratio",
    ],
    cons: [
      "Recent brand change (Religare to Care)",
      "Network growing",
      "Digital platform catching up",
    ],
    affiliateUrl: "#",
    description:
      "Care Health Insurance (formerly Religare) offers affordable health coverage with a focus on family plans and high claims settlement ratios.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Care Health delivers excellent value in Indian health insurance, with competitive family plans and strong claims ratios.",
    editorialSource: "PolicyBazaar Insurance Awards 2025",
  },
];

export function getCountries(): Country[] {
  return countries;
}

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}

export function getPlansByCountry(countryCode: string): InsurancePlan[] {
  return insurancePlans.filter((p) => p.countryCode === countryCode);
}

export function getPlanById(id: string): InsurancePlan | undefined {
  return insurancePlans.find((p) => p.id === id);
}

export function getCountriesByRegion(region: string): Country[] {
  return countries.filter((c) => c.region === region);
}
