import { InsurancePlan } from "./types";

export const plansOceania: InsurancePlan[] = [
  // ─── NEW ZEALAND ──────────────────────────────────────────────────────────────
  {
    id: "nz-southerncross-1",
    name: "Southern Cross Health Insurance",
    provider: "Southern Cross Health Society",
    country: "New Zealand",
    countryCode: "NZ",
    logo: "/logos/southerncross.svg",
    rating: 4.3,
    reviewCount: 38400,
    monthlyPremium: "NZ$ 60–NZ$ 450 / mo",
    deductible: "NZ$ 0–NZ$ 2,000 (excess option)",
    coverageType: "comprehensive",
    badges: [
      "S&P A+ (Strong)",
      "Reader's Digest Most Trusted 2017–2025",
      "1 in 5 New Zealanders Covered",
    ],
    highlights: [
      "New Zealand's largest health insurer covering more than 951,000 members",
      "Pays over 68% of the total value of all NZ health insurance claims",
      "S&P A+ (Strong) financial strength rating; Reader's Digest Most Trusted 2017–2025",
    ],
    pros: [
      "Dominant market position with the broadest hospital specialist network in NZ",
      "Choosing a higher excess reduces premiums by 20–40%",
      "Pays NZ$ 4.7 million in health claims every single day",
    ],
    cons: [
      "Premiums rising 10–30% annually for many members in 2024–2025",
      "Comprehensive plans for policyholders over 50 can be significantly more expensive",
    ],
    affiliateUrl: "https://www.southerncross.co.nz",
    description:
      "Southern Cross Health Society is New Zealand's dominant health insurer, covering more than 951,000 Kiwis and paying 68% of all health insurance claims in the country. The S&P A+ rated not-for-profit society has earned Reader's Digest Most Trusted Health Insurance Brand every year from 2017 to 2025.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Southern Cross's nine consecutive Reader's Digest Most Trusted awards are earned, not just claimed — the society's claims volume and paying speed are benchmarks that every other New Zealand health insurer measures itself against.",
    editorialSource: "Southern Cross Health Insurance Canstar NZ Review; MoneyHub NZ Southern Cross Premium Guide 2025",
  },
  {
    id: "nz-nib-1",
    name: "nib NZ Health Insurance",
    provider: "nib New Zealand",
    country: "New Zealand",
    countryCode: "NZ",
    logo: "/logos/nib.svg",
    rating: 3.8,
    reviewCount: 14200,
    monthlyPremium: "NZ$ 55–NZ$ 380 / mo",
    deductible: "NZ$ 0",
    coverageType: "standard",
    badges: ["2nd Largest NZ Health Insurer", "Product Refresh 2024", "Hospital & Everyday Plans"],
    highlights: [
      "nib is New Zealand's second-largest health insurer",
      "February 2024 product refresh improved benefit limits with no premium impact",
      "Offers Standard and Premium cover plus Everyday day-to-day plan add-ons",
    ],
    pros: [
      "Second-largest market position means strong hospital network coverage",
      "2024 product refresh delivered more value without premium increases",
      "Clear plan structure: Hospital plans plus optional Everyday add-ons",
    ],
    cons: [
      "Trustpilot NZ rating of 2.3/5 citing significant premium increases for existing members",
      "Quarterly rate reviews mean premiums are not locked for the year",
    ],
    affiliateUrl: "https://www.nib.co.nz",
    description:
      "nib is New Zealand's second-largest health insurer, offering Standard and Premium Hospital plans alongside optional Everyday cover for day-to-day costs. A February 2024 product refresh raised benefit limits without changing premiums for existing members.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "nib's 2024 product refresh showed genuine commitment to member value, but the quarterly rate review model means policyholders need to budget carefully for potential premium adjustments throughout the year.",
    editorialSource: "Canstar NZ nib Health Insurance Review; nib NZ Product Refresh February 2024; Trustpilot nib.co.nz",
  },
  {
    id: "nz-unimed-1",
    name: "UniMed Health Insurance",
    provider: "UniMed (Union Medical Benefits Society)",
    country: "New Zealand",
    countryCode: "NZ",
    logo: "/logos/unimed.svg",
    rating: 4.1,
    reviewCount: 8600,
    monthlyPremium: "NZ$ 50–NZ$ 320 / mo",
    deductible: "NZ$ 0",
    coverageType: "standard",
    badges: ["3rd Largest NZ Insurer", "140K+ Members", "Not-For-Profit"],
    highlights: [
      "UniMed acquired Accuro in 2024, becoming New Zealand's third-largest health insurer",
      "Now covers 140,000+ members with combined Accuro and UniMed books",
      "Not-for-profit structure means surplus returned to members",
    ],
    pros: [
      "Third-largest market position after acquiring Accuro's 30,000 members",
      "Not-for-profit model aligns insurer interests with members",
      "StaffCare plans for businesses and SmartCare plans for individuals",
    ],
    cons: [
      "Brand transition for Accuro members may cause temporary confusion",
      "Smaller scale than Southern Cross or nib limits some specialist network breadth",
    ],
    affiliateUrl: "https://unimed.co.nz",
    description:
      "UniMed became New Zealand's third-largest health insurer in 2024 after acquiring Accuro Health Insurance's portfolio of 30,000 members. The not-for-profit society now covers 140,000+ members, offering SmartCare individual plans and StaffCare business plans.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "UniMed's acquisition of Accuro creates New Zealand's third health insurance force with genuine scale, combining Accuro's health-sector roots with UniMed's not-for-profit member focus.",
    editorialSource: "UniMed Now New Zealand's Third Largest Health Insurer — Scoop June 2024; Insurance Business NZ UniMed Accuro Deal",
  },
  {
    id: "nz-accuro-1",
    name: "Accuro (now UniMed) SmartCare+",
    provider: "Accuro (now part of UniMed)",
    country: "New Zealand",
    countryCode: "NZ",
    logo: "/logos/unimed.svg",
    rating: 4.2,
    reviewCount: 6800,
    monthlyPremium: "NZ$ 45–NZ$ 300 / mo",
    deductible: "NZ$ 0",
    coverageType: "standard",
    badges: ["Founded 1971", "Health Sector Heritage", "Now UniMed Backed"],
    highlights: [
      "Accuro founded 1971 as a not-for-profit insurer for hospital staff",
      "Portfolio transferred to UniMed in 2024 — coverage and premiums unchanged",
      "SmartCare+ provides faster access to diagnostic tests and surgery",
    ],
    pros: [
      "Strong health-sector trust built over five decades",
      "UniMed backing now provides stronger financial security for members",
      "SmartCare+ enables faster specialist access versus public system waits",
    ],
    cons: [
      "Accuro brand being phased out under UniMed consolidation",
      "AM Best pulled Accuro ratings following portfolio transfer",
    ],
    affiliateUrl: "https://www.accuro.co.nz",
    description:
      "Accuro began in 1971 serving New Zealand hospital staff and opened to all New Zealanders in 2007. Its portfolio was transferred to UniMed in 2024 with no changes to member coverage or premiums. SmartCare+ plans provide faster access to diagnostics and surgical treatments.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Accuro's five-decade reputation as New Zealand's health sector insurer lives on under UniMed, with the portfolio transfer providing members stronger financial backing while preserving the trusted SmartCare brand experience.",
    editorialSource: "PolicyWise NZ Accuro Health Insurance Review 2026; UniMed Accuro Members Page 2024",
  },
  {
    id: "nz-aia-1",
    name: "AIA New Zealand Health Insurance",
    provider: "AIA New Zealand",
    country: "New Zealand",
    countryCode: "NZ",
    logo: "/logos/aia.svg",
    rating: 4.2,
    reviewCount: 11800,
    monthlyPremium: "NZ$ 50–NZ$ 420 / mo",
    deductible: "NZ$ 0–NZ$ 4,000 (excess options)",
    coverageType: "comprehensive",
    badges: ["NZ's Largest Life Insurer", "NZ$ 167M Claims 2024", "AIA Vitality"],
    highlights: [
      "AIA is New Zealand's largest life insurer",
      "Paid over NZ$ 167 million in health insurance claims in 2024",
      "AIA Vitality add-on provides up to 10% premium discount in year one",
    ],
    pros: [
      "No annual limit on surgeries — both cancer and non-cancer",
      "NZ$ 500,000 extensive cancer cover for diagnosis, treatment, and recovery",
      "Excess options from NZ$ 250 to NZ$ 4,000 reduce premiums by up to 70%",
    ],
    cons: [
      "AIA Vitality health tracking required for maximum premium discount",
      "Health claims rose 6% in 2024 likely driving future premium pressure",
    ],
    affiliateUrl: "https://www.aia.co.nz/en/our-products/health-insurance.html",
    description:
      "AIA New Zealand is the country's largest life insurer and a major health insurer, paying NZ$ 167 million in health claims in 2024 with a 92–93% approval rate. The Private Health plan has no annual surgery limit, NZ$ 500,000 cancer cover, and optional AIA Vitality for a 10% first-year discount.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AIA New Zealand's combination of no annual surgery limit, a NZ$ 500,000 cancer umbrella, and flexible excess options creates one of the most personalisable health plans in the New Zealand market.",
    editorialSource: "AIA NZ Health Insurance Review — PolicyWise NZ 2026; AIA NZ 2024 Claims Statistics; Canstar NZ AIA Review",
  },

  // ─── FIJI ─────────────────────────────────────────────────────────────────────
  {
    id: "fj-fijicare-1",
    name: "FijiCare Health Insurance",
    provider: "FijiCare Insurance Limited",
    country: "Fiji",
    countryCode: "FJ",
    logo: "/logos/fijicare.svg",
    rating: 3.6,
    reviewCount: 3800,
    monthlyPremium: "FJ$ 55–FJ$ 280 / mo",
    deductible: "FJ$ 0",
    coverageType: "standard",
    badges: ["South Pacific Stock Exchange Listed", "150K+ Policyholders", "Founded 1989"],
    highlights: [
      "FijiCare is one of Fiji's largest insurers, covering 150,000+ Fijians",
      "The only insurance company listed on the South Pacific Stock Exchange since 2000",
      "First and only Fijian insurer with a mobile app for policyholders",
    ],
    pros: [
      "Only Fiji-listed insurer providing public financial transparency",
      "Mobile app enables policy management and claims access",
      "Comprehensive coverage including visa fees, airfares, and accommodation for medical overseas treatment",
    ],
    cons: [
      "Trustpilot-equivalent reviews cite poor claims experience for some policyholders",
      "Complex illness frequently requires medical evacuation to Australia or New Zealand",
    ],
    affiliateUrl: "https://www.fijicare.com.fj",
    description:
      "FijiCare Insurance Limited, founded in 1989, is Fiji's only South Pacific Stock Exchange-listed insurer and covers 150,000+ Fijians. Its medical plans cover hospitalization, visa fees, airfares, and accommodation for overseas treatment, and it operates Fiji's only insurer mobile app.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "FijiCare's stock exchange listing and mobile app make it the most transparent and digitally accessible insurer in the South Pacific island market, though policyholders should verify the specific conditions on their claims exclusion list before enrolling.",
    editorialSource: "FijiCare Insurance Official Website; Fijivillage FijiCare Launch Report; ITIJ FijiCare Travel Insurance",
  },
  {
    id: "fj-bsplife-1",
    name: "BSP Life Fiji Health Insurance",
    provider: "BSP Life (Fiji) Limited",
    country: "Fiji",
    countryCode: "FJ",
    logo: "/logos/bsplife.svg",
    rating: 3.8,
    reviewCount: 2400,
    monthlyPremium: "FJ$ 45–FJ$ 220 / mo",
    deductible: "FJ$ 0",
    coverageType: "standard",
    badges: ["BSP Group", "Bank-Backed", "RBF Licensed"],
    highlights: [
      "BSP Life is Fiji's bank-backed life and health insurer under BSP Financial Group",
      "Regulated by Reserve Bank of Fiji (RBF)",
      "Individual and group health plans distributed through BSP Bank branches",
    ],
    pros: [
      "BSP Group financial strength provides institutional stability",
      "Bank distribution makes purchasing and premium payment convenient",
      "RBF regulatory protection for policyholders",
    ],
    cons: [
      "Complex illness requires evacuation to Australia or New Zealand",
      "Bank-distribution model less personal than specialist health insurance agents",
    ],
    affiliateUrl: "https://www.bsplife.com.fj",
    description:
      "BSP Life (Fiji) Limited is the life and health insurance subsidiary of BSP Financial Group, regulated by the Reserve Bank of Fiji. Its health plans are distributed through BSP Bank's branch network, offering individual and group coverage for hospitalization and inpatient care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "BSP Life's bank-backed distribution model makes health insurance accessible to Fijians through the branch network they already use for daily banking — lowering the friction of purchasing meaningful health protection.",
    editorialSource: "RBF Fiji Licensed Insurer Register 2024; ExpatArrivals Fiji Healthcare Guide",
  },

  // ─── PAPUA NEW GUINEA ─────────────────────────────────────────────────────────
  {
    id: "pg-pacificmmi-1",
    name: "Pacific MMI Bel Isi Health Insurance",
    provider: "Pacific MMI Insurance Limited",
    country: "Papua New Guinea",
    countryCode: "PG",
    logo: "/logos/pacificmmi.svg",
    rating: 4.0,
    reviewCount: 2800,
    monthlyPremium: "PGK 150–PGK 800 / mo",
    deductible: "PGK 0",
    coverageType: "standard",
    badges: ["Operating Since 1998", "PGK 8bn Assets Protected", "98% Claims Approved"],
    highlights: [
      "Pacific MMI has operated in PNG since 1998 with General and Life Insurance licenses",
      "Bel Isi Health Care covers medical, hospital, optical, and dental services",
      "98% of claims approved within 10 business days",
    ],
    pros: [
      "PNG's most established domestic insurer with 25+ years of experience",
      "High 98% claims approval rate and fast 10-day processing",
      "Worldwide coverage (excluding Japan, Canada, USA) with medical evacuation",
    ],
    cons: [
      "Hospital network limited to Port Moresby and major PNG cities",
      "Serious illness frequently requires evacuation to Australia or Philippines",
    ],
    affiliateUrl: "https://www.pacificmmi.com",
    description:
      "Pacific MMI Insurance Limited has operated in Papua New Guinea since 1998, protecting PGK 8 billion in assets. Its Bel Isi Health Care medical plans cover hospitalization, outpatient, optical, and dental services for Single, Couple, and Family, with 98% of claims approved within 10 days.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Pacific MMI's 98% claims approval rate and 10-day processing standard set a benchmark for the Pacific insurance market, making it the most operationally reliable domestic health insurer in Papua New Guinea.",
    editorialSource: "Pacific MMI Insurance Official Website; ExpatFinancial PNG Healthcare System Guide",
  },
  {
    id: "pg-capitallife-1",
    name: "Capital Life PNG Medical Insurance",
    provider: "Capital Life Insurance (CLIC) PNG",
    country: "Papua New Guinea",
    countryCode: "PG",
    logo: "/logos/capitallife-pg.svg",
    rating: 3.8,
    reviewCount: 1600,
    monthlyPremium: "PGK 120–PGK 650 / mo",
    deductible: "PGK 0",
    coverageType: "standard",
    badges: ["BPNG Licensed", "Individual & Family", "Overseas Evacuation"],
    highlights: [
      "Capital Life Insurance provides life and medical insurance products in PNG",
      "Regulated by the Bank of Papua New Guinea (BPNG)",
      "Medical insurance covers day-to-day and hospitalization for individuals and families",
    ],
    pros: [
      "BPNG-regulated for policyholder protection",
      "Both individual and corporate medical plans available",
      "Overseas evacuation benefit included for serious conditions",
    ],
    cons: [
      "Smaller market presence than Pacific MMI",
      "Port Moresby-centric hospital network",
    ],
    affiliateUrl: "https://capgrp.com/location/papua-new-guinea/",
    description:
      "Capital Life Insurance Company in PNG, licensed by the Bank of Papua New Guinea, provides life and medical insurance for individuals, families, and corporate groups. Medical insurance covers day-to-day healthcare and hospitalization with overseas evacuation for conditions requiring specialist care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Capital Life PNG provides individuals and families with a solid BPNG-regulated alternative to Pacific MMI, with overseas evacuation cover that addresses PNG's most fundamental healthcare limitation.",
    editorialSource: "Capital Insurance Group PNG Page; Pacific Prime Papua New Guinea Healthcare Guide",
  },

  // ─── SAMOA ────────────────────────────────────────────────────────────────────
  {
    id: "ws-nric-1",
    name: "NRIC Samoa Health Insurance",
    provider: "National Reinsurance Corporation of the Pacific",
    country: "Samoa",
    countryCode: "WS",
    logo: "/logos/nric.svg",
    rating: 3.6,
    reviewCount: 680,
    monthlyPremium: "WST 50–WST 200 / mo",
    deductible: "WST 0",
    coverageType: "basic",
    badges: ["CBS Licensed", "Apia Network", "Pacific Insurer"],
    highlights: [
      "One of Samoa's licensed domestic insurance providers",
      "Regulated by the Central Bank of Samoa (CBS)",
      "Basic health plans for Samoan residents and businesses",
    ],
    pros: [
      "CBS-regulated for policyholder protection",
      "WST-denominated plans avoid currency conversion",
      "Accessible Apia hospital network for basic coverage",
    ],
    cons: [
      "Serious illness requires evacuation to New Zealand or Australia",
      "Very limited benefit amounts relative to actual medical evacuation costs",
    ],
    affiliateUrl: "https://www.nric.ws",
    description:
      "NRIC is a CBS-regulated insurer in Samoa offering basic WST-denominated health plans for Samoan residents and businesses, primarily covering hospitalization at Apia-area hospitals, with medical evacuation to New Zealand for complex conditions.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "NRIC Samoa's CBS licensing and WST pricing make it the most accessible domestic health insurance option in Samoa, though policyholders should verify that evacuation costs to New Zealand are adequately covered for serious conditions.",
    editorialSource: "Central Bank of Samoa Licensed Insurer Registry 2024",
  },
  {
    id: "ws-allianz-1",
    name: "Allianz Pacific Samoa International Plan",
    provider: "Allianz Care (for Samoa Residents)",
    country: "Samoa",
    countryCode: "WS",
    logo: "/logos/allianz.svg",
    rating: 4.0,
    reviewCount: 290,
    monthlyPremium: "$ 55–$ 280 / mo",
    deductible: "$ 500",
    coverageType: "standard",
    badges: ["International Standard", "NZ & Australia Access", "Expat Focus"],
    highlights: [
      "International plans fill the coverage gap for high-risk conditions in Samoa",
      "Medical evacuation to Auckland or Sydney is the essential benefit",
      "USD-denominated for convenience in Samoa's international business community",
    ],
    pros: [
      "Allianz Care global network covers treatment in New Zealand and Australia",
      "24/7 emergency support for a remote Pacific island context",
      "Annual plan limits up to USD 5,000,000",
    ],
    cons: [
      "USD premiums high relative to most Samoan incomes",
      "Primarily serves expatriates and high-income Samoans",
    ],
    affiliateUrl: "https://www.allianzcare.com",
    description:
      "Allianz Care's international plans are the primary comprehensive health insurance option for expatriates and high-income Samoans, providing medical evacuation coverage to Auckland or Sydney for conditions that exceed Samoa's local healthcare capacity.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "For serious health events in Samoa, the choice of insurer matters less than whether the policy includes medical evacuation to Auckland — Allianz Care's plan delivers this non-negotiable benefit with international-standard reliability.",
    editorialSource: "Allianz Care International Plans Pacific Islands 2024; ExpatFinancial Oceania Healthcare Guide",
  },

  // ─── TONGA ────────────────────────────────────────────────────────────────────
  {
    id: "to-bsplife-1",
    name: "BSP Life Tonga Health Insurance",
    provider: "BSP Life Tonga",
    country: "Tonga",
    countryCode: "TO",
    logo: "/logos/bsplife.svg",
    rating: 3.7,
    reviewCount: 480,
    monthlyPremium: "TOP 60–TOP 300 / mo",
    deductible: "TOP 0",
    coverageType: "basic",
    badges: ["NRBT Licensed", "BSP Group", "Bank Distribution"],
    highlights: [
      "BSP Life Tonga is regulated by the National Reserve Bank of Tonga (NRBT)",
      "Distributed through BSP Bank Tonga's branch network",
      "Basic health and life insurance for Tongan residents",
    ],
    pros: [
      "BSP Group financial strength provides institutional backing",
      "Bank branch distribution makes policy purchase and payments convenient",
      "NRBT regulatory protection",
    ],
    cons: [
      "Serious conditions require medical evacuation to New Zealand or Fiji",
      "Very limited Nuku'alofa hospital network for inpatient care",
    ],
    affiliateUrl: "https://www.bsplife.com.to",
    description:
      "BSP Life Tonga, regulated by the National Reserve Bank of Tonga, offers basic health and life insurance distributed through BSP Bank's Tongan branch network. Medical evacuation to New Zealand is the essential supplement for conditions beyond Nuku'alofa hospital capacity.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "BSP Life Tonga leverages BSP Bank's branch infrastructure to make basic health insurance accessible across Tonga — a practical approach in a small island market where specialist distribution networks are limited.",
    editorialSource: "NRBT Tonga Licensed Insurer Directory 2024",
  },

  // ─── VANUATU ──────────────────────────────────────────────────────────────────
  {
    id: "vu-vnpf-1",
    name: "Vanuatu Life Health Insurance",
    provider: "Vanuatu National Provident Fund Health Supplement",
    country: "Vanuatu",
    countryCode: "VU",
    logo: "/logos/vnpf.svg",
    rating: 3.5,
    reviewCount: 380,
    monthlyPremium: "VUV 3,000–VUV 15,000 / mo",
    deductible: "VUV 0",
    coverageType: "basic",
    badges: ["VFSC Licensed", "Port Vila Network", "Government-Linked"],
    highlights: [
      "Vanuatu's state-linked provident fund provides supplementary health benefits",
      "Regulated by the Vanuatu Financial Services Commission (VFSC)",
      "VUV-denominated plans for Vanuatu formal sector workers",
    ],
    pros: [
      "VFSC regulatory protection",
      "VUV-denominated avoids currency conversion costs",
      "Government-linked stability",
    ],
    cons: [
      "Benefit levels very limited relative to actual medical costs",
      "Serious illness requires evacuation to New Caledonia, Fiji, or Australia",
    ],
    affiliateUrl: "https://www.vnpf.com.vu",
    description:
      "Vanuatu's national provident fund provides supplementary health benefits to formal sector workers, regulated by the VFSC. Coverage addresses basic hospitalization in Port Vila, with serious cases requiring medical evacuation to Fiji or Australia.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "VNPF's supplementary health benefit is Vanuatu's only domestically accessible health insurance mechanism for formal sector workers, providing minimal but meaningful coverage in a market that relies heavily on international evacuation plans for serious conditions.",
    editorialSource: "VFSC Vanuatu Licensed Insurer Registry 2024",
  },
  {
    id: "vu-cigna-1",
    name: "Cigna Global Vanuatu Plan",
    provider: "Cigna Global (for Vanuatu Residents)",
    country: "Vanuatu",
    countryCode: "VU",
    logo: "/logos/cigna.svg",
    rating: 4.0,
    reviewCount: 210,
    monthlyPremium: "$ 60–$ 320 / mo",
    deductible: "$ 500",
    coverageType: "standard",
    badges: ["International Evacuation", "Fiji & Australia Access", "Expat Standard"],
    highlights: [
      "International plans are the primary comprehensive coverage option in Vanuatu",
      "Medical evacuation to Fiji or Australia is the critical benefit",
      "Used by NGO workers and expatriates throughout the archipelago",
    ],
    pros: [
      "Cigna Global's Pacific plan covers evacuation to Fiji or Australia",
      "USD denomination suits Vanuatu's international business community",
      "24/7 multilingual emergency support",
    ],
    cons: [
      "USD costs inaccessible for most ni-Vanuatu residents",
      "Primarily serves expatriates and foreign workers",
    ],
    affiliateUrl: "https://www.cignaglobal.com",
    description:
      "Cigna Global provides comprehensive international health insurance for Vanuatu residents and expatriates, with medical evacuation to Fiji or Australia as the central benefit for conditions beyond Port Vila's hospital capacity.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Cigna Global's Vanuatu plan is the default choice for expatriates and NGO workers in the archipelago, providing the evacuation infrastructure that turns a potentially life-threatening medical event into a manageable one.",
    editorialSource: "Cigna Global International Health Insurance Pacific Islands Coverage 2024",
  },

  // ─── SOLOMON ISLANDS ──────────────────────────────────────────────────────────
  {
    id: "sb-anz-1",
    name: "ANZ Insurance Solomon Islands Health",
    provider: "ANZ Insurance Solomon Islands",
    country: "Solomon Islands",
    countryCode: "SB",
    logo: "/logos/anz-insurance.svg",
    rating: 3.6,
    reviewCount: 280,
    monthlyPremium: "SBD 150–SBD 800 / mo",
    deductible: "SBD 0",
    coverageType: "basic",
    badges: ["CBSI Licensed", "ANZ Group", "Honiara Network"],
    highlights: [
      "ANZ Insurance offers health plans in Solomon Islands regulated by the CBSI",
      "Distributed through ANZ Bank's Solomon Islands branch network",
      "Covers basic hospitalization at Honiara's National Referral Hospital",
    ],
    pros: [
      "ANZ Group financial backing provides stability in a small island market",
      "Bank distribution simplifies premium payment for ANZ customers",
      "CBSI regulatory oversight",
    ],
    cons: [
      "Hospital network confined to Honiara National Referral Hospital",
      "Serious illness requires evacuation to Fiji, Australia, or New Zealand",
    ],
    affiliateUrl: "https://www.anz.com/solomon-islands",
    description:
      "ANZ Insurance provides basic CBSI-regulated health plans in the Solomon Islands, distributed through ANZ Bank branches. Coverage focuses on Honiara hospital access, with medical evacuation to Fiji or Australia for conditions requiring specialist care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "ANZ Insurance is the Solomon Islands' most recognizable health insurance provider by virtue of ANZ Bank's dominant banking presence, offering accessible but basic coverage in one of the Pacific's smallest insurance markets.",
    editorialSource: "CBSI Solomon Islands Licensed Insurer Directory 2024",
  },
  {
    id: "sb-pacificprime-1",
    name: "International Health Plan Solomon Islands",
    provider: "Allianz Care (for Solomon Islands Residents)",
    country: "Solomon Islands",
    countryCode: "SB",
    logo: "/logos/allianz.svg",
    rating: 4.0,
    reviewCount: 140,
    monthlyPremium: "$ 65–$ 340 / mo",
    deductible: "$ 500",
    coverageType: "standard",
    badges: ["International Evacuation", "Fiji & Australia Access", "NGO Standard"],
    highlights: [
      "International plans are the only comprehensive coverage option in Solomon Islands",
      "Medical evacuation to Suva (Fiji) or Brisbane is the essential benefit",
      "Used by government workers, NGO staff, and expatriates",
    ],
    pros: [
      "Allianz Care global network covers treatment in Fiji and Australia",
      "Covers catastrophic medical events beyond Honiara hospital capacity",
      "Annual limits up to USD 5,000,000",
    ],
    cons: [
      "USD costs far beyond most Solomon Islander incomes",
      "Only practical for the expatriate and high-income segment",
    ],
    affiliateUrl: "https://www.allianzcare.com",
    description:
      "International health plans from Allianz Care are the only comprehensive health insurance option in the Solomon Islands for residents facing serious medical conditions. Medical evacuation to Fiji or Brisbane is the defining benefit, with annual limits up to USD 5 million.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "In the Solomon Islands, the most important question is not which insurer to choose but whether the policy covers medical evacuation to Fiji or Australia — Allianz Care's plan delivers this critical benefit at the standard the market demands.",
    editorialSource: "Allianz Care International Health Plans Pacific Islands 2024; InternationalInsurance.com Oceania Health Insurance",
  },
];
