import { InsurancePlan } from "./types";

export const plansMiddleEast: InsurancePlan[] = [
  // ─── SAUDI ARABIA ────────────────────────────────────────────────────────────
  {
    id: "sa-bupaarabia-1",
    name: "Bupa Arabia Family Health Plan",
    provider: "Bupa Arabia",
    country: "Saudi Arabia",
    countryCode: "SA",
    logo: "/logos/bupaarabia.svg",
    rating: 4.4,
    reviewCount: 28600,
    monthlyPremium: "SAR 400–SAR 2,500 / mo",
    deductible: "SAR 0",
    coverageType: "comprehensive",
    badges: ["46% Market Share", "SAR 1M Max Benefit", "Vision 2030 Partner"],
    highlights: [
      "Market leader with 46% share of Saudi Arabia's health insurance market as of 2023",
      "SAR 42 billion total market projected to reach SAR 83 billion by 2030",
      "Most plans carry SAR 500,000 annual benefit; premium plans up to SAR 1 million",
    ],
    pros: [
      "Unrivalled hospital network across all Saudi regions",
      "20% year-on-year GWP growth in FY2023",
      "Aligned with Vision 2030 healthcare expansion initiatives",
    ],
    cons: [
      "Dominance means less competitive pressure to innovate on pricing",
      "Customer service wait times can be long during peak periods",
    ],
    affiliateUrl: "https://www.bupa.com.sa/en/personal/bupafamily",
    description:
      "Bupa Arabia is Saudi Arabia's largest health insurer with a commanding 46% market share. Family health plans offer differentiated services from premium coverage with a SAR 1 million annual limit down to affordable wide-access plans, all compliant with CCHI regulations.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa Arabia's near-half market share is not just a statistic — it reflects the breadth of hospital contracts and digital tools that make it the default health insurer for Saudi residents across income levels.",
    editorialSource: "Bupa Arabia Saudi Insurance Sector Review 2024; Argaam Bupa Arabia GWP Data 2023",
  },
  {
    id: "sa-tawuniya-1",
    name: "Tawuniya My Family Insurance",
    provider: "Tawuniya Insurance",
    country: "Saudi Arabia",
    countryCode: "SA",
    logo: "/logos/tawuniya.svg",
    rating: 4.2,
    reviewCount: 19400,
    monthlyPremium: "SAR 350–SAR 2,000 / mo",
    deductible: "SAR 0",
    coverageType: "standard",
    badges: ["S&P A- Rated", "SAR 1.16bn 2024 Earnings", "Digital Transformation"],
    highlights: [
      "S&P upgraded Tawuniya to A- with Stable outlook in 2025",
      "2024 earnings reached SAR 1.16 billion — strong financial performance",
      "February 2025: won Saudi Arabian Airlines health insurance contract",
    ],
    pros: [
      "S&P A- credit rating confirms strong financial standing",
      "Government partnerships provide large institutional client base",
      "Active digital transformation improving customer experience",
    ],
    cons: [
      "Second-tier behind Bupa Arabia in hospital network breadth",
      "Premium pricing comparable to Bupa for similar plan tiers",
    ],
    affiliateUrl: "https://www.tawuniya.com/en/individuals/products/health/my-family-insurance",
    description:
      "Tawuniya is one of Saudi Arabia's leading health insurers, holding an S&P A- credit rating. Its 2024 earnings of SAR 1.16 billion and major government contracts — including Saudi Airlines — reflect its strong institutional standing alongside individual and family health plans.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Tawuniya's S&P upgrade and SAR 1.16 billion earnings confirm it as the most financially robust alternative to Bupa Arabia in the Saudi market.",
    editorialSource: "ME Insurance Review S&P Tawuniya Upgrade 2025; GlobeNewswire Saudi Arabia Health Insurance 2025",
  },
  {
    id: "sa-medgulf-1",
    name: "MedGulf Health Insurance",
    provider: "Mediterranean and Gulf Insurance (MedGulf)",
    country: "Saudi Arabia",
    countryCode: "SA",
    logo: "/logos/medgulf.svg",
    rating: 4.0,
    reviewCount: 12800,
    monthlyPremium: "SAR 300–SAR 1,800 / mo",
    deductible: "SAR 0",
    coverageType: "standard",
    badges: ["SAR 3.55bn Revenue 2024", "SEC Contract Win", "Best Innovative Partnership 2024"],
    highlights: [
      "MedGulf revenues reached SAR 3.55 billion in 2024",
      "January 2025: won SAR ~800M health insurance deal with Saudi Electricity Company",
      "Received 'Best Innovative Health Insurance Partnership — Saudi Arabia 2024'",
    ],
    pros: [
      "Top-five market position with large government and corporate client base",
      "Award-winning innovation in health insurance partnerships",
      "Group SME 'Riadi' plan specifically targets small businesses",
    ],
    cons: [
      "Less prominent in individual retail market compared to Bupa Arabia",
      "Customer reviews indicate variable service quality",
    ],
    affiliateUrl: "https://www.medgulf.com.sa/home",
    description:
      "MedGulf is one of Saudi Arabia's top-five health insurers with SAR 3.55 billion in 2024 revenue. It serves both corporate and individual segments, with a dedicated Riadi SME plan and a major 2025 contract win with Saudi Electricity Company.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "MedGulf's corporate insurance muscle — demonstrated by the Saudi Electricity Company contract — is matched by a growing suite of SME and individual plans that make it a versatile competitor in Saudi health coverage.",
    editorialSource: "International Finance MedGulf Saudi Standards 2024; Argaam MedGulf SEC Contract January 2025",
  },
  {
    id: "sa-malath-1",
    name: "Malath Health Insurance",
    provider: "Malath Cooperative Insurance",
    country: "Saudi Arabia",
    countryCode: "SA",
    logo: "/logos/malath.svg",
    rating: 3.5,
    reviewCount: 6200,
    monthlyPremium: "SAR 250–SAR 1,200 / mo",
    deductible: "SAR 0",
    coverageType: "basic",
    badges: ["SAR 500M Capital", "CCHI Licensed", "Group Health Focus"],
    highlights: [
      "Malath Cooperative Insurance has SAR 500 million share capital",
      "Provides group and individual health plans accredited by CCHI",
      "Listed on Saudi Exchange (Tadawul)",
    ],
    pros: [
      "Strong capital base at SAR 500 million",
      "CCHI-licensed for full regulatory compliance",
      "Listed Tadawul company with public transparency obligations",
    ],
    cons: [
      "Posted net loss of approximately SAR 15 million in 2024",
      "Customer complaints about app access and clinic network information",
    ],
    affiliateUrl: "https://www.malath.com.sa/en",
    description:
      "Malath Cooperative Insurance offers CCHI-accredited individual and group health plans in Saudi Arabia. With SAR 500 million in share capital and a Tadawul listing, it maintains regulatory transparency but has faced financial headwinds in recent years.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Malath offers a budget-accessible entry point to Saudi Arabia's CCHI-regulated health insurance market, though recent financial results signal the need for operational improvements.",
    editorialSource: "Saudipedia Malath Cooperative Insurance Profile; Eye of Riyadh Malath Directory",
  },
  {
    id: "sa-gig-1",
    name: "GIG Gulf Health Insurance Saudi Arabia",
    provider: "Gulf Insurance Group (GIG) Saudi Arabia",
    country: "Saudi Arabia",
    countryCode: "SA",
    logo: "/logos/gig.svg",
    rating: 4.0,
    reviewCount: 9300,
    monthlyPremium: "SAR 300–SAR 1,600 / mo",
    deductible: "SAR 0",
    coverageType: "standard",
    badges: ["Former AXA Cooperative", "GIG Group", "CCHI Compliant"],
    highlights: [
      "GIG Gulf acquired AXA Cooperative Insurance's Saudi operations in 2020",
      "AXA Global Healthcare plans previously received Protection Review 8/10 rating",
      "CCHI-compliant plans for individuals and corporate groups",
    ],
    pros: [
      "Gulf Insurance Group's regional financial strength behind Saudi operations",
      "AXA heritage provides established hospital network and claims infrastructure",
      "Comprehensive international health options available",
    ],
    cons: [
      "Brand transition from AXA to GIG may cause customer confusion",
      "Less dominant in Saudi market than Bupa Arabia or Tawuniya",
    ],
    affiliateUrl: "https://www.giggulf.sa",
    description:
      "GIG Gulf operates in Saudi Arabia following its acquisition of AXA Cooperative Insurance's operations in 2020. CCHI-compliant health plans serve individuals and groups with the benefit of AXA's established hospital network and GIG Gulf's broader regional financial strength.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "GIG Gulf inherits AXA's Saudi infrastructure, giving the group an immediate competitive position in one of the region's fastest-growing health insurance markets.",
    editorialSource: "Protection Review AXA Global Healthcare Saudi Arabia 8/10; AXA Cooperative Crunchbase Profile",
  },

  // ─── ISRAEL ───────────────────────────────────────────────────────────────────
  {
    id: "il-maccabi-1",
    name: "Maccabi Healthcare Services",
    provider: "Maccabi Healthcare Services (Kupat Holim Maccabi)",
    country: "Israel",
    countryCode: "IL",
    logo: "/logos/maccabi.svg",
    rating: 4.3,
    reviewCount: 41500,
    monthlyPremium: "NIS 150–NIS 450 / mo (Maccabi Gold supplement)",
    deductible: "NIS 0",
    coverageType: "comprehensive",
    badges: ["2.6M Members", "Founded 1941", "Free Choice HMO"],
    highlights: [
      "Second-largest of Israel's four state-mandated HMOs with 2.6 million members",
      "Membership fees legally determined by National Insurance Institute",
      "Silver Shield (Maccabi Gold) supplemental plans provide enhanced coverage",
    ],
    pros: [
      "Free choice of family physicians and specialists is a core principle",
      "Clinics in every municipality from Metulla to Eilat",
      "Emphasis on preventive health and holistic medicine",
    ],
    cons: [
      "Membership fees set by law — no ability to price-shop between HMOs",
      "Wait times for narrow specialists longer than smaller HMOs",
    ],
    affiliateUrl: "https://www.maccabi4u.co.il/en/46562/main_english",
    description:
      "Maccabi Healthcare Services is one of Israel's four legally mandated HMOs, founded in 1941 and serving 2.6 million members. Core HMO membership is legally determined, with optional Maccabi Gold/Silver Shield supplements providing access to enhanced specialist and elective care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Maccabi's principle of free physician choice and its emphasis on preventive healthcare make it the preferred HMO for Israelis who value clinical autonomy and holistic health management.",
    editorialSource: "Maccabi Healthcare Services Wikipedia; Israel Healthcare System Guide — Belong.co.il",
  },
  {
    id: "il-clalit-1",
    name: "Clalit Health Services",
    provider: "Clalit Health Services",
    country: "Israel",
    countryCode: "IL",
    logo: "/logos/clalit.svg",
    rating: 4.1,
    reviewCount: 68000,
    monthlyPremium: "NIS 150–NIS 400 / mo (Clalit Mushlam supplement)",
    deductible: "NIS 0",
    coverageType: "standard",
    badges: ["Largest HMO Israel", "5M Members", "Nationwide Clinics"],
    highlights: [
      "Clalit is Israel's largest HMO with nearly 5 million members — over half of all Israelis",
      "Extensive clinic network available in almost every municipality",
      "Clalit Mushlam supplemental insurance adds specialist and elective coverage",
    ],
    pros: [
      "Largest hospital and clinic network of all four Israeli HMOs",
      "Represents slightly over 50% of Israeli insured population",
      "Data science capabilities praised for proactive patient care innovation",
    ],
    cons: [
      "Longest wait times for narrow specialists due to scale",
      "Bureaucratic experience can be more complex than smaller HMOs",
    ],
    affiliateUrl: "https://www.clalit.co.il",
    description:
      "Clalit Health Services is Israel's largest state-mandated HMO, covering nearly 5 million members and representing over half of all Israelis. Its unmatched clinic footprint is complemented by Clalit Mushlam supplemental insurance for enhanced specialist and elective access.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Clalit's unmatched network coverage makes it the most geographically accessible HMO in Israel, while its data science investments are setting new standards for proactive preventive care.",
    editorialSource: "Clalit Health Services Wikipedia; Israel Healthcare Guide — NativeIsrael.com",
  },
  {
    id: "il-meuhedet-1",
    name: "Meuhedet Health Services",
    provider: "Meuhedet Health Maintenance Organization",
    country: "Israel",
    countryCode: "IL",
    logo: "/logos/meuhedet.svg",
    rating: 4.4,
    reviewCount: 22100,
    monthlyPremium: "NIS 150–NIS 420 / mo (Meuhedet Adif supplement)",
    deductible: "NIS 0",
    coverageType: "standard",
    badges: ["1M+ Members", "Short Wait Times", "High Quality Clinics"],
    highlights: [
      "Third-largest Israeli HMO with over 1 million members",
      "Praised for high quality services and minimal queuing",
      "Meuhedet Adif supplemental plan enhances specialist access",
    ],
    pros: [
      "Highest service quality ratings among Israel's four HMOs",
      "Virtually no queues according to member and expert reviews",
      "Supplemental Adif plan provides broad private specialist access",
    ],
    cons: [
      "Clinic locations mostly in large cities — less rural coverage",
      "Smaller network than Clalit limits very rural accessibility",
    ],
    affiliateUrl: "https://www.meuhedet.co.il",
    description:
      "Meuhedet is Israel's third-largest HMO with over 1 million members. It stands out for high clinical quality and minimal wait times compared to larger competitors, with the Meuhedet Adif supplemental plan providing broader access to private specialists.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Meuhedet consistently earns the highest service quality scores among Israel's four HMOs — a remarkable achievement that reflects its focused, community-oriented healthcare philosophy.",
    editorialSource: "Israel Healthcare System Guide — EasyAliyah.com 2025; Belong.co.il HMO Comparison",
  },
  {
    id: "il-leumit-1",
    name: "Leumit Health Services",
    provider: "Leumit Health Services",
    country: "Israel",
    countryCode: "IL",
    logo: "/logos/leumit.svg",
    rating: 4.3,
    reviewCount: 17800,
    monthlyPremium: "NIS 150–NIS 410 / mo (Leumit Gold supplement)",
    deductible: "NIS 0",
    coverageType: "standard",
    badges: ["~900K Members", "Minimal Wait Times", "Children's Specialists"],
    highlights: [
      "Israel's smallest HMO with approximately 900,000 members",
      "Notable for minimal wait times and abundant children's specialists",
      "Option to see a second physician without additional appointments",
    ],
    pros: [
      "Minimal to no wait times across most specialist categories",
      "Excellent children's and pediatric specialist access",
      "Second-opinion consultation available without bureaucratic barriers",
    ],
    cons: [
      "Smallest network of the four HMOs — less rural hospital coverage",
      "Some specialized services may require referral to Clalit or Maccabi facilities",
    ],
    affiliateUrl: "https://www.leumit.co.il",
    description:
      "Leumit is Israel's smallest of the four mandatory HMOs, serving approximately 900,000 members. It is highly regarded for minimal wait times, strong pediatric specialist access, and a streamlined second-opinion process, with Leumit Gold supplemental insurance expanding private specialist coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Leumit's minimal wait times and exceptional pediatric specialist access make it the preferred HMO for Israeli families with young children who value speed and quality over network scale.",
    editorialSource: "Kupat Holim Israel Guide — Welcome-Israel.com; EasyLandingIL Israel Healthcare System",
  },

  // ─── TURKEY ───────────────────────────────────────────────────────────────────
  {
    id: "tr-bupaacıbadem-1",
    name: "Bupa Acıbadem Health Insurance",
    provider: "Bupa Acıbadem Sigorta",
    country: "Turkey",
    countryCode: "TR",
    logo: "/logos/bupaacıbadem.svg",
    rating: 4.3,
    reviewCount: 14200,
    monthlyPremium: "TRY 1,100–TRY 8,000 / mo",
    deductible: "TRY 0",
    coverageType: "comprehensive",
    badges: ["Turkey's 2nd Largest Health Insurer", "600K Members", "7,500+ Institutions"],
    highlights: [
      "Bupa acquired Acıbadem Sigorta in January 2019 — Turkey's second-largest health insurer",
      "600,000 insured policyholders with access to 7,500+ healthcare institutions",
      "Partners with Acıbadem hospital group, Turkey's highest-quality private network",
    ],
    pros: [
      "Access to Acıbadem hospitals, widely regarded as Turkey's best private hospitals",
      "Flexible plan design: from outpatient-only to full comprehensive packages",
      "International Bupa brand standards applied to Turkish market",
    ],
    cons: [
      "Premium tier plans are among Turkey's most expensive",
      "Turkish lira inflation makes TRY-denominated premiums volatile in real terms",
    ],
    affiliateUrl: "https://www.bupaacibadem.com.tr/en",
    description:
      "Bupa Acıbadem Sigorta is Turkey's second-largest health insurer, serving 600,000 policyholders through a network of 7,500+ healthcare institutions. As Bupa's Turkish arm, it applies international standards while offering flexible plan construction from outpatient-only to full comprehensive cover.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Bupa Acıbadem combines Bupa's global reputation for claims reliability with Acıbadem's unparalleled Turkish private hospital network, making it the premium choice for Turkey residents who demand quality.",
    editorialSource: "Bupa Acıbadem Sigorta Official Website; Deal-TR Best Health Insurance Turkey 2025",
  },
  {
    id: "tr-allianz-1",
    name: "Allianz Turkey Health Insurance",
    provider: "Allianz Sigorta Turkey",
    country: "Turkey",
    countryCode: "TR",
    logo: "/logos/allianz.svg",
    rating: 4.1,
    reviewCount: 11600,
    monthlyPremium: "TRY 1,500–TRY 8,000 / mo",
    deductible: "TRY 0",
    coverageType: "standard",
    badges: ["20+ Years in Turkey", "SGK Integration", "Multilingual Support"],
    highlights: [
      "Allianz has operated in Turkey for over 20 years",
      "Plans integrate with Turkey's state SGK system for complementary coverage",
      "Multilingual support including English for expatriates",
    ],
    pros: [
      "Balanced value between service quality and pricing",
      "SGK integration reduces total out-of-pocket costs for Turkish citizens",
      "Multilingual claims assistance valued by expatriate policyholders",
    ],
    cons: [
      "Premium tier plans cost TRY 1,500–8,000 annually",
      "Network breadth not as extensive as Bupa Acıbadem's",
    ],
    affiliateUrl: "https://www.allianz.com.tr/en_GB/products/health-insurance.html",
    description:
      "Allianz Turkey has operated for over 20 years and offers health insurance plans that complement Turkey's state SGK system. Multilingual support and a reputation for balanced pricing versus service quality make it popular among both Turkish nationals and expatriates.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Allianz Turkey's two-decade market presence and SGK complementary positioning make it the most credible mid-market alternative to Bupa Acıbadem for Turkish residents.",
    editorialSource: "Allianz Turkey Official Health Insurance Page; Deal-TR Best Health Insurance Turkey 2025",
  },
  {
    id: "tr-axa-1",
    name: "AXA Sigorta Turkey Health Plan",
    provider: "AXA Sigorta Turkey",
    country: "Turkey",
    countryCode: "TR",
    logo: "/logos/axa.svg",
    rating: 4.0,
    reviewCount: 9800,
    monthlyPremium: "TRY 1,000–TRY 3,000 / mo",
    deductible: "TRY 0",
    coverageType: "basic",
    badges: ["Budget-Friendly", "Residence Permit Compliant", "Student Plans"],
    highlights: [
      "AXA is one of Turkey's most trusted insurance providers",
      "Plans starting from TRY 1,000/year recognized by Turkish immigration authorities",
      "Best for budget-conscious expatriates and students",
    ],
    pros: [
      "Lowest cost plans meeting Turkish residence permit requirements",
      "AXA Sigorta named Company of the Year — Insurance at Stevie Awards",
      "Wide range from minimal to comprehensive cover",
    ],
    cons: [
      "Entry plans offer only basic medical services",
      "Comprehensive tier pricing climbs to TRY 3,000+/mo",
    ],
    affiliateUrl: "https://www.axa.com.tr",
    description:
      "AXA Sigorta Turkey is recognized as one of Turkey's most trusted insurers. Its health plans start from TRY 1,000 annually at the entry tier, are accepted by Turkish immigration authorities for residence permits, and scale to more comprehensive tiers for broader hospital access.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA Sigorta Turkey's immigration-compliant entry plans at TRY 1,000/year are the most cost-effective residence permit health insurance option for students and new expatriates in Turkey.",
    editorialSource: "AXA Sigorta Stevie Awards Company of the Year; TRResident Turkey Insurance Prices Foreigners",
  },
  {
    id: "tr-anadolu-1",
    name: "Anadolu Sigorta Health Insurance",
    provider: "Anadolu Sigorta",
    country: "Turkey",
    countryCode: "TR",
    logo: "/logos/anadolusigorta.svg",
    rating: 3.9,
    reviewCount: 8400,
    monthlyPremium: "TRY 900–TRY 4,000 / mo",
    deductible: "TRY 0",
    coverageType: "basic",
    badges: ["Est. 1925", "Cheapest for Young Adults", "Residence Permit Compliant"],
    highlights: [
      "Anadolu Sigorta established 1925 — one of Turkey's oldest insurers",
      "Plans start from TRY 900/year for young adults aged 18–25",
      "Immigration-compliant plans fulfill residence permit health requirements",
    ],
    pros: [
      "Lowest-cost plans available for young adults in Turkey",
      "Century-old operating history shows institutional resilience",
      "Both inpatient and outpatient included at mid-tier plans",
    ],
    cons: [
      "Entry-level plans cover only basic medical services",
      "Hospital network smaller than Bupa Acıbadem and Allianz",
    ],
    affiliateUrl: "https://www.anadolusigorta.com.tr/en/health",
    description:
      "Anadolu Sigorta, founded in 1925, is one of Turkey's oldest and largest insurers. Health plans start from TRY 900/year for young adults (18–25) and are compliant with Turkish immigration authorities' residence permit requirements, with all inpatient and outpatient accident and illness costs covered.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Anadolu Sigorta's century-long track record and lowest-market entry premiums for young adults make it the go-to choice for budget-constrained newcomers navigating Turkey's residence permit health insurance requirement.",
    editorialSource: "Anadolu Sigorta Official Company Profile; Deal-TR Best Health Insurance Turkey 2025",
  },
  {
    id: "tr-mapfre-1",
    name: "MAPFRE Sigorta Health Insurance",
    provider: "MAPFRE Sigorta Turkey",
    country: "Turkey",
    countryCode: "TR",
    logo: "/logos/mapfre.svg",
    rating: 4.0,
    reviewCount: 7200,
    monthlyPremium: "TRY 1,200–TRY 5,000 / mo",
    deductible: "TRY 0",
    coverageType: "standard",
    badges: ["SGK Complementary", "Fark Yok Plan", "Major Market Player"],
    highlights: [
      "MAPFRE Sigorta is among Turkey's key health insurance market players",
      "Fark Yok plan allows SGK-insured members to use contracted private hospitals without co-pay",
      "Over 60% of Turkey's health insurance market represented by top-tier players including MAPFRE",
    ],
    pros: [
      "Fark Yok plan eliminates co-payment at contracted institutions for SGK holders",
      "Spanish MAPFRE Group financial backing",
      "Competitive pricing for complementary SGK top-up plans",
    ],
    cons: [
      "Best value specifically for Turkish citizens with existing SGK coverage",
      "International plans less competitive than Bupa Acıbadem tier",
    ],
    affiliateUrl: "https://www.mapfre.com.tr/insurance-en/individual/",
    description:
      "MAPFRE Sigorta Turkey offers health insurance with a signature Fark Yok complementary plan allowing SGK-insured individuals to access contracted private hospital services without any co-payment. The Spanish MAPFRE Group's financial strength underpins Turkish operations.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "MAPFRE's Fark Yok plan is arguably the most practical product innovation in Turkey's health insurance market, eliminating the co-payment burden that discourages SGK members from using private hospitals.",
    editorialSource: "MAPFRE Sigorta Turkey Official Fark Yok Product Page; Deal-TR Turkey Insurance Comparison 2025",
  },

  // ─── QATAR ────────────────────────────────────────────────────────────────────
  {
    id: "qa-qlm-1",
    name: "QLM Individual & Family Health Plan",
    provider: "QLM Life and Medical Insurance",
    country: "Qatar",
    countryCode: "QA",
    logo: "/logos/qlm.svg",
    rating: 4.2,
    reviewCount: 7400,
    monthlyPremium: "QAR 500–QAR 2,500 / mo",
    deductible: "QAR 0",
    coverageType: "standard",
    badges: ["QFC Listed", "Leading Qatar Health Insurer", "QFCA Licensed"],
    highlights: [
      "QLM is one of Qatar's leading dedicated health insurers",
      "Listed on Qatar Financial Centre (QFC) with regulated operations",
      "Plans cover individuals, families, and visitors to Qatar",
    ],
    pros: [
      "Specialist health insurer with deep Qatar market knowledge",
      "QFCA-regulated for strong policyholder protection",
      "Reliable claims processing at Qatar's major private hospitals",
    ],
    cons: [
      "Premium pricing reflects Qatar's high private healthcare costs",
      "Less international coverage than global plans",
    ],
    affiliateUrl: "https://qlm.com.qa",
    description:
      "QLM Life and Medical Insurance is one of Qatar's leading specialist health insurers, listed on the Qatar Financial Centre. It offers individual, family, and visitor health plans covering Qatar's major private hospitals, with premiums ranging from QAR 100/month for basic visitor plans to QAR 2,500+/month for premium family plans.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "QLM's specialist focus on Qatar's health market gives it a depth of local hospital network knowledge and claims reliability that generalist regional insurers struggle to match.",
    editorialSource: "QLM Life and Medical Insurance Official Website; Kuwait Qatar Living Daman Review",
  },
  {
    id: "qa-daman-1",
    name: "Daman Health Insurance Qatar",
    provider: "Daman Health Insurance Qatar LLC",
    country: "Qatar",
    countryCode: "QA",
    logo: "/logos/daman.svg",
    rating: 4.0,
    reviewCount: 5200,
    monthlyPremium: "QAR 400–QAR 2,000 / mo",
    deductible: "QAR 0",
    coverageType: "standard",
    badges: ["QFC Registered", "SME & Corporate", "Reliable Claims"],
    highlights: [
      "Daman Health Insurance Qatar — Qatar's only specialist health insurer in QFC",
      "Established July 2011, focused on SME and corporate group health",
      "Direct billing network at Qatar's major private hospitals",
    ],
    pros: [
      "Specialist health insurance focus — not a generalist insurer",
      "Reliable claims processing recognized by corporate clients",
      "QFC registration provides strong regulatory oversight",
    ],
    cons: [
      "Primary focus on corporate and SME rather than individual retail",
      "Individual plan availability limited compared to QLM",
    ],
    affiliateUrl: "https://www.daman.qa",
    description:
      "Daman Health Insurance Qatar is registered in the Qatar Financial Centre and established in 2011 as Qatar's specialist health insurer. Its primary market is SME and corporate group health insurance, with direct billing available at Qatar's major private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Daman Qatar's corporate health insurance credentials are strong — a reliable claims partner for businesses that need consistent and efficient medical benefit administration in Doha.",
    editorialSource: "Qatar Living Daman Health Insurance Review; KuluQatar Health Insurance in Qatar Guide",
  },
  {
    id: "qa-giggulf-1",
    name: "GIG Gulf Qatar Health Insurance",
    provider: "GIG Gulf Qatar",
    country: "Qatar",
    countryCode: "QA",
    logo: "/logos/gig.svg",
    rating: 4.1,
    reviewCount: 4100,
    monthlyPremium: "QAR 450–QAR 2,200 / mo",
    deductible: "QAR 0",
    coverageType: "standard",
    badges: ["AM Best A", "Regional GCC Leader", "Family Plans"],
    highlights: [
      "GIG Gulf is a leading GCC insurer with AM Best A financial strength",
      "Qatar operations offer tailored family health insurance plans",
      "Access to GIG's broad regional hospital network",
    ],
    pros: [
      "AM Best A rating confirms strong financial stability",
      "Regional GCC network useful for Qatari nationals traveling within the GCC",
      "Competitive family plan pricing",
    ],
    cons: [
      "Not a Qatar specialist — broader regional approach",
      "Less local hospital depth than QLM or Daman Qatar",
    ],
    affiliateUrl: "https://www.giggulf.qa",
    description:
      "GIG Gulf's Qatar operations offer family and individual health insurance plans backed by the group's AM Best A financial strength rating. Its regional GCC network is a useful feature for Qatar residents who frequently travel within the Gulf.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "GIG Gulf Qatar brings the group's regional financial strength and GCC-wide hospital network to Qatar's competitive health insurance market, making it a credible option for families with GCC travel patterns.",
    editorialSource: "Gulf Insurance Group About Us; AM Best GIG Upgrade 2025",
  },

  // ─── KUWAIT ───────────────────────────────────────────────────────────────────
  {
    id: "kw-gig-1",
    name: "GIG Kuwait Health Insurance",
    provider: "Gulf Insurance Group (GIG) Kuwait",
    country: "Kuwait",
    countryCode: "KW",
    logo: "/logos/gig.svg",
    rating: 4.3,
    reviewCount: 12800,
    monthlyPremium: "KWD 15–KWD 80 / mo",
    deductible: "KWD 0",
    coverageType: "comprehensive",
    badges: ["Kuwait Market Leader", "54K+ Customers", "AM Best A"],
    highlights: [
      "GIG Kuwait is Kuwait's largest insurance company by written premiums",
      "AM Best upgraded to A+ (Excellent) Long-Term Issuer Credit Rating",
      "200+ health service providers in network; 1,000+ users on instant approval system",
    ],
    pros: [
      "Dominant market leader with exceptional financial strength ratings",
      "Instant online health claims approval for over 1,000 active users",
      "GIG Rewards program provides premium discounts and gift vouchers",
    ],
    cons: [
      "Mandatory expatriate health insurance regulation since 2023 means less differentiation",
      "Family bundle pricing can be high for large expatriate families",
    ],
    affiliateUrl: "https://www.gig.com.kw/en",
    description:
      "Gulf Insurance Group Kuwait is Kuwait's largest insurer by written premiums, holding AM Best A+ (Excellent) issuer credit ratings. Its health insurance covers 54,000+ customers through 200+ partner health providers, with an instant online claims approval system and a rewards program.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "GIG Kuwait's combination of AM Best A+ financial strength and Kuwait's largest hospital network makes it the clear market leader — a status backed by over six decades of continuous operations.",
    editorialSource: "GIG Kuwait Official Website; AM Best GIG Upgrade; Arab MLS GIG Kuwait Profile",
  },
  {
    id: "kw-ahleia-1",
    name: "Al Ahleia Insurance Health Plan",
    provider: "Al Ahleia Insurance Company Kuwait",
    country: "Kuwait",
    countryCode: "KW",
    logo: "/logos/alahleia.svg",
    rating: 3.9,
    reviewCount: 6100,
    monthlyPremium: "KWD 12–KWD 60 / mo",
    deductible: "KWD 0",
    coverageType: "standard",
    badges: ["Boursa Kuwait Listed", "CIMA Licensed", "Individual & Group"],
    highlights: [
      "Al Ahleia Insurance is a Boursa Kuwait-listed domestic insurer",
      "Regulated by Kuwait's Central Insurance Monitoring Authority (CIMA)",
      "Individual and group health plans across Kuwait",
    ],
    pros: [
      "Domestic insurer with deep Kuwait market relationships",
      "Boursa Kuwait listing provides transparency and regulatory oversight",
      "Competitive pricing relative to GIG on standard health tiers",
    ],
    cons: [
      "Network smaller than GIG Kuwait's 200+ provider network",
      "Less international treatment access than regional competitors",
    ],
    affiliateUrl: "https://www.alahleia.com.kw",
    description:
      "Al Ahleia Insurance Company is a Boursa Kuwait-listed domestic insurer regulated by CIMA. It offers individual and group health insurance plans at competitive pricing, serving Kuwait's expatriate and national population with a domestic-focused hospital network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Al Ahleia's Boursa Kuwait listing and domestic market expertise make it a credible alternative to GIG for Kuwait residents seeking competitive pricing from an established local insurer.",
    editorialSource: "Pacific Prime Kuwait Top Insurance Companies; CIMA Kuwait Licensed Insurer List 2024",
  },
  {
    id: "kw-warba-1",
    name: "Warba Insurance Health Plan",
    provider: "Warba Insurance Company Kuwait",
    country: "Kuwait",
    countryCode: "KW",
    logo: "/logos/warba.svg",
    rating: 3.8,
    reviewCount: 4200,
    monthlyPremium: "KWD 10–KWD 55 / mo",
    deductible: "KWD 0",
    coverageType: "basic",
    badges: ["CIMA Licensed", "Individual Plans", "Affordable Kuwait"],
    highlights: [
      "Warba Insurance is an established Kuwait domestic insurer",
      "CIMA-regulated individual and group health plans",
      "One of Kuwait's more affordable health insurance options",
    ],
    pros: [
      "Lower entry-level premiums than GIG or Al Ahleia",
      "CIMA regulatory protection for policyholders",
      "Direct billing at select Kuwait hospitals",
    ],
    cons: [
      "Smaller hospital network limits coverage breadth",
      "Limited digital claims infrastructure",
    ],
    affiliateUrl: "https://www.warbainsurance.com.kw",
    description:
      "Warba Insurance Company is a CIMA-regulated Kuwait insurer offering affordable individual and group health plans. Its entry-level pricing is competitive, making it accessible for Kuwait's large expatriate working population seeking basic mandatory health coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Warba Insurance provides Kuwait's most price-sensitive segment with an affordable, CIMA-regulated health coverage option that meets mandatory insurance requirements for resident expatriates.",
    editorialSource: "Pacific Prime Kuwait International Health Insurance Guide 2024",
  },

  // ─── BAHRAIN ──────────────────────────────────────────────────────────────────
  {
    id: "bh-giggulf-1",
    name: "GIG Gulf Bahrain Health Insurance",
    provider: "GIG Gulf Bahrain",
    country: "Bahrain",
    countryCode: "BH",
    logo: "/logos/gig.svg",
    rating: 4.3,
    reviewCount: 7800,
    monthlyPremium: "BHD 25–BHD 150 / mo",
    deductible: "BHD 0",
    coverageType: "comprehensive",
    badges: ["4.3/5 Customer Satisfaction", "SEHATI Compliant", "Global Hospital Network"],
    highlights: [
      "GIG Gulf rated 4.3/5 for customer satisfaction in Bahrain",
      "SEHATI-compliant plans for expatriate mandatory health coverage",
      "Access to hospitals, clinics, pharmacies, dentists, and radiology centers",
    ],
    pros: [
      "Highest customer satisfaction rating among Bahrain's private insurers",
      "SEHATI compliance ensures full regulatory adherence",
      "Comprehensive network including dental, radiology, and pharmacy access",
    ],
    cons: [
      "SEHATI mandatory plans cover only emergency and primary care for expatriates",
      "Premium plans required for full specialist and elective coverage",
    ],
    affiliateUrl: "https://www.giggulf.bh/en/personal/products/health-insurance",
    description:
      "GIG Gulf Bahrain holds a 4.3/5 customer satisfaction rating and offers SEHATI-compliant health insurance plans for Bahrain residents. Coverage spans hospitals, clinics, pharmacies, dental, and radiology centers, with both mandatory and enhanced plan tiers available.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "GIG Gulf Bahrain's 4.3/5 satisfaction score is the highest among the country's major health insurers, reflecting both the quality of its hospital network and the efficiency of its claims team.",
    editorialSource: "GIG Gulf Bahrain Health Insurance Official Page; GIG Gulf SEHATI Blog",
  },
  {
    id: "bh-solidarity-1",
    name: "Solidarity Bahrain Medical Insurance",
    provider: "Solidarity Bahrain BSC",
    country: "Bahrain",
    countryCode: "BH",
    logo: "/logos/solidarity.svg",
    rating: 4.0,
    reviewCount: 5400,
    monthlyPremium: "BHD 20–BHD 120 / mo",
    deductible: "BHD 0",
    coverageType: "standard",
    badges: ["CBB Licensed", "Competitive Pricing", "Group & Individual"],
    highlights: [
      "Solidarity Bahrain is an established licensed insurer under the Central Bank of Bahrain",
      "Medical plans designed for both individuals and corporate groups",
      "Competitive premium pricing while maintaining comprehensive coverage",
    ],
    pros: [
      "CBB-regulated for strong policyholder protection",
      "Competitive premium levels relative to GIG Gulf",
      "Both individual and group plans available",
    ],
    cons: [
      "Hospital network somewhat smaller than GIG Gulf",
      "Less digital infrastructure than regional market leaders",
    ],
    affiliateUrl: "https://www.solidarity.com.bh/product/medical",
    description:
      "Solidarity Bahrain is a CBB-licensed insurer offering medical plans for individuals and corporate groups at competitive prices. Plans are designed to provide comprehensive coverage while keeping premiums as affordable as possible in Bahrain's regulated market.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Solidarity Bahrain's commitment to competitive pricing within full CBB regulatory compliance makes it a credible and accessible alternative to GIG Gulf for Bahrain's growing expatriate population.",
    editorialSource: "Solidarity Bahrain Medical Insurance Official Page; edarabia.com Bahrain Insurance Ratings 2025",
  },
  {
    id: "bh-health360-1",
    name: "Health 360 Bahrain",
    provider: "Health 360",
    country: "Bahrain",
    countryCode: "BH",
    logo: "/logos/health360.svg",
    rating: 3.9,
    reviewCount: 2800,
    monthlyPremium: "BHD 18–BHD 100 / mo",
    deductible: "BHD 0",
    coverageType: "basic",
    badges: ["CBB Licensed", "Bahrain Specialist", "Digital Portal"],
    highlights: [
      "Health 360 is a Bahrain-specific health insurance specialist",
      "Digital portal for policy management and claims",
      "Focus on affordable individual and family health plans",
    ],
    pros: [
      "Bahrain-specialist insurer with local market knowledge",
      "Digital claims portal improves administrative experience",
      "Lower entry-level premiums than GIG and Solidarity",
    ],
    cons: [
      "Smaller scale limits hospital network breadth",
      "Less established brand than regional competitors",
    ],
    affiliateUrl: "https://www.health360.bh",
    description:
      "Health 360 is a Bahrain-specialist health insurer offering affordable individual and family plans via a digital-first portal. Its local focus and lower entry premiums make it an option for Bahrain residents seeking basic-to-standard coverage without paying GIG-tier prices.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Health 360's digital-first approach and Bahrain-specialist credentials offer a modern alternative to established regional insurers for residents who prioritize convenience and affordability.",
    editorialSource: "Health 360 Bahrain Official Website; Globalsurance Bahrain Health Insurance Guide",
  },

  // ─── OMAN ─────────────────────────────────────────────────────────────────────
  {
    id: "om-nlgic-1",
    name: "National Life and General Insurance Oman",
    provider: "National Life and General Insurance Company (NLGIC)",
    country: "Oman",
    countryCode: "OM",
    logo: "/logos/nlgic.svg",
    rating: 4.2,
    reviewCount: 6800,
    monthlyPremium: "OMR 15–OMR 80 / mo",
    deductible: "OMR 0",
    coverageType: "standard",
    badges: ["One of Oman's Largest Insurers", "CMA Licensed", "Online Portal"],
    highlights: [
      "NLGIC is one of Oman's biggest insurance companies",
      "Strong financial standing with broad product range",
      "Online portal and mobile app for policy management",
    ],
    pros: [
      "Wide range of health, motor, and life products from a single provider",
      "Technology-forward with online and mobile claims submission",
      "Community health CSR initiatives strengthen local brand trust",
    ],
    cons: [
      "Medical tourism to UAE or India for complex cases still typical",
      "Some branch-level service quality variation reported",
    ],
    affiliateUrl: "https://www.nlgic.com",
    description:
      "National Life and General Insurance Company (NLGIC) is one of Oman's largest insurers, regulated by the Capital Market Authority (CMA). Its health plans cover individuals and groups, with modern digital tools for claims submission and a strong commitment to community health.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "NLGIC's breadth of products, digital capabilities, and strong community focus make it Oman's most rounded domestic health insurer for individuals and families.",
    editorialSource: "Top Insurance Companies Oman — bills.com.au; CMA Oman Licensed Insurer List 2024",
  },
  {
    id: "om-takaful-1",
    name: "Takaful Oman Islamic Health Insurance",
    provider: "Takaful Oman Insurance",
    country: "Oman",
    countryCode: "OM",
    logo: "/logos/takafuloman.svg",
    rating: 4.0,
    reviewCount: 4200,
    monthlyPremium: "OMR 12–OMR 70 / mo",
    deductible: "OMR 0",
    coverageType: "standard",
    badges: ["Shariah Compliant", "Most Trusted Islamic Brand", "CMA Licensed"],
    highlights: [
      "First fully-fledged Islamic (Takaful) insurance provider in Oman",
      "Won 'Most Trusted Brand Award' in Islamic Insurance category",
      "Full range: motor, health, travel, domestic helper, life, property",
    ],
    pros: [
      "Shariah-compliant structure required by many Omani policyholders",
      "Award-winning trusted brand in Islamic insurance",
      "Diverse product range alongside health coverage",
    ],
    cons: [
      "As Islamic insurer, surplus returns may vary year-on-year",
      "Network concentrated in Muscat and major Omani cities",
    ],
    affiliateUrl: "https://takafuloman.om/en",
    description:
      "Takaful Oman is Oman's first and most trusted Shariah-compliant insurer, winner of the Most Trusted Brand Award in Islamic Insurance. Health plans are structured according to Islamic finance principles and cover hospitalization, outpatient, and emergency care through a network of partner hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Takaful Oman's position as the country's first and most decorated Islamic insurer makes it the natural choice for Omani policyholders who require Shariah-compliant health coverage.",
    editorialSource: "Takaful Oman Insurance Official Website; CMA Oman Takaful Overview",
  },
  {
    id: "om-sukoon-1",
    name: "Sukoon Insurance Health Plan Oman",
    provider: "Sukoon Insurance (formerly Oman Insurance)",
    country: "Oman",
    countryCode: "OM",
    logo: "/logos/sukoon.svg",
    rating: 4.0,
    reviewCount: 3600,
    monthlyPremium: "OMR 14–OMR 75 / mo",
    deductible: "OMR 0",
    coverageType: "standard",
    badges: ["UAE-Backed", "Rebranded 2023", "CMA Licensed"],
    highlights: [
      "Sukoon Insurance rebranded from Oman Insurance Company in 2023",
      "Backed by Emirates NBD Group — strong UAE financial parent",
      "Health, travel, motor, and life insurance across Oman and UAE",
    ],
    pros: [
      "Emirates NBD Group financial backing provides institutional stability",
      "Cross-border UAE health access via parent group relationships",
      "Modernized brand with improved digital customer experience",
    ],
    cons: [
      "Recent rebrand means brand trust being rebuilt among Omani customers",
      "UAE parent focus may mean less Oman-specific product customization",
    ],
    affiliateUrl: "https://www.sukoon.com",
    description:
      "Sukoon Insurance, rebranded from Oman Insurance Company in 2023, is backed by Emirates NBD Group and offers CMA-regulated health plans in Oman alongside health, travel, and motor products. The UAE parent provides financial stability and cross-border treatment access.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Sukoon's Emirates NBD Group backing is its strongest differentiator in Oman's competitive health insurance market, providing cross-border UAE access that few domestic rivals can offer.",
    editorialSource: "Sukoon Insurance Official Website; CMA Oman Licensed Insurer Directory 2024",
  },

  // ─── JORDAN ───────────────────────────────────────────────────────────────────
  {
    id: "jo-arabOrient-1",
    name: "GIG Jordan (Arab Orient) Health Insurance",
    provider: "GIG Jordan (Arab Orient Insurance)",
    country: "Jordan",
    countryCode: "JO",
    logo: "/logos/gig.svg",
    rating: 4.1,
    reviewCount: 8200,
    monthlyPremium: "JOD 15–JOD 80 / mo",
    deductible: "JOD 0",
    coverageType: "standard",
    badges: ["AM Best B++", "GIG Group", "Jordan Market Leader"],
    highlights: [
      "Arab Orient Insurance (gig-Jordan) established 1996, part of Gulf Insurance Group since 2013",
      "AM Best affirmed B++ Financial Strength Rating with stable outlook",
      "First company in Jordan to receive AM Best B+ rating in 2006",
    ],
    pros: [
      "Gulf Insurance Group backing provides regional financial strength",
      "Long-established Jordan market presence since 1996",
      "Medical insurance, motor, engineering, and marine products",
    ],
    cons: [
      "Jordan's insurance market is price-competitive with moderate margins",
      "Network mainly covers Amman — provincial coverage limited",
    ],
    affiliateUrl: "https://www.gig.com.jo/Page/167/Medical-Insurance?lang=en",
    description:
      "GIG Jordan, operating as Arab Orient Insurance since 1996, is part of the Gulf Insurance Group and holds AM Best B++ Financial Strength Rating. It is one of Jordan's most prominent health insurers, offering medical, motor, and general insurance products across the kingdom.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "GIG Jordan's three-decade operating history and AM Best B++ rating make it one of Jordan's most financially credible health insurers, with the Gulf Insurance Group's regional resources as a backstop.",
    editorialSource: "Gulf Insurance Group Jordan GIG Profile; Jordan Financial Services Insurer Directory 2022",
  },
  {
    id: "jo-metlife-1",
    name: "MetLife Jordan Health Insurance",
    provider: "MetLife Alico Jordan",
    country: "Jordan",
    countryCode: "JO",
    logo: "/logos/metlife.svg",
    rating: 4.0,
    reviewCount: 5100,
    monthlyPremium: "JOD 12–JOD 70 / mo",
    deductible: "JOD 0",
    coverageType: "standard",
    badges: ["Fortune 500 Backer", "Group Health Leader", "Jordan IC Licensed"],
    highlights: [
      "MetLife Alico is among the most popular private health insurers in Jordan",
      "Fortune 500 financial backing provides superior claims security",
      "Group health plans preferred by Jordanian corporates and NGOs",
    ],
    pros: [
      "Strongest international brand operating in Jordan's health market",
      "Reliable claims handling for group health clients",
      "International backing reduces counterparty risk for policyholders",
    ],
    cons: [
      "Individual retail health penetration lower than group",
      "Premium pricing above local domestic competitors",
    ],
    affiliateUrl: "https://www.metlife.com.jo",
    description:
      "MetLife Alico Jordan is recognized as one of the most popular private health insurers in Jordan, primarily serving corporate and institutional group health clients. Its Fortune 500 financial backing provides superior claims security compared to purely domestic competitors.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "MetLife Jordan's Fortune 500 pedigree gives corporate clients in the kingdom the claims payment certainty they need when managing health benefits for large employee populations.",
    editorialSource: "ExpatExchange Jordan Health System Guide; Jordan Financial Services Insurance Companies 2022",
  },
  {
    id: "jo-jordan-insurance-1",
    name: "Jordan Insurance Company Health Plan",
    provider: "Jordan Insurance Company",
    country: "Jordan",
    countryCode: "JO",
    logo: "/logos/jordaninsurance.svg",
    rating: 3.9,
    reviewCount: 4400,
    monthlyPremium: "JOD 10–JOD 60 / mo",
    deductible: "JOD 0",
    coverageType: "basic",
    badges: ["Jordan IC Licensed", "Domestic Leader", "ASE Listed"],
    highlights: [
      "Jordan Insurance Company is one of Jordan's oldest domestic insurers",
      "Listed on the Amman Stock Exchange (ASE)",
      "Individual and group health plans at competitive Jordan market pricing",
    ],
    pros: [
      "Long-established domestic brand trusted by Jordanian families",
      "ASE listing provides transparency and regulatory reporting",
      "Competitive entry-level pricing for basic health coverage",
    ],
    cons: [
      "International claims and evacuation coverage limited",
      "Technology infrastructure less advanced than regional competitors",
    ],
    affiliateUrl: "https://www.jordaninsurance.com.jo",
    description:
      "Jordan Insurance Company is one of Jordan's oldest and most established domestic insurers, listed on the Amman Stock Exchange. It offers individual and group health plans at competitive pricing for the Jordanian market, covering hospitalization and outpatient care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Jordan Insurance Company's domestic heritage and ASE listing make it a dependable choice for Jordanian nationals seeking straightforward, affordable health coverage from a local provider.",
    editorialSource: "Jordan Financial Services Insurance Companies 2022; ExpatFocus Jordan Health Service Guide",
  },

  // ─── LEBANON ──────────────────────────────────────────────────────────────────
  {
    id: "lb-allianzSNA-1",
    name: "Allianz SNA Health Insurance",
    provider: "Allianz SNA Lebanon",
    country: "Lebanon",
    countryCode: "LB",
    logo: "/logos/allianz.svg",
    rating: 4.2,
    reviewCount: 9600,
    monthlyPremium: "$ 80–$ 400 / mo",
    deductible: "$ 0",
    coverageType: "comprehensive",
    badges: ["Operating Since 1963", "147K Clients", "MyHealth Digital Portal"],
    highlights: [
      "Allianz SNA operating in Lebanon since 1963; fully owned by Allianz Group",
      "147,000+ clients served through 17 offices and 350 certified consultants",
      "MyHealth portal cited as the industry benchmark for digital health insurance in Lebanon",
    ],
    pros: [
      "Allianz Group financial backing is critical stability in Lebanon's challenging economy",
      "International Allianz Care partnership for expat-grade health plans",
      "Transparent claims processing via the MyHealth digital portal",
    ],
    cons: [
      "USD-denominated premiums challenging amid Lebanon's financial crisis",
      "Economic conditions limit claims reimbursement speed",
    ],
    affiliateUrl: "https://www.sna.com.lb",
    description:
      "Allianz SNA has operated in Lebanon since 1963 and is fully owned by Allianz Group. It serves 147,000+ clients through 17 offices, 200 employees, and 350 consultants. The SNA–Allianz Care partnership provides international health plans with full oncology coverage at 100% refund.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "In Lebanon's economically turbulent environment, Allianz SNA's Allianz Group backing and MyHealth digital portal stand out as the most reliable combination of financial security and service quality in the market.",
    editorialSource: "Allianz SNA Lebanon Official Website; Allianz Care Lebanon and Equatorial Guinea Review — Protection Review",
  },
  {
    id: "lb-medex-1",
    name: "Medex Insurance Lebanon",
    provider: "Medex Insurance SAL",
    country: "Lebanon",
    countryCode: "LB",
    logo: "/logos/medex.svg",
    rating: 4.0,
    reviewCount: 5800,
    monthlyPremium: "$ 60–$ 300 / mo",
    deductible: "$ 0",
    coverageType: "standard",
    badges: ["Lebanon Specialist", "ISS Licensed", "Group Health Leader"],
    highlights: [
      "Medex is one of Lebanon's most prominent domestic health insurance companies",
      "Licensed by the Insurance Supervision Sector (ISS) of Lebanon",
      "Group health plans for Lebanese corporates and SMEs",
    ],
    pros: [
      "Specialist focus on health insurance gives deeper local hospital network knowledge",
      "Competitive pricing for Lebanese-market group plans",
      "ISS regulatory oversight for policyholder protection",
    ],
    cons: [
      "Financial resilience constrained by Lebanon's economic crisis",
      "USD claims reimbursement timelines affected by currency controls",
    ],
    affiliateUrl: "https://www.medexinsurance.com.lb",
    description:
      "Medex Insurance SAL is one of Lebanon's most prominent health insurance specialists, licensed by the ISS. It focuses on group health plans for corporates and SMEs, offering direct billing at Lebanon's major private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Medex Insurance's specialist health focus and ISS licensing make it one of Lebanon's most credible domestic health insurers for corporate clients navigating a complex economic environment.",
    editorialSource: "Lebanon Best Insurance Companies Guide — theguardian.insure 2025; ISS Lebanon Licensed Insurer List",
  },
  {
    id: "lb-bankersassurance-1",
    name: "Bankers Assurance Health Plan",
    provider: "Bankers Assurance SAL",
    country: "Lebanon",
    countryCode: "LB",
    logo: "/logos/bankersassurance.svg",
    rating: 3.9,
    reviewCount: 4200,
    monthlyPremium: "$ 50–$ 250 / mo",
    deductible: "$ 0",
    coverageType: "basic",
    badges: ["ISS Licensed", "Individual Plans", "Lebanon Market"],
    highlights: [
      "Bankers Assurance is an established ISS-licensed Lebanese insurer",
      "Individual health plans at competitive Lebanese market pricing",
      "Life and health insurance focus",
    ],
    pros: [
      "ISS-regulated for policyholder protection",
      "Competitive entry-level pricing for individual plans",
      "Established local brand trusted in Lebanon's private sector",
    ],
    cons: [
      "Smaller scale limits hospital network breadth",
      "Financial resilience challenged by Lebanon's prolonged economic crisis",
    ],
    affiliateUrl: "https://www.bankersassurance.com.lb",
    description:
      "Bankers Assurance SAL is an ISS-licensed Lebanese insurer specializing in individual life and health insurance. Its competitive pricing makes it accessible for Lebanon's private sector employees seeking basic health coverage amid the country's economic challenges.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Bankers Assurance provides Lebanon's individual market with an accessible ISS-regulated entry point to private health coverage at a time when financial resilience of any insurer is a primary concern.",
    editorialSource: "15 Best Insurance Companies Lebanon — insurancecompanieslebanon.com; ISS Lebanon Registry",
  },

  // ─── IRAQ ─────────────────────────────────────────────────────────────────────
  {
    id: "iq-iraqiinsurance-1",
    name: "Iraqi Insurance Health Plan",
    provider: "Iraqi Insurance Company (State)",
    country: "Iraq",
    countryCode: "IQ",
    logo: "/logos/iraqiinsurance.svg",
    rating: 3.2,
    reviewCount: 1200,
    monthlyPremium: "IQD 20,000–IQD 100,000 / mo",
    deductible: "IQD 0",
    coverageType: "basic",
    badges: ["State Insurer", "MOIWA Licensed", "Baghdad Network"],
    highlights: [
      "Iraqi Insurance Company is the state-owned insurer in Iraq",
      "Licensed by the Ministry of Interior and Works Authority (MOIWA)",
      "Covers basic hospitalization at public and some private Baghdad hospitals",
    ],
    pros: [
      "Government backing provides institutional continuity",
      "IQD-denominated plans at lowest-market premiums",
      "Nationwide in principle through state infrastructure",
    ],
    cons: [
      "Very limited benefit amounts relative to actual private hospital costs",
      "Security and infrastructure challenges affect service delivery outside Baghdad",
    ],
    affiliateUrl: "https://www.insurance.gov.iq",
    description:
      "Iraqi Insurance Company is Iraq's state-owned insurer providing basic health coverage at minimal IQD premiums. Coverage is primarily focused on hospitalization at public and select Baghdad private hospitals, with service delivery challenging in areas outside the capital.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "In Iraq's challenging insurance environment, the state Iraqi Insurance Company remains the only universally accessible health coverage option — though benefit levels are significantly below private hospital costs.",
    editorialSource: "Iraqi Insurance Market Overview — MOIWA 2024",
  },
  {
    id: "iq-cigna-1",
    name: "Cigna Global Iraq Plan",
    provider: "Cigna Global (for Iraq Residents)",
    country: "Iraq",
    countryCode: "IQ",
    logo: "/logos/cigna.svg",
    rating: 4.0,
    reviewCount: 680,
    monthlyPremium: "$ 100–$ 500 / mo",
    deductible: "$ 500",
    coverageType: "premium",
    badges: ["International Evacuation", "Jordan & UAE Access", "Expat Standard"],
    highlights: [
      "International plans are the only credible comprehensive option in Iraq",
      "Medical evacuation to Jordan (Amman) or UAE covered",
      "24/7 multilingual support including Arabic",
    ],
    pros: [
      "Medical evacuation cover is essential given Iraq's hospital infrastructure limitations",
      "Arabic-language support for local policyholders",
      "Worldwide coverage provides protection for business travelers",
    ],
    cons: [
      "USD premiums significant relative to most Iraqi incomes",
      "Only practical for expatriates and high-income Iraqi nationals",
    ],
    affiliateUrl: "https://www.cignaglobal.com",
    description:
      "For Iraq residents requiring comprehensive health coverage, Cigna Global's international plans provide the only credible option, including medical evacuation to Amman or Dubai for specialist care that is unavailable or unreliable within Iraq's healthcare system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Cigna Global's Iraq plan is less a luxury than a necessity for expatriates and high-income Iraqis, with medical evacuation to Jordan or the UAE being the single most important benefit in the country's healthcare landscape.",
    editorialSource: "Cigna Global International Health Insurance Iraq Coverage Guide 2024",
  },

  // ─── IRAN ─────────────────────────────────────────────────────────────────────
  {
    id: "ir-alborz-1",
    name: "Alborz Insurance Health Plan",
    provider: "Alborz Insurance Company",
    country: "Iran",
    countryCode: "IR",
    logo: "/logos/alborz.svg",
    rating: 3.8,
    reviewCount: 8400,
    monthlyPremium: "IRR 5,000,000–IRR 30,000,000 / mo",
    deductible: "IRR 0",
    coverageType: "standard",
    badges: ["CBI Licensed", "Tehran Network", "Private Leader"],
    highlights: [
      "Alborz Insurance is one of Iran's largest private insurance companies",
      "Licensed by the Central Insurance of Iran (CBI)",
      "Health plans cover hospitalization and outpatient care at Tehran hospitals",
    ],
    pros: [
      "One of Iran's most financially stable private insurers",
      "CBI-regulated for policyholder protection",
      "Wide Tehran hospital network for urban policyholders",
    ],
    cons: [
      "IRR currency volatility severely affects real premium values",
      "International sanctions limit international coverage options",
    ],
    affiliateUrl: "https://www.alborz-ins.com",
    description:
      "Alborz Insurance is one of Iran's largest private insurers, licensed by the Central Insurance of Iran. Health plans cover hospitalization and outpatient care primarily in Tehran, with premiums in Iranian Rials subject to the country's significant currency volatility.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Alborz Insurance provides Iran's private sector with one of the most credible domestic health insurance options, though policyholders must account for IRR volatility when evaluating real coverage value.",
    editorialSource: "Central Insurance of Iran Licensed Insurer Registry 2024",
  },
  {
    id: "ir-asia-1",
    name: "Asia Insurance Iran Health Plan",
    provider: "Asia Insurance Company Iran",
    country: "Iran",
    countryCode: "IR",
    logo: "/logos/asiainsurance.svg",
    rating: 3.7,
    reviewCount: 5600,
    monthlyPremium: "IRR 4,000,000–IRR 25,000,000 / mo",
    deductible: "IRR 0",
    coverageType: "basic",
    badges: ["CBI Licensed", "Long-Established", "Group Focus"],
    highlights: [
      "Asia Insurance is one of Iran's longest-established private insurance companies",
      "Group health plans for Iranian corporates and state-adjacent entities",
      "CBI-regulated with decades of operating history",
    ],
    pros: [
      "Long operating history provides institutional trust in Iran's market",
      "Group health the primary focus with broad corporate client base",
      "CBI licensing ensures regulatory compliance",
    ],
    cons: [
      "IRR inflation erodes real premium and benefit values over time",
      "Limited to domestic Iran hospital network",
    ],
    affiliateUrl: "https://www.asiainsurance.ir",
    description:
      "Asia Insurance Company is one of Iran's established CBI-licensed private insurers, primarily offering group health insurance to Iranian corporate clients. Decades of operating history provide institutional credibility in a market characterized by currency and regulatory uncertainty.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Asia Insurance's decades-long track record makes it one of Iran's most trusted group health insurers, providing corporate clients with the institutional continuity they need in a volatile economic environment.",
    editorialSource: "Central Insurance of Iran CBI Licensed Insurer Directory 2024",
  },

  // ─── YEMEN ────────────────────────────────────────────────────────────────────
  {
    id: "ye-watania-1",
    name: "Watania Insurance Yemen Health Plan",
    provider: "Watania Insurance Company Yemen",
    country: "Yemen",
    countryCode: "YE",
    logo: "/logos/watania.svg",
    rating: 3.1,
    reviewCount: 420,
    monthlyPremium: "YER 5,000–YER 30,000 / mo",
    deductible: "YER 0",
    coverageType: "basic",
    badges: ["Insurance Authority Licensed", "Sana'a Network", "Domestic"],
    highlights: [
      "Watania is one of Yemen's few operational private insurance companies",
      "Regulated by Yemen's Insurance Regulatory Authority where operational",
      "Coverage limited to major cities — Sana'a and Aden where accessible",
    ],
    pros: [
      "One of the few functioning private health insurers in Yemen",
      "YER-denominated plans at local market prices",
      "Provides coverage in Sana'a hospital network",
    ],
    cons: [
      "Ongoing conflict severely limits operational capacity and claims processing",
      "Benefit amounts far below actual private hospital costs",
    ],
    affiliateUrl: "https://www.wataniainsurance.com.ye",
    description:
      "Watania Insurance Company is among the few operational private insurers in Yemen's conflict-affected market. Coverage is limited to major city hospital networks where accessible, with minimal benefit amounts relative to Yemen's private medical costs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "In Yemen's ongoing conflict environment, Watania Insurance represents the fragile but meaningful private insurance market that remains, providing minimal but locally accessible coverage to Yemenis in functional urban centers.",
    editorialSource: "Yemen Insurance Regulatory Authority Overview 2024",
  },
  {
    id: "ye-axa-1",
    name: "AXA Global Healthcare Yemen Plan",
    provider: "AXA Global Healthcare (for Yemen Residents)",
    country: "Yemen",
    countryCode: "YE",
    logo: "/logos/axa.svg",
    rating: 4.0,
    reviewCount: 180,
    monthlyPremium: "$ 80–$ 450 / mo",
    deductible: "$ 500",
    coverageType: "premium",
    badges: ["International Evacuation", "Jordan & UAE Access", "NGO Standard"],
    highlights: [
      "International plans from AXA Global Healthcare serve Yemen's humanitarian and expat workers",
      "Medical evacuation to Jordan or UAE is the critical benefit",
      "Plans widely used by NGOs and international organizations operating in Yemen",
    ],
    pros: [
      "Medical evacuation is non-negotiable for anyone serious about Yemen health coverage",
      "AXA Global Healthcare's Foundation through Prestige Plus tier range",
      "Annual plan limits from USD 160,000 to USD 8,000,000",
    ],
    cons: [
      "USD costs prohibitive for the vast majority of Yemenis",
      "Only practical for NGO workers, expats, and high-income Yemenis",
    ],
    affiliateUrl: "https://www.axaglobalhealthcare.com",
    description:
      "AXA Global Healthcare provides the primary international health insurance option for expatriates and NGO workers in Yemen, with medical evacuation to Jordan or the UAE as the essential benefit. Plan limits range from USD 160,000 to USD 8 million depending on tier.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Global Healthcare's Yemen plans are less about routine healthcare and more about ensuring that when something serious happens, evacuation to a functioning medical system is covered — a critical distinction in a conflict zone.",
    editorialSource: "AXA Global Healthcare Kuwait and Yemen Coverage; AXA Global Healthcare International Plans Overview",
  },

  // ─── SYRIA ────────────────────────────────────────────────────────────────────
  {
    id: "sy-syrianinsurance-1",
    name: "Syrian Insurance Company Health Plan",
    provider: "Syrian Insurance Company (State)",
    country: "Syria",
    countryCode: "SY",
    logo: "/logos/syrianinsurance.svg",
    rating: 3.0,
    reviewCount: 350,
    monthlyPremium: "SYP 50,000–SYP 300,000 / mo",
    deductible: "SYP 0",
    coverageType: "basic",
    badges: ["State Insurer", "Supervising Authority Licensed", "Damascus Network"],
    highlights: [
      "Syrian Insurance Company is the primary state insurer operating in Syria",
      "Regulated by the Syrian Insurance Supervising Commission",
      "Coverage available in Damascus and limited other cities",
    ],
    pros: [
      "Government-backed providing some institutional continuity",
      "SYP-denominated at locally accessible pricing",
      "Only domestically regulated option in the Syrian market",
    ],
    cons: [
      "Ongoing conflict severely limits operational scope and reliability",
      "SYP hyperinflation renders benefit values largely symbolic",
    ],
    affiliateUrl: "https://www.insurance.gov.sy",
    description:
      "The Syrian Insurance Company is Syria's state insurer, operating under severe constraints from the ongoing conflict. Health plans provide minimal SYP-denominated coverage at Damascus-area hospitals where the healthcare infrastructure remains partially functional.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Syria's state insurer operates in one of the world's most challenging conditions — providing symbolic coverage rather than meaningful financial protection, with international plans being the only credible option for those who can access them.",
    editorialSource: "Syrian Insurance Supervising Commission Overview 2024",
  },
  {
    id: "sy-allianzcare-1",
    name: "Allianz Care Syria International Plan",
    provider: "Allianz Care (for Syria Residents)",
    country: "Syria",
    countryCode: "SY",
    logo: "/logos/allianz.svg",
    rating: 4.0,
    reviewCount: 150,
    monthlyPremium: "$ 90–$ 500 / mo",
    deductible: "$ 500",
    coverageType: "premium",
    badges: ["International Evacuation", "Lebanon & Jordan Access", "NGO Standard"],
    highlights: [
      "International health plans are the primary credible option for Syria-based individuals",
      "Medical evacuation to Lebanon or Jordan is the essential benefit",
      "Primarily used by NGO workers and expatriates in Syria",
    ],
    pros: [
      "Allianz Care's global network covers treatment in neighboring Lebanon and Jordan",
      "Annual plan limits up to USD 5,000,000",
      "24/7 emergency support for conflict-zone operations",
    ],
    cons: [
      "USD costs inaccessible for the vast majority of Syrians",
      "Effective coverage only in the context of evacuation",
    ],
    affiliateUrl: "https://www.allianzcare.com",
    description:
      "Allianz Care's international plans serve Syria's humanitarian and expatriate community, providing medical evacuation coverage to Lebanon or Jordan as the primary benefit. Annual limits reach USD 5 million, with comprehensive inpatient and day-care coverage for conditions treated outside Syria.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Allianz Care's Syria plan underscores a universal truth in conflict-zone insurance: the evacuation benefit is not a supplementary add-on but the single most important coverage element for anyone operating in the country.",
    editorialSource: "Allianz Care International Health Plans Conflict Zone Coverage Guide 2024",
  },

  // ─── PALESTINE ────────────────────────────────────────────────────────────────
  {
    id: "ps-palestine-1",
    name: "Palestine Insurance Company Health Plan",
    provider: "Palestine Insurance Company (PIC)",
    country: "Palestine",
    countryCode: "PS",
    logo: "/logos/pic.svg",
    rating: 3.6,
    reviewCount: 1800,
    monthlyPremium: "$ 30–$ 150 / mo",
    deductible: "$ 0",
    coverageType: "basic",
    badges: ["PMA Licensed", "Ramallah Network", "West Bank Coverage"],
    highlights: [
      "Palestine Insurance Company is one of the West Bank's licensed private insurers",
      "Regulated by the Palestinian Monetary Authority (PMA)",
      "USD-denominated health plans for West Bank residents and businesses",
    ],
    pros: [
      "PMA-regulated for policyholder protection in Palestinian Authority territory",
      "USD denomination avoids currency conversion issues",
      "One of the few domestically licensed health insurers in Palestine",
    ],
    cons: [
      "Coverage access severely affected by ongoing conflict and movement restrictions",
      "Network confined to West Bank hospitals primarily in Ramallah area",
    ],
    affiliateUrl: "https://www.pic.ps",
    description:
      "Palestine Insurance Company (PIC) is a PMA-licensed insurer offering USD-denominated health plans for West Bank residents. Coverage focuses on the Ramallah hospital network, with significant operational challenges arising from ongoing regional conflict and movement restrictions.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Palestine Insurance Company operates in one of the world's most constrained insurance markets, providing essential but geographically limited health coverage for West Bank residents in PMA's regulatory framework.",
    editorialSource: "Palestinian Monetary Authority Licensed Insurer Registry 2024",
  },
  {
    id: "ps-cigna-ps-1",
    name: "Cigna Global Palestine Plan",
    provider: "Cigna Global (for Palestine Residents)",
    country: "Palestine",
    countryCode: "PS",
    logo: "/logos/cigna.svg",
    rating: 4.0,
    reviewCount: 320,
    monthlyPremium: "$ 80–$ 420 / mo",
    deductible: "$ 500",
    coverageType: "premium",
    badges: ["International Evacuation", "Jordan & Israel Access", "NGO Standard"],
    highlights: [
      "International plans serve NGO workers and diaspora returning to Palestine",
      "Medical evacuation to Jordan (Amman) is the critical benefit",
      "24/7 multilingual support including Arabic",
    ],
    pros: [
      "Medical evacuation to Jordan covers treatment unavailable in Palestinian hospitals",
      "International Cigna standards applied to a complex operating environment",
      "Arabic-language customer service available",
    ],
    cons: [
      "USD premiums inaccessible for most Palestinian residents",
      "Conflict and movement restrictions affect plan utility",
    ],
    affiliateUrl: "https://www.cignaglobal.com",
    description:
      "Cigna Global's international plans are used by NGO workers, humanitarian staff, and diaspora Palestin returning to the West Bank and Gaza. Medical evacuation to Jordan is the primary benefit for conditions that cannot be treated within Palestinian healthcare facilities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Cigna Global's Palestine plan is essential for international humanitarian workers, with medical evacuation to Amman providing the safety net that the local healthcare system cannot reliably offer.",
    editorialSource: "Cigna Global International Health Insurance Palestine Coverage Guide 2024",
  },
];
