import { InsurancePlan } from "./types";

export const plansMiddleEast: InsurancePlan[] = [
  // Saudi Arabia (SAR)
  {
    id: "sa-bupa-arabia",
    name: "Bupa Arabia Smart Plan",
    provider: "Bupa Arabia",
    country: "Saudi Arabia",
    countryCode: "sa",
    logo: "/logos/bupa-arabia.svg",
    rating: 4.5,
    reviewCount: 8312,
    monthlyPremium: "SAR 850 - SAR 2,200",
    deductible: "SAR 500 - SAR 2,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular", "Best Network"],
    highlights: [
      "Widest hospital network in Saudi Arabia",
      "24/7 telehealth consultations in Arabic",
      "Full maternity and newborn coverage",
    ],
    pros: [
      "Access to over 750 network hospitals and clinics",
      "Strong digital app for claims and appointments",
      "Comprehensive chronic disease management",
      "Fast pre-authorization process",
    ],
    cons: [
      "Premiums higher than local competitors",
      "Out-of-network reimbursement can be slow",
      "Some specialist referrals require GP gatekeeper",
    ],
    affiliateUrl: "#",
    description:
      "Bupa Arabia is the largest health insurer in Saudi Arabia, operating as a joint venture between Bupa and Nazer Group. The Smart Plan is designed for individuals and families seeking comprehensive inpatient and outpatient coverage across the Kingdom.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa Arabia sets the benchmark for private health coverage in Saudi Arabia with its extensive network and robust digital infrastructure.",
    editorialSource: "MENA Insurance Review 2025",
  },
  {
    id: "sa-tawuniya",
    name: "Tawuniya Afrad Premium",
    provider: "Tawuniya",
    country: "Saudi Arabia",
    countryCode: "sa",
    logo: "/logos/tawuniya.svg",
    rating: 4.3,
    reviewCount: 6147,
    monthlyPremium: "SAR 700 - SAR 1,800",
    deductible: "SAR 300 - SAR 1,500",
    coverageType: "premium",
    badges: ["Best Value", "Top Rated"],
    highlights: [
      "Strong government and semi-government employee plans",
      "Rapid claims settlement track record",
      "National coverage across all 13 regions",
    ],
    pros: [
      "Competitive premiums for comprehensive coverage",
      "Excellent customer service centres nationwide",
      "Dental and optical add-ons available",
      "Easy online claims submission",
    ],
    cons: [
      "International coverage limited to emergency only",
      "Mental health benefits require add-on",
      "Network smaller than Bupa Arabia in rural areas",
    ],
    affiliateUrl: "#",
    description:
      "Tawuniya (The Company for Cooperative Insurance) is one of Saudi Arabia's oldest and most trusted insurers. The Afrad Premium plan is tailored for individuals seeking solid inpatient and outpatient coverage with competitive pricing.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Tawuniya's long market presence and government partnerships make it a reliable choice for Saudi residents seeking dependable coverage.",
    editorialSource: "Saudi Insurance Market Report 2025",
  },
  {
    id: "sa-medgulf",
    name: "Medgulf Gold Health Plan",
    provider: "Mediterranean & Gulf Insurance (Medgulf)",
    country: "Saudi Arabia",
    countryCode: "sa",
    logo: "/logos/medgulf.svg",
    rating: 4.1,
    reviewCount: 3982,
    monthlyPremium: "SAR 600 - SAR 1,500",
    deductible: "SAR 400 - SAR 1,200",
    coverageType: "standard",
    badges: ["Best for Expats"],
    highlights: [
      "Designed for expatriate workforce in KSA",
      "Covers pre-existing conditions after waiting period",
      "Multilingual customer support",
    ],
    pros: [
      "Affordable entry-level to mid-range plans",
      "Good outpatient and pharmacy network",
      "Arabic and English support channels",
    ],
    cons: [
      "Limited maternity coverage in base plan",
      "Claims process can be paper-heavy",
      "Telehealth features less developed than larger competitors",
    ],
    affiliateUrl: "#",
    description:
      "Medgulf is a leading regional insurer operating across the GCC and Levant. Its Gold Health Plan is popular among small and medium enterprises looking to provide solid health coverage for expatriate employees in Saudi Arabia.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Medgulf offers solid mid-market value for SMEs and expats, with a well-established regional network across the GCC.",
    editorialSource: "Gulf Business Insurance Index 2025",
  },

  // Qatar (QAR)
  {
    id: "qa-daman-national",
    name: "Daman National Health Standard",
    provider: "Daman – National Health Insurance Company",
    country: "Qatar",
    countryCode: "qa",
    logo: "/logos/daman-qa.svg",
    rating: 4.2,
    reviewCount: 2874,
    monthlyPremium: "QAR 550 - QAR 1,400",
    deductible: "QAR 200 - QAR 800",
    coverageType: "standard",
    badges: ["Most Popular"],
    highlights: [
      "Compliant with Qatar's mandatory health insurance law",
      "Wide Hamad Medical Corporation network access",
      "Straightforward digital claims portal",
    ],
    pros: [
      "Accepted at all major Qatari hospitals",
      "Transparent pricing structure",
      "Good preventive care benefits",
      "Bilingual Arabic and English support",
    ],
    cons: [
      "International coverage not included in base plan",
      "Specialist visits require GP referral",
      "Dental and vision sold separately",
    ],
    affiliateUrl: "#",
    description:
      "Daman – National Health Insurance Company is Qatar's primary health insurer operating under the Qatar General Organisation for Social Insurance framework. The Standard plan is designed to meet mandatory insurance requirements for residents and employees.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Daman is the go-to insurer for legal compliance in Qatar, offering reliable coverage that meets all government-mandated requirements.",
    editorialSource: "Qatar Financial Centre Insurance Report 2025",
  },
  {
    id: "qa-qic-health",
    name: "QIC Health Premium",
    provider: "Qatar Insurance Company (QIC)",
    country: "Qatar",
    countryCode: "qa",
    logo: "/logos/qic.svg",
    rating: 4.0,
    reviewCount: 1935,
    monthlyPremium: "QAR 700 - QAR 2,000",
    deductible: "QAR 300 - QAR 1,000",
    coverageType: "premium",
    badges: ["Best for Families"],
    highlights: [
      "Comprehensive family maternity and newborn benefits",
      "Global emergency coverage included",
      "Cashless treatment at 200+ Qatar clinics",
    ],
    pros: [
      "Strong maternity and paediatric coverage",
      "International emergency included",
      "Good dental add-on packages",
    ],
    cons: [
      "Higher premiums for older applicants",
      "Mental health covered at limited level",
      "Claims app needs improvement",
    ],
    affiliateUrl: "#",
    description:
      "Qatar Insurance Company is the largest insurance company in Qatar and one of the largest in the Middle East. The QIC Health Premium plan targets families and professionals seeking broader coverage beyond the mandatory minimum.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "QIC Health Premium is well-suited for families relocating to Qatar who need comprehensive coverage with international emergency provisions.",
    editorialSource: "MENA Health Insurance Benchmark 2025",
  },

  // Kuwait (KWD)
  {
    id: "kw-axa-gulf",
    name: "AXA Gulf Flexi Health",
    provider: "AXA Gulf",
    country: "Kuwait",
    countryCode: "kw",
    logo: "/logos/axa-gulf.svg",
    rating: 4.3,
    reviewCount: 2105,
    monthlyPremium: "KWD 180 - KWD 450",
    deductible: "KWD 50 - KWD 200",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Best International Coverage"],
    highlights: [
      "Access to AXA's global provider network",
      "Full international coverage outside Kuwait",
      "Strong wellness and preventive benefits",
    ],
    pros: [
      "Global hospital network across 200 countries",
      "Seamless digital claims via AXA app",
      "Comprehensive mental health coverage",
      "Annual health checks included",
    ],
    cons: [
      "Among the pricier options in Kuwait",
      "Some routine dental excluded from base plan",
      "Pre-authorisation needed for elective procedures",
    ],
    affiliateUrl: "#",
    description:
      "AXA Gulf operates across the GCC and offers internationally backed health plans. The Flexi Health plan is designed for Kuwait residents seeking comprehensive coverage both locally and when travelling abroad.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Gulf Flexi Health is the top pick for Kuwait-based professionals who travel frequently and need consistent coverage across borders.",
    editorialSource: "Gulf Insurance Digest 2025",
  },
  {
    id: "kw-warba-health",
    name: "Warba Insurance Essential Health",
    provider: "Warba Insurance Company",
    country: "Kuwait",
    countryCode: "kw",
    logo: "/logos/warba.svg",
    rating: 3.9,
    reviewCount: 1243,
    monthlyPremium: "KWD 100 - KWD 280",
    deductible: "KWD 30 - KWD 120",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "Affordable entry-level plan for Kuwait residents",
      "Quick card issuance within 48 hours",
      "Good local clinic and pharmacy network",
    ],
    pros: [
      "Low monthly premiums",
      "No referral required for most specialists",
      "Fast card and policy issuance",
    ],
    cons: [
      "No international coverage",
      "Dental and vision not included",
      "Limited mental health benefits",
    ],
    affiliateUrl: "#",
    description:
      "Warba Insurance Company is a Kuwaiti insurer offering Sharia-compliant takaful products. The Essential Health plan provides core inpatient and outpatient coverage at affordable rates for individuals and families residing in Kuwait.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Warba Essential Health delivers solid value for Kuwait residents who need reliable local coverage without the premium price tag.",
    editorialSource: "Kuwait Insurance Market Survey 2025",
  },

  // Bahrain (BHD)
  {
    id: "bh-bupa-bahrain",
    name: "Bupa Bahrain SmartCare Plus",
    provider: "Bupa Bahrain",
    country: "Bahrain",
    countryCode: "bh",
    logo: "/logos/bupa-bahrain.svg",
    rating: 4.4,
    reviewCount: 1872,
    monthlyPremium: "BHD 55 - BHD 180",
    deductible: "BHD 20 - BHD 80",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Compliant with Bahrain's National Health Regulatory Authority",
      "Access to Bupa's global network for international travel",
      "Comprehensive maternity and newborn care",
    ],
    pros: [
      "Wide network of private hospitals in Bahrain",
      "Full maternity coverage from conception",
      "Digital health app with teleconsultation",
      "Straightforward claims process",
    ],
    cons: [
      "Premiums increase significantly with age",
      "Dental is an optional add-on",
      "Waiting periods for pre-existing conditions",
    ],
    affiliateUrl: "#",
    description:
      "Bupa Bahrain is the leading health insurer in the Kingdom of Bahrain, regulated by the Central Bank of Bahrain. SmartCare Plus provides comprehensive health coverage for individuals and families, meeting all NHRA requirements.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa Bahrain remains the market leader with best-in-class service and a plan that exceeds the country's mandatory coverage requirements.",
    editorialSource: "GCC Health Insurance Rankings 2025",
  },
  {
    id: "bh-medgulf-bahrain",
    name: "Medgulf Bahrain Individual Plan",
    provider: "Mediterranean & Gulf Insurance – Bahrain",
    country: "Bahrain",
    countryCode: "bh",
    logo: "/logos/medgulf-bh.svg",
    rating: 3.8,
    reviewCount: 892,
    monthlyPremium: "BHD 35 - BHD 110",
    deductible: "BHD 15 - BHD 60",
    coverageType: "standard",
    badges: ["Best for SMEs"],
    highlights: [
      "Affordable group and individual plans for SMEs",
      "NHRA-compliant basic package",
      "Regional Medgulf network access",
    ],
    pros: [
      "Competitive group pricing for small businesses",
      "Coverage across the GCC region",
      "Quick policy issuance",
    ],
    cons: [
      "Limited telehealth functionality",
      "Mental health and dental not included",
      "Claims processing time can vary",
    ],
    affiliateUrl: "#",
    description:
      "Medgulf's Bahrain branch provides health insurance solutions focused on small and medium enterprises. The Individual Plan delivers NHRA-compliant coverage at accessible price points.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Medgulf Bahrain is a practical and cost-conscious option for smaller employers who need compliant group health coverage.",
    editorialSource: "Bahrain Financial Services Review 2025",
  },

  // Oman (OMR)
  {
    id: "om-oman-insurance",
    name: "Oman Insurance MyCare Premium",
    provider: "Oman Insurance Company",
    country: "Oman",
    countryCode: "om",
    logo: "/logos/oman-insurance.svg",
    rating: 4.2,
    reviewCount: 2143,
    monthlyPremium: "OMR 45 - OMR 130",
    deductible: "OMR 10 - OMR 50",
    coverageType: "premium",
    badges: ["Most Popular", "Best Network"],
    highlights: [
      "Extensive Oman-wide clinic and hospital network",
      "Covers treatment at Sultan Qaboos University Hospital",
      "Digital pre-authorisation in under 2 hours",
    ],
    pros: [
      "Strong in-country hospital network",
      "Maternity benefits from month one",
      "Excellent customer service ratings",
      "Add-on dental and optical available",
    ],
    cons: [
      "International coverage only for emergencies",
      "Mental health sessions capped per year",
      "Premiums can be high for older age bands",
    ],
    affiliateUrl: "#",
    description:
      "Oman Insurance Company (OIC) is one of the largest insurers in the MENA region, headquartered in Dubai with a strong Oman operation. The MyCare Premium plan offers comprehensive coverage for Oman-based individuals and families.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Oman Insurance MyCare Premium is a top choice for Oman residents seeking reliable private coverage with a well-managed network.",
    editorialSource: "Oman Health Insurance Market Review 2025",
  },
  {
    id: "om-al-madina-takaful",
    name: "Al Madina Takaful Health Basic",
    provider: "Al Madina Takaful",
    country: "Oman",
    countryCode: "om",
    logo: "/logos/al-madina-takaful.svg",
    rating: 3.7,
    reviewCount: 1054,
    monthlyPremium: "OMR 25 - OMR 75",
    deductible: "OMR 5 - OMR 30",
    coverageType: "basic",
    badges: ["Best Value", "Sharia-Compliant"],
    highlights: [
      "Sharia-compliant takaful health plan",
      "Affordable coverage for low-income residents",
      "Good pharmacy and GP network in Muscat",
    ],
    pros: [
      "Very affordable premiums",
      "Takaful structure with surplus sharing",
      "No-frills essential health protection",
    ],
    cons: [
      "Limited specialist and hospital choices",
      "No maternity in base plan",
      "No telehealth or digital tools",
    ],
    affiliateUrl: "#",
    description:
      "Al Madina Takaful offers Islamic insurance products in Oman. The Health Basic plan is targeted at lower-income individuals and families seeking affordable, Sharia-compliant essential health coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Al Madina Takaful Health Basic is an accessible entry point to private health coverage in Oman for budget-conscious residents.",
    editorialSource: "Gulf Takaful Market Analysis 2025",
  },

  // Israel (ILS)
  {
    id: "il-maccabi",
    name: "Maccabi Gold Supplemental Plan",
    provider: "Maccabi Healthcare Services",
    country: "Israel",
    countryCode: "il",
    logo: "/logos/maccabi.svg",
    rating: 4.6,
    reviewCount: 9420,
    monthlyPremium: "ILS 180 - ILS 520",
    deductible: "ILS 0 - ILS 500",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Top Rated", "Most Popular"],
    highlights: [
      "Supplement to Israel's mandatory National Health Insurance",
      "Access to leading private specialists and private hospitals",
      "Comprehensive dental and vision included",
    ],
    pros: [
      "Top-tier network of private physicians",
      "Full dental and orthodontic coverage",
      "Mental health sessions without long waitlists",
      "Strong maternity and fertility treatments",
    ],
    cons: [
      "Monthly premiums increase with age",
      "Requires active Maccabi HMO membership as base",
      "Some experimental treatments excluded",
    ],
    affiliateUrl: "#",
    description:
      "Maccabi Healthcare Services is one of Israel's four statutory Health Maintenance Organisations (HMOs). The Gold Supplemental Plan sits on top of the mandatory Keren Holim coverage and provides faster access to private specialists, advanced treatments, and comprehensive dental.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Maccabi Gold is the benchmark supplemental plan in Israel, reducing wait times for specialists and covering treatments not included in the national basket.",
    editorialSource: "Israel Healthcare Consumer Report 2025",
  },
  {
    id: "il-clalit",
    name: "Clalit Mushlam Premium",
    provider: "Clalit Health Services",
    country: "Israel",
    countryCode: "il",
    logo: "/logos/clalit.svg",
    rating: 4.4,
    reviewCount: 12800,
    monthlyPremium: "ILS 150 - ILS 450",
    deductible: "ILS 0 - ILS 300",
    coverageType: "premium",
    badges: ["Largest Network", "Best Value"],
    highlights: [
      "Largest HMO network in Israel with over 5,000 physicians",
      "Affordable supplemental plan for Clalit members",
      "Wide mental health and rehabilitation coverage",
    ],
    pros: [
      "Israel's largest insured population",
      "Comprehensive rehabilitation and physiotherapy",
      "Wide dental network",
      "Strong chronic disease management",
    ],
    cons: [
      "Mushlam tier requires additional premium above Clalit base",
      "Private hospital room upgrade costs extra",
      "Wait times at busy clinics can still occur",
    ],
    affiliateUrl: "#",
    description:
      "Clalit Health Services is the largest HMO in Israel and among the largest in the world. The Mushlam Premium plan offers an extensive supplemental coverage layer providing access to private hospitalisation, advanced dental, and priority specialist appointments.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Clalit Mushlam is the supplemental plan of choice for millions of Israelis, combining affordability with a vast clinical network.",
    editorialSource: "Israeli Health System Performance Report 2025",
  },
  {
    id: "il-meuhedet",
    name: "Meuhedet Zahav Gold",
    provider: "Meuhedet Health Services",
    country: "Israel",
    countryCode: "il",
    logo: "/logos/meuhedet.svg",
    rating: 4.2,
    reviewCount: 5630,
    monthlyPremium: "ILS 130 - ILS 380",
    deductible: "ILS 0 - ILS 250",
    coverageType: "standard",
    badges: ["Best for Young Families"],
    highlights: [
      "Excellent maternity, fertility, and paediatric add-ons",
      "Competitive pricing for young families",
      "Digital appointment booking and teleconsultation",
    ],
    pros: [
      "Strong maternity and fertility support",
      "User-friendly digital platform",
      "Competitive family premiums",
    ],
    cons: [
      "Smaller network than Clalit or Maccabi",
      "International coverage limited to emergency",
      "Some dental sub-limits apply",
    ],
    affiliateUrl: "#",
    description:
      "Meuhedet is one of Israel's four statutory HMOs with a strong reputation for family healthcare. The Zahav Gold supplemental plan adds private specialist access, dental, and fertility treatments on top of the mandatory national basket.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Meuhedet Zahav Gold is particularly valued by young families for its fertility and paediatric benefits at a competitive price point.",
    editorialSource: "Israel HMO Comparison Study 2025",
  },

  // Jordan (JOD)
  {
    id: "jo-allianz-jordan",
    name: "Allianz Jordan HealthCare Plus",
    provider: "Allianz Jordan Insurance",
    country: "Jordan",
    countryCode: "jo",
    logo: "/logos/allianz-jordan.svg",
    rating: 4.3,
    reviewCount: 2840,
    monthlyPremium: "JOD 55 - JOD 160",
    deductible: "JOD 15 - JOD 60",
    coverageType: "premium",
    badges: ["Editor's Choice", "Best for Expats"],
    highlights: [
      "Backed by Allianz global network",
      "Coverage across Jordan's top private hospitals",
      "International emergency coverage included",
    ],
    pros: [
      "Reliable international insurer presence in Jordan",
      "Access to Jordan's best private hospitals (Jordan Hospital, Istishari)",
      "Comprehensive maternity and newborn benefits",
      "Digital claims and teleconsultation",
    ],
    cons: [
      "Premiums higher than local Jordanian insurers",
      "Dental and vision sold as add-ons",
      "Mental health benefit is capped",
    ],
    affiliateUrl: "#",
    description:
      "Allianz Jordan is one of the leading international insurers in the Jordanian market. The HealthCare Plus plan is popular among professionals and expatriates seeking private hospital coverage supported by Allianz's global infrastructure.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Allianz Jordan brings international standards to private health coverage in Jordan, making it the preferred choice for expatriates and corporate clients.",
    editorialSource: "Jordan Insurance Federation Annual Report 2025",
  },
  {
    id: "jo-arabic-insurance",
    name: "Arab Orient Insurance Health Plan",
    provider: "Arab Orient Insurance Company",
    country: "Jordan",
    countryCode: "jo",
    logo: "/logos/arab-orient.svg",
    rating: 3.9,
    reviewCount: 1732,
    monthlyPremium: "JOD 35 - JOD 100",
    deductible: "JOD 10 - JOD 40",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "Affordable Jordanian insurer with solid local network",
      "Group plans for SMEs and large corporations",
      "Easy direct billing at partner hospitals",
    ],
    pros: [
      "Competitive premiums for local market",
      "Good direct billing network in Amman",
      "Flexible benefit customisation for groups",
    ],
    cons: [
      "Limited coverage outside Jordan",
      "No telehealth platform",
      "Claims documentation requirements can be cumbersome",
    ],
    affiliateUrl: "#",
    description:
      "Arab Orient Insurance Company is one of Jordan's established local insurers. The Health Plan provides practical inpatient and outpatient coverage for Jordanian residents and employees at competitive rates.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Arab Orient delivers dependable local health coverage in Jordan at rates that make private insurance accessible to a wider population.",
    editorialSource: "Jordan Consumer Insurance Survey 2025",
  },

  // Lebanon (LBP)
  {
    id: "lb-allianz-sir",
    name: "Allianz SNA HealthCare",
    provider: "Allianz SNA",
    country: "Lebanon",
    countryCode: "lb",
    logo: "/logos/allianz-sna.svg",
    rating: 4.1,
    reviewCount: 2215,
    monthlyPremium: "LBP 1,800,000 - LBP 5,500,000",
    deductible: "LBP 500,000 - LBP 2,000,000",
    coverageType: "premium",
    badges: ["Most Popular", "Best for Professionals"],
    highlights: [
      "Operates despite Lebanon's economic challenges",
      "Covers hospitalisation at leading Beirut hospitals",
      "USD-indexed plan options available for stability",
    ],
    pros: [
      "Trusted international brand in a volatile market",
      "USD-linked premiums protect against lira devaluation",
      "Strong network at AUB Medical Centre and Hotel Dieu",
      "Telehealth consultations available",
    ],
    cons: [
      "Economic instability affects claim payouts",
      "High cost in USD-equivalent terms",
      "Policy may require dollar payment in some tiers",
    ],
    affiliateUrl: "#",
    description:
      "Allianz SNA is one of the largest insurers operating in Lebanon, offering health plans that have adapted to the country's complex economic environment. USD-indexed options help protect policyholders from the Lebanese pound's volatility.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Allianz SNA remains the most dependable private health insurer in Lebanon, navigating the country's economic crisis with USD-linked plan structures.",
    editorialSource: "Lebanon Insurance Monitor 2025",
  },
  {
    id: "lb-arope-insurance",
    name: "Arope Insurance Health Essential",
    provider: "Arope Insurance",
    country: "Lebanon",
    countryCode: "lb",
    logo: "/logos/arope.svg",
    rating: 3.8,
    reviewCount: 1423,
    monthlyPremium: "LBP 1,200,000 - LBP 3,500,000",
    deductible: "LBP 300,000 - LBP 1,200,000",
    coverageType: "standard",
    badges: ["Local Leader"],
    highlights: [
      "Lebanese insurer with 70+ years of history",
      "Accepts both LBP and USD premium payments",
      "Wide network of clinics and pharmacies in Beirut",
    ],
    pros: [
      "Flexible payment currency options",
      "Long-established local presence",
      "Good outpatient and pharmacy network",
    ],
    cons: [
      "Financial stability concerns in current economy",
      "International coverage very limited",
      "Digital services minimal",
    ],
    affiliateUrl: "#",
    description:
      "Arope Insurance is one of Lebanon's oldest and most recognisable insurance brands. The Health Essential plan provides standard inpatient and outpatient coverage for Lebanese residents seeking basic private health protection.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Arope Insurance is a resilient Lebanese brand offering practical health coverage in a challenging economic environment.",
    editorialSource: "Levant Insurance Review 2025",
  },

  // Iraq (IQD)
  {
    id: "iq-national-insurance-iraq",
    name: "National Insurance Company Iraq Health",
    provider: "National Insurance Company (Iraq)",
    country: "Iraq",
    countryCode: "iq",
    logo: "/logos/nic-iraq.svg",
    rating: 3.6,
    reviewCount: 987,
    monthlyPremium: "IQD 85,000 - IQD 250,000",
    deductible: "IQD 20,000 - IQD 80,000",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "State-owned insurer with nationwide presence",
      "Accepts coverage for government employees",
      "Covers major public and private hospitals in Baghdad",
    ],
    pros: [
      "Government-backed reliability",
      "Low premium cost",
      "Broad geographic acceptance",
    ],
    cons: [
      "Limited digital infrastructure",
      "Claims processing can be slow",
      "Benefit limits are modest",
    ],
    affiliateUrl: "#",
    description:
      "The National Insurance Company of Iraq is the leading state-owned insurer providing health coverage across Iraq. It serves government employees and offers affordable health plans for individuals seeking basic private coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Iraq's National Insurance Company provides a foundational layer of private health coverage for millions of Iraqis through its state-backed infrastructure.",
    editorialSource: "Iraq Financial Services Authority Report 2025",
  },
  {
    id: "iq-al-wiaam",
    name: "Al Wiaam Insurance Health Plan",
    provider: "Al Wiaam Insurance Company",
    country: "Iraq",
    countryCode: "iq",
    logo: "/logos/al-wiaam.svg",
    rating: 3.5,
    reviewCount: 612,
    monthlyPremium: "IQD 65,000 - IQD 180,000",
    deductible: "IQD 15,000 - IQD 60,000",
    coverageType: "basic",
    badges: ["Best Value"],
    highlights: [
      "Private Iraqi insurer with growing clinic network",
      "Affordable plans for private sector employees",
      "Direct billing at partner clinics in Baghdad and Erbil",
    ],
    pros: [
      "Very affordable premiums",
      "Direct billing available at partner facilities",
      "Growing network in Kurdistan Region",
    ],
    cons: [
      "Limited outside major cities",
      "No telehealth services",
      "Dental and vision not covered",
    ],
    affiliateUrl: "#",
    description:
      "Al Wiaam Insurance Company is a private Iraqi insurer offering basic health plans for individuals and small businesses. It is one of the few private insurers expanding network coverage into Iraq's Kurdistan Region.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Al Wiaam is a promising private health insurer in Iraq offering accessible plans for urban residents as the market gradually develops.",
    editorialSource: "Iraq Private Sector Insurance Update 2025",
  },

  // Iran (IRR)
  {
    id: "ir-iran-insurance",
    name: "Iran Insurance Supplemental Health",
    provider: "Iran Insurance Company (Bimeh Iran)",
    country: "Iran",
    countryCode: "ir",
    logo: "/logos/bimeh-iran.svg",
    rating: 3.8,
    reviewCount: 4521,
    monthlyPremium: "IRR 12,000,000 - IRR 35,000,000",
    deductible: "IRR 2,000,000 - IRR 8,000,000",
    coverageType: "standard",
    badges: ["Government-Backed", "Most Popular"],
    highlights: [
      "Iran's oldest and largest insurer",
      "Supplements mandatory Social Security health coverage",
      "Wide hospital acceptance across all 31 provinces",
    ],
    pros: [
      "Nationwide network acceptance",
      "Government-backed financial stability",
      "Covers advanced specialist procedures",
      "Affordable relative to market",
    ],
    cons: [
      "Currency inflation affects benefit value",
      "International coverage not available",
      "Digital services are limited",
    ],
    affiliateUrl: "#",
    description:
      "Bimeh Iran (Iran Insurance Company) is the largest state-owned insurer in Iran, established in 1935. The Supplemental Health plan provides additional coverage on top of Iran's universal Social Security insurance, helping cover co-payments and specialist costs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Bimeh Iran is the foundational supplemental insurer for millions of Iranians, bridging the gap between public coverage and private care needs.",
    editorialSource: "Iran Insurance Industry Yearbook 2025",
  },
  {
    id: "ir-parsian-insurance",
    name: "Parsian Insurance Health Gold",
    provider: "Parsian Insurance Company",
    country: "Iran",
    countryCode: "ir",
    logo: "/logos/parsian-insurance.svg",
    rating: 3.9,
    reviewCount: 2847,
    monthlyPremium: "IRR 15,000,000 - IRR 45,000,000",
    deductible: "IRR 1,500,000 - IRR 6,000,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "Leading private insurer in Iran",
      "Good specialist and private hospital access",
      "Dental coverage included in Gold tier",
    ],
    pros: [
      "One of Iran's best-rated private insurers",
      "Includes dental in Gold plan",
      "Responsive customer service",
    ],
    cons: [
      "Subject to inflation-related premium increases",
      "No telehealth platform",
      "Claims ceilings affected by currency volatility",
    ],
    affiliateUrl: "#",
    description:
      "Parsian Insurance is one of Iran's leading private insurers. The Health Gold plan offers a comprehensive supplement to mandatory public coverage, providing broader specialist access and dental benefits for higher-tier subscribers.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Parsian Insurance Health Gold is the standout private supplemental plan in Iran, offering dental and broader specialist coverage above the public baseline.",
    editorialSource: "Iran Private Insurance Rankings 2025",
  },

  // Turkey (TRY)
  {
    id: "tr-acibadem-health",
    name: "Acibadem Sigorta Premium Health",
    provider: "Acibadem Sigorta",
    country: "Turkey",
    countryCode: "tr",
    logo: "/logos/acibadem.svg",
    rating: 4.7,
    reviewCount: 11230,
    monthlyPremium: "TRY 3,500 - TRY 9,500",
    deductible: "TRY 500 - TRY 3,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Top Rated", "Best Hospital Network"],
    highlights: [
      "Direct access to Acibadem's world-class hospital group",
      "Comprehensive coverage including dental and vision",
      "24/7 physician on-call service",
    ],
    pros: [
      "Access to Turkey's best private hospital chain",
      "Full dental and orthodontic coverage",
      "Strong mental health and psychology benefits",
      "International emergency coverage included",
    ],
    cons: [
      "Premium costs high relative to Turkish average income",
      "Best benefits tied to Acibadem hospital group",
      "Annual premium increases due to inflation",
    ],
    affiliateUrl: "#",
    description:
      "Acibadem Sigorta is the insurance arm of Acibadem Healthcare Group, Turkey's leading private hospital chain. The Premium Health plan offers unparalleled access to Acibadem's facilities and comprehensive coverage that sets the benchmark in the Turkish private health market.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Acibadem Sigorta Premium Health is the gold standard in Turkish private health insurance, combining world-class hospitals with genuinely comprehensive benefits.",
    editorialSource: "Turkey Health Insurance Market Leader Report 2025",
  },
  {
    id: "tr-allianz-turkey",
    name: "Allianz Turkey Sağlık Plus",
    provider: "Allianz Sigorta (Turkey)",
    country: "Turkey",
    countryCode: "tr",
    logo: "/logos/allianz-turkey.svg",
    rating: 4.4,
    reviewCount: 8760,
    monthlyPremium: "TRY 2,800 - TRY 7,500",
    deductible: "TRY 400 - TRY 2,000",
    coverageType: "premium",
    badges: ["Most Popular", "Best for Expats"],
    highlights: [
      "Backed by Allianz global network for international coverage",
      "Wide panel of 1,800+ contracted hospitals across Turkey",
      "Strong maternity package with comprehensive newborn cover",
    ],
    pros: [
      "International emergency coverage",
      "Broad hospital network beyond single-brand facilities",
      "Digital health app with teleconsultation",
      "Competitive group plans for corporates",
    ],
    cons: [
      "Not as strong as Acibadem at top-tier hospitals",
      "Dental coverage limited in base tier",
      "Inflation-adjusted premium increases annually",
    ],
    affiliateUrl: "#",
    description:
      "Allianz Sigorta is one of Turkey's largest private insurers and part of the global Allianz Group. The Sağlık Plus plan provides broad hospital network access across Turkey with international backing, making it particularly attractive for expatriates and corporate clients.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Allianz Turkey Sağlık Plus combines global insurance expertise with an extensive local network, making it the top choice for Turkey's expatriate community.",
    editorialSource: "Turkey Insurance Association Market Review 2025",
  },
  {
    id: "tr-axa-sigorta",
    name: "AXA Sigorta Sağlık Standard",
    provider: "AXA Sigorta (Turkey)",
    country: "Turkey",
    countryCode: "tr",
    logo: "/logos/axa-sigorta.svg",
    rating: 4.1,
    reviewCount: 6140,
    monthlyPremium: "TRY 2,000 - TRY 5,500",
    deductible: "TRY 300 - TRY 1,500",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "Affordable AXA-backed coverage for Turkish residents",
      "Access to 1,500+ contracted hospitals nationwide",
      "Good outpatient and diagnostic coverage",
    ],
    pros: [
      "Competitive premiums in Turkish market",
      "Trusted international brand",
      "Solid outpatient and diagnostic benefits",
    ],
    cons: [
      "Fewer top-tier hospitals than Acibadem plan",
      "International coverage limited to emergency",
      "Mental health sessions capped at 10 per year",
    ],
    affiliateUrl: "#",
    description:
      "AXA Sigorta is a major insurer in Turkey operating as part of the global AXA Group. The Sağlık Standard plan is the accessible mid-market option offering solid coverage at a price point appropriate for individuals and SMEs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Sigorta Standard is a reliable mid-market choice in Turkey, delivering solid daily health coverage at a price accessible to a broad population.",
    editorialSource: "Turkey Consumer Insurance Guide 2025",
  },

  // Yemen (YER)
  {
    id: "ye-trust-insurance",
    name: "Trust Yemen Insurance Health",
    provider: "Trust Yemen Insurance Company",
    country: "Yemen",
    countryCode: "ye",
    logo: "/logos/trust-yemen.svg",
    rating: 3.5,
    reviewCount: 423,
    monthlyPremium: "YER 25,000 - YER 70,000",
    deductible: "YER 5,000 - YER 20,000",
    coverageType: "basic",
    badges: ["Available in Conflict Zone"],
    highlights: [
      "One of the few operational private insurers in Yemen",
      "Covers treatment at functional private hospitals in Aden and Sana'a",
      "Emergency evacuation support available",
    ],
    pros: [
      "Operational coverage in a severely constrained market",
      "Emergency medical evacuation support",
      "Affordable premiums given coverage available",
    ],
    cons: [
      "Very limited hospital network due to conflict",
      "Claims processing significantly delayed",
      "Benefits restricted by security conditions",
    ],
    affiliateUrl: "#",
    description:
      "Trust Yemen Insurance Company is one of the few private insurers continuing operations in Yemen despite the ongoing conflict. The Health plan provides basic coverage at functional hospitals in accessible urban areas.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Trust Yemen Insurance remains one of the few viable options for basic private health coverage in Yemen, operating under extremely difficult conditions.",
    editorialSource: "MENA Frontier Insurance Market Report 2025",
  },
  {
    id: "ye-marib-insurance",
    name: "Marib Insurance Basic Health",
    provider: "Marib Insurance Company",
    country: "Yemen",
    countryCode: "ye",
    logo: "/logos/marib-insurance.svg",
    rating: 3.5,
    reviewCount: 287,
    monthlyPremium: "YER 18,000 - YER 55,000",
    deductible: "YER 4,000 - YER 15,000",
    coverageType: "basic",
    badges: ["Local Insurer"],
    highlights: [
      "Local Yemeni insurer focused on Aden region",
      "Basic inpatient coverage at partner hospitals",
      "Low-cost plans for NGO and aid worker coverage",
    ],
    pros: [
      "Lowest available premiums in Yemen",
      "Serves aid worker and NGO community",
      "Localised knowledge of operational facilities",
    ],
    cons: [
      "Very limited network and coverage area",
      "No digital infrastructure",
      "Claim amounts are low relative to actual costs",
    ],
    affiliateUrl: "#",
    description:
      "Marib Insurance Company is a Yemeni insurer operating primarily in southern Yemen. The Basic Health plan is used mainly by NGOs and local organisations seeking basic health coverage for their staff.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Marib Insurance provides a minimal but functioning health coverage option in Yemen's deeply constrained private insurance market.",
    editorialSource: "Yemen Humanitarian Sector Insurance Review 2025",
  },

  // Syria (SYP)
  {
    id: "sy-syrian-arab-insurance",
    name: "Syrian Arab Insurance Establishment Health",
    provider: "Syrian Arab Insurance Establishment (SAIE)",
    country: "Syria",
    countryCode: "sy",
    logo: "/logos/saie.svg",
    rating: 3.5,
    reviewCount: 318,
    monthlyPremium: "SYP 500,000 - SYP 1,500,000",
    deductible: "SYP 100,000 - SYP 400,000",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "State-owned insurer operational in government-held areas",
      "Covers hospitalisation at public and private hospitals in Damascus",
      "Low-cost plans for civil servants",
    ],
    pros: [
      "Government-backed coverage",
      "Affordable premiums for civil servants",
      "Accepted at major Damascus hospitals",
    ],
    cons: [
      "Limited geographic reach due to conflict",
      "Currency inflation erodes benefit value",
      "Minimal digital services",
    ],
    affiliateUrl: "#",
    description:
      "The Syrian Arab Insurance Establishment (SAIE) is Syria's state-owned insurer, continuing operations primarily in government-controlled areas including Damascus. The Health plan supplements Syria's weakened public health system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "SAIE remains the only functioning formal health insurer in Syria, providing limited but essential coverage for civil servants and urban residents.",
    editorialSource: "Syria Financial Markets Monitor 2025",
  },
  {
    id: "sy-al-aqeela",
    name: "Al Aqeela Insurance Health Basic",
    provider: "Al Aqeela Insurance Company",
    country: "Syria",
    countryCode: "sy",
    logo: "/logos/al-aqeela.svg",
    rating: 3.6,
    reviewCount: 201,
    monthlyPremium: "SYP 350,000 - SYP 1,000,000",
    deductible: "SYP 80,000 - SYP 300,000",
    coverageType: "basic",
    badges: ["Private Option"],
    highlights: [
      "Private Syrian insurer with pre-war legacy",
      "Coverage at partner private clinics in Damascus and Latakia",
      "Accepts USD payment for premium stability",
    ],
    pros: [
      "USD-payment option protects against SYP devaluation",
      "Private clinic network in major cities",
      "Long operational history in Syria",
    ],
    cons: [
      "Very restricted network outside major cities",
      "Limited benefit coverage due to economic constraints",
      "No digital infrastructure",
    ],
    affiliateUrl: "#",
    description:
      "Al Aqeela Insurance Company is one of Syria's pre-war established private insurers that has continued partial operations. The Health Basic plan provides minimal but functioning coverage at private clinics in Damascus and Latakia.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Al Aqeela Insurance is one of the few private health insurance options remaining in Syria, operating with USD payment options to maintain financial viability.",
    editorialSource: "Levant Insurance Market Update 2025",
  },

  // Palestine (ILS)
  {
    id: "ps-palestine-insurance",
    name: "Palestine Insurance Company Health Plan",
    provider: "Palestine Insurance Company",
    country: "Palestine",
    countryCode: "ps",
    logo: "/logos/pic-palestine.svg",
    rating: 3.7,
    reviewCount: 892,
    monthlyPremium: "ILS 120 - ILS 350",
    deductible: "ILS 50 - ILS 200",
    coverageType: "standard",
    badges: ["Most Popular", "Local Leader"],
    highlights: [
      "Largest private insurer in West Bank and Gaza",
      "Covers treatment at Palestinian Authority hospitals",
      "Plans available in ILS and USD",
    ],
    pros: [
      "Broad acceptance at PA-funded hospitals and clinics",
      "Affordable relative to population income levels",
      "Bilingual Arabic and Hebrew customer support in West Bank",
    ],
    cons: [
      "Access severely restricted in Gaza due to conflict",
      "Limited specialist options",
      "No international emergency coverage",
    ],
    affiliateUrl: "#",
    description:
      "Palestine Insurance Company (PIC) is the largest insurance company in Palestine, operating across the West Bank and where accessible in Gaza. The Health Plan provides private health coverage supplementing Palestinian Authority public health services.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Palestine Insurance Company is the most accessible private health coverage option for West Bank residents seeking supplemental protection.",
    editorialSource: "Palestinian Insurance Market Assessment 2025",
  },
  {
    id: "ps-arab-insurance-group",
    name: "Arab Insurance Group Palestine Health",
    provider: "Arab Insurance Group (ARIG) – Palestine Branch",
    country: "Palestine",
    countryCode: "ps",
    logo: "/logos/arig-palestine.svg",
    rating: 3.8,
    reviewCount: 641,
    monthlyPremium: "ILS 150 - ILS 420",
    deductible: "ILS 60 - ILS 220",
    coverageType: "standard",
    badges: ["Best for NGO Staff"],
    highlights: [
      "Covers NGO and international organisation employees in Palestine",
      "Accepts treatment referrals to Israeli or Jordanian hospitals",
      "USD-denominated premiums available",
    ],
    pros: [
      "International organisation staff coverage specialist",
      "Cross-border treatment referrals possible",
      "USD premium option",
    ],
    cons: [
      "Access restricted by movement limitations",
      "Higher cost than local competitors",
      "Gaza operations severely limited",
    ],
    affiliateUrl: "#",
    description:
      "Arab Insurance Group (ARIG) operates a Palestinian branch focused on serving international NGOs and organisations. The Palestine Health plan covers cross-border treatment referrals and is denominated in USD for international employers.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "ARIG Palestine Health is uniquely positioned to serve international NGO staff, offering cross-border treatment access critical for complex medical needs.",
    editorialSource: "Palestine NGO Health Coverage Review 2025",
  },
];
