import { InsurancePlan } from "./types";

export const plansAfrica: InsurancePlan[] = [
  // Nigeria (NGN)
  {
    id: "ng-nhia",
    name: "NHIA Formal Sector Social Health Insurance",
    provider: "National Health Insurance Authority (NHIA)",
    country: "Nigeria",
    countryCode: "ng",
    logo: "/logos/nhia-nigeria.svg",
    rating: 3.6,
    reviewCount: 5430,
    monthlyPremium: "NGN 6,000 - NGN 18,000",
    deductible: "NGN 1,000 - NGN 5,000",
    coverageType: "basic",
    badges: ["Government-Backed", "Most Accessible"],
    highlights: [
      "Mandatory scheme for federal government employees",
      "Nationwide accredited healthcare provider network",
      "Covers primary, secondary, and selected tertiary care",
    ],
    pros: [
      "Low contribution rates for formal sector workers",
      "Government co-contribution for employees",
      "Wide geographic coverage across 36 states",
      "Covers dependants including spouse and up to 4 children",
    ],
    cons: [
      "Benefit limits are modest",
      "Quality of accredited providers varies widely",
      "Claims processing and reimbursement can be slow",
    ],
    affiliateUrl: "#",
    description:
      "The National Health Insurance Authority (formerly NHIS) administers Nigeria's social health insurance programme. The Formal Sector Social Health Insurance Programme covers federal government employees and their families through accredited Health Maintenance Organisations (HMOs).",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Nigeria's NHIA programme provides a critical first layer of health coverage for formal sector workers, though benefit levels remain modest relative to actual healthcare costs.",
    editorialSource: "Nigerian Healthcare Financing Review 2025",
  },
  {
    id: "ng-hygeia",
    name: "Hygeia HMO Premium",
    provider: "Hygeia HMO",
    country: "Nigeria",
    countryCode: "ng",
    logo: "/logos/hygeia.svg",
    rating: 4.2,
    reviewCount: 7820,
    monthlyPremium: "NGN 45,000 - NGN 130,000",
    deductible: "NGN 5,000 - NGN 20,000",
    coverageType: "premium",
    badges: ["Editor's Choice", "Top Rated"],
    highlights: [
      "One of Nigeria's oldest and most trusted HMOs",
      "Own hospital facilities for direct care",
      "Comprehensive family and corporate plans",
    ],
    pros: [
      "Own Hygeia hospitals for integrated care",
      "Broad network of 3,000+ accredited providers",
      "Strong maternity and newborn benefits",
      "Teleconsultation available",
    ],
    cons: [
      "Higher premiums than government HMOs",
      "International coverage not included",
      "Some specialist services require referrals",
    ],
    affiliateUrl: "#",
    description:
      "Hygeia HMO is one of Nigeria's oldest private health maintenance organisations, founded in 1985. The Premium plan provides comprehensive inpatient, outpatient, and specialist care through Hygeia's own hospital network and a nationwide panel of accredited providers.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Hygeia HMO stands out in Nigeria's fragmented health insurance market with its integrated hospital network and consistent service quality.",
    editorialSource: "Nigeria HMO Performance Rankings 2025",
  },
  {
    id: "ng-axa-mansard",
    name: "AXA Mansard Health Individual Plan",
    provider: "AXA Mansard Insurance",
    country: "Nigeria",
    countryCode: "ng",
    logo: "/logos/axa-mansard.svg",
    rating: 4.3,
    reviewCount: 9125,
    monthlyPremium: "NGN 55,000 - NGN 160,000",
    deductible: "NGN 8,000 - NGN 30,000",
    coverageType: "comprehensive",
    badges: ["Most Popular", "Best for Corporates"],
    highlights: [
      "Backed by AXA Group's global expertise",
      "Widest provider network among Nigerian HMOs",
      "Strong digital health tools and teleconsultation",
    ],
    pros: [
      "Access to 5,000+ providers across Nigeria",
      "Excellent digital claims and pre-authorisation app",
      "Comprehensive corporate plan options",
      "Optional international emergency add-on",
    ],
    cons: [
      "Premium pricing for comprehensive tiers",
      "Mental health benefits limited in base plan",
      "Dental covered as add-on only",
    ],
    affiliateUrl: "#",
    description:
      "AXA Mansard Insurance is a leading Nigerian insurer backed by the global AXA Group. The Health Individual Plan provides comprehensive coverage for professionals and families with access to one of Nigeria's widest healthcare provider networks.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Mansard is Nigeria's most digitally advanced health insurer, combining global insurance standards with the largest provider network in the country.",
    editorialSource: "Nigeria Insurance Industry Awards 2025",
  },

  // Kenya (KES)
  {
    id: "ke-aar-health",
    name: "AAR Health Insurance Comprehensive",
    provider: "AAR Insurance Kenya",
    country: "Kenya",
    countryCode: "ke",
    logo: "/logos/aar-kenya.svg",
    rating: 4.3,
    reviewCount: 6240,
    monthlyPremium: "KES 4,500 - KES 14,000",
    deductible: "KES 1,000 - KES 5,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "One of Kenya's oldest and most trusted health insurers",
      "Own AAR clinics for integrated outpatient care",
      "Covers evacuation to Nairobi for upcountry emergencies",
    ],
    pros: [
      "Own clinic network for fast outpatient access",
      "Strong maternity and newborn benefits",
      "Medical evacuation coverage included",
      "24/7 medical helpline",
    ],
    cons: [
      "International coverage limited to emergency",
      "Dental and optical sold separately",
      "Network thinner outside Nairobi and Mombasa",
    ],
    affiliateUrl: "#",
    description:
      "AAR Insurance Kenya is one of the country's most established private health insurers, operating since 1984. The Comprehensive plan provides inpatient and outpatient coverage through AAR's own clinics and a wide panel of partner hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AAR Health Insurance is a cornerstone of Kenya's private health market, trusted for its integrated clinic network and reliable claims service.",
    editorialSource: "Kenya Health Insurance Market Report 2025",
  },
  {
    id: "ke-jubilee-health",
    name: "Jubilee Health Insurance Premier",
    provider: "Jubilee Insurance Kenya",
    country: "Kenya",
    countryCode: "ke",
    logo: "/logos/jubilee-kenya.svg",
    rating: 4.5,
    reviewCount: 8910,
    monthlyPremium: "KES 6,000 - KES 18,000",
    deductible: "KES 1,500 - KES 6,000",
    coverageType: "premium",
    badges: ["Top Rated", "Best Network"],
    highlights: [
      "Largest hospital network in Kenya with 700+ providers",
      "Comprehensive dental and optical in Premier plan",
      "International medical coverage for treatment abroad",
    ],
    pros: [
      "Kenya's most extensive hospital panel",
      "Dental and optical included in Premier",
      "International treatment coverage",
      "Strong digital health platform",
    ],
    cons: [
      "Higher premiums for comprehensive tiers",
      "Mental health benefit limited",
      "Pre-authorisation required for elective procedures",
    ],
    affiliateUrl: "#",
    description:
      "Jubilee Insurance is East Africa's largest insurer and Kenya's leading health insurance provider. The Premier plan offers comprehensive benefits including dental, optical, and international treatment options for individuals and families seeking top-tier coverage.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Jubilee Health Insurance Premier is Kenya's most comprehensive private health plan, offering the widest network and the most complete benefit package available.",
    editorialSource: "East Africa Insurance Awards 2025",
  },
  {
    id: "ke-uap-health",
    name: "UAP Old Mutual Health Gold",
    provider: "UAP Old Mutual Insurance Kenya",
    country: "Kenya",
    countryCode: "ke",
    logo: "/logos/uap-kenya.svg",
    rating: 4.1,
    reviewCount: 4830,
    monthlyPremium: "KES 3,800 - KES 12,000",
    deductible: "KES 1,000 - KES 4,000",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "Old Mutual backing provides strong financial stability",
      "Good mid-market coverage at competitive premiums",
      "Wellness and preventive care programme",
    ],
    pros: [
      "Competitive mid-market pricing",
      "Backed by Old Mutual's pan-African scale",
      "Wellness programme with health screenings",
    ],
    cons: [
      "Network not as large as Jubilee",
      "International coverage excluded",
      "Digital tools could be improved",
    ],
    affiliateUrl: "#",
    description:
      "UAP Old Mutual is a pan-African financial services group with a strong Kenyan insurance presence. The Health Gold plan delivers reliable mid-market coverage for individuals and SMEs seeking solid value at accessible premiums.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "UAP Old Mutual Health Gold is a dependable mid-market option for Kenyan families seeking solid coverage at a price-conscious premium.",
    editorialSource: "Kenya Insurance Buyer's Guide 2025",
  },

  // Egypt (EGP)
  {
    id: "eg-axa-egypt",
    name: "AXA Egypt Health Premier",
    provider: "AXA Insurance Egypt",
    country: "Egypt",
    countryCode: "eg",
    logo: "/logos/axa-egypt.svg",
    rating: 4.4,
    reviewCount: 7650,
    monthlyPremium: "EGP 2,500 - EGP 7,500",
    deductible: "EGP 500 - EGP 2,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Backed by AXA Group's global expertise",
      "Wide Cairo and Alexandria hospital network",
      "Comprehensive maternity and newborn coverage",
    ],
    pros: [
      "International insurer reliability in Egypt",
      "Comprehensive maternity package",
      "Digital claims portal available",
      "Good specialist and diagnostic coverage",
    ],
    cons: [
      "Premiums rising with Egyptian inflation",
      "Dental covered as add-on only",
      "International coverage limited to emergency",
    ],
    affiliateUrl: "#",
    description:
      "AXA Insurance Egypt is one of Egypt's leading private health insurers, part of the global AXA Group. The Health Premier plan provides comprehensive coverage for Egyptians and expatriates seeking private healthcare beyond the public health system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AXA Egypt Health Premier is the go-to choice for Egypt's professional class, offering international-standard coverage at one of Egypt's widest hospital networks.",
    editorialSource: "Egypt Insurance Market Review 2025",
  },
  {
    id: "eg-metlife-egypt",
    name: "MetLife Egypt MediGold",
    provider: "MetLife Egypt Insurance",
    country: "Egypt",
    countryCode: "eg",
    logo: "/logos/metlife-egypt.svg",
    rating: 4.2,
    reviewCount: 5840,
    monthlyPremium: "EGP 2,000 - EGP 6,000",
    deductible: "EGP 400 - EGP 1,500",
    coverageType: "premium",
    badges: ["Best for Corporates", "Top Rated"],
    highlights: [
      "MetLife global backing with strong Egyptian operations",
      "Comprehensive corporate group plans",
      "Wide dental and vision add-on options",
    ],
    pros: [
      "Strong corporate group plan portfolio",
      "Good dental and vision add-on packages",
      "Reliable claims service",
    ],
    cons: [
      "Premiums subject to inflationary adjustments",
      "International coverage not standard",
      "Telehealth functionality limited",
    ],
    affiliateUrl: "#",
    description:
      "MetLife Egypt is a leading international insurer with deep roots in the Egyptian market. The MediGold plan is particularly strong for corporate clients, offering comprehensive group health benefits for employees and their families.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "MetLife Egypt MediGold is Egypt's leading corporate group health plan, trusted by major multinationals and local corporations for employee benefits.",
    editorialSource: "Egypt Employee Benefits Survey 2025",
  },
  {
    id: "eg-gig-egypt",
    name: "GIG Egypt Health Standard",
    provider: "Gulf Insurance Group Egypt",
    country: "Egypt",
    countryCode: "eg",
    logo: "/logos/gig-egypt.svg",
    rating: 3.9,
    reviewCount: 3210,
    monthlyPremium: "EGP 1,500 - EGP 4,500",
    deductible: "EGP 300 - EGP 1,000",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "GCC-backed insurer with strong Egyptian market footprint",
      "Affordable mid-market plans for Egyptian families",
      "Covers treatment at major Cairo and Alexandria hospitals",
    ],
    pros: [
      "Competitive pricing for solid coverage",
      "GCC insurer credibility",
      "Good hospital panel in major cities",
    ],
    cons: [
      "Limited coverage outside Cairo and Alexandria",
      "No telehealth features",
      "Mental health and dental excluded",
    ],
    affiliateUrl: "#",
    description:
      "Gulf Insurance Group Egypt is a branch of the Kuwait-headquartered GIG, operating across MENA. The Health Standard plan provides affordable mid-market coverage for Egyptian residents in major urban centres.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "GIG Egypt Health Standard delivers dependable urban coverage at a price point accessible to middle-class Egyptian families.",
    editorialSource: "MENA Health Insurance Consumer Report 2025",
  },

  // Morocco (MAD)
  {
    id: "ma-cnops",
    name: "CNOPS Inaya Complementary Health",
    provider: "Caisse Nationale des Organismes de Prévoyance Sociale (CNOPS)",
    country: "Morocco",
    countryCode: "ma",
    logo: "/logos/cnops.svg",
    rating: 3.9,
    reviewCount: 4120,
    monthlyPremium: "MAD 350 - MAD 900",
    deductible: "MAD 100 - MAD 400",
    coverageType: "standard",
    badges: ["Government-Backed", "Most Popular"],
    highlights: [
      "Mandatory scheme for civil servants and their families",
      "Supplements the AMO (Assurance Maladie Obligatoire) base coverage",
      "Wide network across all Moroccan provinces",
    ],
    pros: [
      "Government-backed financial stability",
      "Nationwide acceptance at public and private hospitals",
      "Low contribution rates for civil servants",
      "Covers dependants comprehensively",
    ],
    cons: [
      "Benefits primarily for civil servants",
      "Reimbursement delays reported",
      "Digital services underdeveloped",
    ],
    affiliateUrl: "#",
    description:
      "CNOPS is the mandatory health insurance fund for Moroccan civil servants. The Inaya Complementary Health plan supplements the mandatory AMO base coverage, covering co-payments and extending benefits for government employees and their families.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "CNOPS Inaya is the cornerstone of Moroccan civil servant health coverage, providing essential complementary benefits to the mandatory AMO system.",
    editorialSource: "Morocco Healthcare Financing Assessment 2025",
  },
  {
    id: "ma-saham-assurance",
    name: "Saham Assurance Santé Premium",
    provider: "Saham Assurance",
    country: "Morocco",
    countryCode: "ma",
    logo: "/logos/saham-assurance.svg",
    rating: 4.1,
    reviewCount: 3560,
    monthlyPremium: "MAD 500 - MAD 1,400",
    deductible: "MAD 150 - MAD 600",
    coverageType: "premium",
    badges: ["Best Private Option", "Top Rated"],
    highlights: [
      "Morocco's leading private health insurer",
      "Comprehensive dental and optical benefits",
      "Access to top Casablanca and Rabat private clinics",
    ],
    pros: [
      "Widest private hospital network in Morocco",
      "Strong dental and optical inclusion",
      "Good maternity package",
    ],
    cons: [
      "Premiums high for lower-income households",
      "International coverage limited",
      "Mental health barely covered",
    ],
    affiliateUrl: "#",
    description:
      "Saham Assurance is Morocco's leading private insurance company. The Santé Premium plan provides comprehensive private health coverage for Moroccan professionals and families, with access to the country's best private clinics in major cities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Saham Assurance Santé Premium is the definitive choice for Moroccan professionals seeking comprehensive private health coverage with strong dental and optical benefits.",
    editorialSource: "Morocco Private Insurance Rankings 2025",
  },

  // Tunisia (TND)
  {
    id: "tn-cnrps",
    name: "CNRPS Health Insurance Essential",
    provider: "Caisse Nationale de Retraite et de Prévoyance Sociale (CNRPS)",
    country: "Tunisia",
    countryCode: "tn",
    logo: "/logos/cnrps.svg",
    rating: 3.7,
    reviewCount: 2840,
    monthlyPremium: "TND 45 - TND 130",
    deductible: "TND 10 - TND 50",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "Mandatory social health coverage for Tunisian employees",
      "Nationwide acceptance at public healthcare facilities",
      "Affordable contribution structure for formal workers",
    ],
    pros: [
      "Mandatory and universally accepted",
      "Low contribution cost",
      "Covers primary and hospital care nationwide",
    ],
    cons: [
      "Limited to public facilities primarily",
      "Long wait times at public hospitals",
      "No private clinic access in base plan",
    ],
    affiliateUrl: "#",
    description:
      "CNRPS manages social insurance for Tunisia's public sector workers. The Health Insurance Essential plan provides foundational medical coverage for government employees and their families through the national healthcare network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "CNRPS provides the essential health insurance foundation for Tunisia's public sector workforce, though private supplemental plans are increasingly sought to bridge coverage gaps.",
    editorialSource: "Tunisia Social Protection Review 2025",
  },
  {
    id: "tn-gat-assurance",
    name: "GAT Assurance Santé Plus",
    provider: "GAT Assurance",
    country: "Tunisia",
    countryCode: "tn",
    logo: "/logos/gat-assurance.svg",
    rating: 4.0,
    reviewCount: 1980,
    monthlyPremium: "TND 70 - TND 200",
    deductible: "TND 15 - TND 70",
    coverageType: "standard",
    badges: ["Best Private Option"],
    highlights: [
      "Tunisia's largest private health insurer",
      "Access to private clinics and specialist care in Tunis",
      "Dental and optical add-ons available",
    ],
    pros: [
      "Widest private provider panel in Tunisia",
      "Responsive customer service",
      "Good maternity and newborn coverage",
    ],
    cons: [
      "International coverage limited to emergency",
      "Mental health not covered",
      "Digital tools limited",
    ],
    affiliateUrl: "#",
    description:
      "GAT Assurance is Tunisia's leading private insurance company. The Santé Plus plan supplements mandatory social coverage by providing access to private clinics, specialists, and dental care for Tunisian professionals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "GAT Assurance Santé Plus is Tunisia's premier private health supplement, bridging the gap between public provision and professional healthcare expectations.",
    editorialSource: "Tunisia Insurance Market Report 2025",
  },

  // Ghana (GHS)
  {
    id: "gh-nhia-ghana",
    name: "Ghana NHIA Active Membership",
    provider: "National Health Insurance Authority Ghana",
    country: "Ghana",
    countryCode: "gh",
    logo: "/logos/nhia-ghana.svg",
    rating: 3.6,
    reviewCount: 8920,
    monthlyPremium: "GHS 60 - GHS 180",
    deductible: "GHS 0 - GHS 50",
    coverageType: "basic",
    badges: ["Government-Backed", "Most Accessible"],
    highlights: [
      "Ghana's national health insurance with broad population coverage",
      "Free at point of use for most services",
      "Covers maternity care and essential medicines",
    ],
    pros: [
      "Affordable nationwide coverage",
      "Free maternity services at accredited facilities",
      "Covers essential medicines on NHIA list",
      "Accepted at public and accredited private facilities",
    ],
    cons: [
      "Limited to essential services list",
      "Private hospital network patchy outside Accra",
      "Renewal and registration processes can be slow",
    ],
    affiliateUrl: "#",
    description:
      "Ghana's National Health Insurance Authority operates the country's social health insurance scheme. The Active Membership plan provides broad basic coverage at accredited facilities across Ghana's ten regions, with free maternity services included.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Ghana's NHIA is sub-Saharan Africa's most cited health insurance success story, achieving near-universal coverage of the population at very low cost.",
    editorialSource: "Africa Health Insurance Performance Index 2025",
  },
  {
    id: "gh-enterprise-health",
    name: "Enterprise Insurance Health Plus",
    provider: "Enterprise Insurance Company Ghana",
    country: "Ghana",
    countryCode: "gh",
    logo: "/logos/enterprise-ghana.svg",
    rating: 4.1,
    reviewCount: 3240,
    monthlyPremium: "GHS 250 - GHS 700",
    deductible: "GHS 50 - GHS 200",
    coverageType: "premium",
    badges: ["Best Private Option", "Top Rated"],
    highlights: [
      "Ghana's largest private health insurer",
      "Access to top Accra and Kumasi private hospitals",
      "Comprehensive group and individual plans",
    ],
    pros: [
      "Wide private hospital panel in Ghana",
      "Strong corporate group plan offerings",
      "Good customer service track record",
    ],
    cons: [
      "Significantly pricier than NHIA",
      "International coverage not standard",
      "Network thinner in northern regions",
    ],
    affiliateUrl: "#",
    description:
      "Enterprise Insurance Company is Ghana's largest private insurer. The Health Plus plan provides comprehensive private health coverage for Ghanaian professionals and businesses seeking care beyond the NHIA network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Enterprise Insurance Health Plus is the gold standard for private health coverage in Ghana, offering access to the country's best private medical facilities.",
    editorialSource: "Ghana Financial Services Insurance Ranking 2025",
  },

  // Ethiopia (ETB)
  {
    id: "et-nyala-insurance",
    name: "Nyala Insurance Health Package",
    provider: "Nyala Insurance Share Company",
    country: "Ethiopia",
    countryCode: "et",
    logo: "/logos/nyala-insurance.svg",
    rating: 3.7,
    reviewCount: 1830,
    monthlyPremium: "ETB 1,200 - ETB 4,000",
    deductible: "ETB 300 - ETB 1,200",
    coverageType: "standard",
    badges: ["Most Popular"],
    highlights: [
      "One of Ethiopia's largest private insurers",
      "Covers treatment at major Addis Ababa private hospitals",
      "Group plans available for Ethiopian businesses",
    ],
    pros: [
      "Wide acceptance at Addis Ababa private clinics",
      "Affordable relative to Ethiopian income levels",
      "Good group plan pricing for SMEs",
    ],
    cons: [
      "Network very limited outside Addis Ababa",
      "No international coverage",
      "Digital tools not available",
    ],
    affiliateUrl: "#",
    description:
      "Nyala Insurance Share Company is one of Ethiopia's largest private insurance companies. The Health Package provides corporate and individual health coverage primarily for Addis Ababa-based clients with access to the capital's growing private hospital sector.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Nyala Insurance is the go-to private health insurer for Ethiopian businesses in Addis Ababa, offering practical coverage for a growing professional workforce.",
    editorialSource: "Ethiopian Insurance Sector Review 2025",
  },
  {
    id: "et-awash-insurance",
    name: "Awash Insurance Health Care",
    provider: "Awash Insurance Company",
    country: "Ethiopia",
    countryCode: "et",
    logo: "/logos/awash-insurance.svg",
    rating: 3.8,
    reviewCount: 1420,
    monthlyPremium: "ETB 900 - ETB 3,000",
    deductible: "ETB 200 - ETB 800",
    coverageType: "basic",
    badges: ["Best Value"],
    highlights: [
      "Competitive premiums for Ethiopian market",
      "Solid Addis Ababa hospital and clinic network",
      "Active corporate group health plan",
    ],
    pros: [
      "Very competitive premiums",
      "Reliable brand with strong local reputation",
      "Simple claims process",
    ],
    cons: [
      "Coverage primarily Addis Ababa-centric",
      "No maternity in base plan",
      "No digital self-service tools",
    ],
    affiliateUrl: "#",
    description:
      "Awash Insurance Company is a prominent Ethiopian private insurer. The Health Care plan offers basic-to-standard coverage for Addis Ababa residents and corporate clients seeking affordable private health protection.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Awash Insurance Health Care is a reliable, budget-friendly option for Ethiopian businesses and professionals seeking essential private health coverage.",
    editorialSource: "Ethiopia Private Sector Insurance Market 2025",
  },

  // Tanzania (TZS)
  {
    id: "tz-jubilee-tanzania",
    name: "Jubilee Insurance Tanzania Health",
    provider: "Jubilee Insurance Tanzania",
    country: "Tanzania",
    countryCode: "tz",
    logo: "/logos/jubilee-tanzania.svg",
    rating: 4.1,
    reviewCount: 2760,
    monthlyPremium: "TZS 120,000 - TZS 400,000",
    deductible: "TZS 25,000 - TZS 100,000",
    coverageType: "premium",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "East Africa's Jubilee brand with strong Tanzanian presence",
      "Covers Dar es Salaam's leading private hospitals",
      "Includes medical evacuation to Nairobi or South Africa",
    ],
    pros: [
      "Regional insurer with financial strength",
      "Medical evacuation coverage",
      "Comprehensive maternity benefits",
      "Good private hospital network in Dar es Salaam",
    ],
    cons: [
      "Network limited outside major cities",
      "Dental and optical sold as add-ons",
      "International coverage limited to evacuation",
    ],
    affiliateUrl: "#",
    description:
      "Jubilee Insurance Tanzania is part of the East Africa-wide Jubilee Group. The Health plan provides comprehensive private coverage for Tanzanian residents with a focus on Dar es Salaam's growing private hospital sector and medical evacuation capability.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Jubilee Insurance Tanzania is the leading private health insurer in the country, valued for its evacuation coverage and Dar es Salaam hospital network.",
    editorialSource: "East Africa Insurance Review 2025",
  },
  {
    id: "tz-nhif-tanzania",
    name: "NHIF Tanzania Comprehensive",
    provider: "National Health Insurance Fund (NHIF) Tanzania",
    country: "Tanzania",
    countryCode: "tz",
    logo: "/logos/nhif-tanzania.svg",
    rating: 3.5,
    reviewCount: 5820,
    monthlyPremium: "TZS 50,000 - TZS 150,000",
    deductible: "TZS 5,000 - TZS 30,000",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "Mandatory scheme for Tanzanian formal sector employees",
      "Covers government and mission hospital network",
      "Includes maternity and paediatric care",
    ],
    pros: [
      "Very low contributions",
      "Government-backed stability",
      "Wide public hospital acceptance",
    ],
    cons: [
      "Quality of care at public facilities varies widely",
      "Private hospital access requires top-up",
      "Limited outpatient services",
    ],
    affiliateUrl: "#",
    description:
      "Tanzania's National Health Insurance Fund provides mandatory social health insurance for formal sector employees. The Comprehensive plan offers access to public and accredited private healthcare providers across mainland Tanzania and Zanzibar.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "NHIF Tanzania provides the essential foundation of health coverage for Tanzanian formal sector workers, though most opt for private supplements for better care access.",
    editorialSource: "Tanzania Health Sector Financing Report 2025",
  },

  // Rwanda (RWF)
  {
    id: "rw-mutuelle-sante",
    name: "Mutuelle de Santé Community Health",
    provider: "Rwanda Social Security Board (RSSB) – Mutuelle de Santé",
    country: "Rwanda",
    countryCode: "rw",
    logo: "/logos/mutuelle-rw.svg",
    rating: 4.0,
    reviewCount: 7240,
    monthlyPremium: "RWF 3,000 - RWF 10,000",
    deductible: "RWF 500 - RWF 2,000",
    coverageType: "basic",
    badges: ["Government-Backed", "Most Accessible"],
    highlights: [
      "Rwanda's community-based health insurance covering 90%+ of population",
      "Tiered premium based on income level",
      "Covers primary care and hospital referrals",
    ],
    pros: [
      "Near-universal population coverage",
      "Income-tiered premiums ensure affordability",
      "Covers primary, secondary, and tertiary care referrals",
      "Recognised globally as an African healthcare success story",
    ],
    cons: [
      "Benefit package limited compared to private plans",
      "Co-payment required at point of service",
      "Private hospital access restricted",
    ],
    affiliateUrl: "#",
    description:
      "Mutuelle de Santé is Rwanda's community-based health insurance scheme administered by the Rwanda Social Security Board. It is one of Africa's most successful universal health coverage initiatives, covering over 90% of Rwanda's population with tiered, income-adjusted premiums.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Rwanda's Mutuelle de Santé is Africa's most celebrated health insurance model, achieving near-universal coverage through a community-based, income-tiered approach.",
    editorialSource: "WHO Rwanda Health Financing Report 2025",
  },
  {
    id: "rw-radiant-insurance",
    name: "Radiant Insurance Rwanda Health Premium",
    provider: "Radiant Insurance Company",
    country: "Rwanda",
    countryCode: "rw",
    logo: "/logos/radiant-rw.svg",
    rating: 4.1,
    reviewCount: 1540,
    monthlyPremium: "RWF 25,000 - RWF 80,000",
    deductible: "RWF 5,000 - RWF 20,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "Rwanda's leading private health insurer",
      "Access to King Faisal Hospital and top Kigali clinics",
      "International medical evacuation included",
    ],
    pros: [
      "Best private hospital access in Rwanda",
      "International evacuation coverage",
      "Good maternity benefits",
    ],
    cons: [
      "High cost relative to Rwandan income levels",
      "Network concentrated in Kigali",
      "No telehealth platform",
    ],
    affiliateUrl: "#",
    description:
      "Radiant Insurance Company is Rwanda's leading private insurer. The Health Premium plan provides comprehensive private health coverage for Rwanda's growing professional class, NGO workers, and expatriates, including access to Kigali's top-tier private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Radiant Insurance Rwanda is the preferred private health insurer for Kigali's expatriate and professional community seeking care beyond the public Mutuelle system.",
    editorialSource: "East Africa Private Insurance Market Survey 2025",
  },

  // Uganda (UGX)
  {
    id: "ug-jubilee-uganda",
    name: "Jubilee Insurance Uganda MediCare",
    provider: "Jubilee Insurance Uganda",
    country: "Uganda",
    countryCode: "ug",
    logo: "/logos/jubilee-uganda.svg",
    rating: 4.2,
    reviewCount: 2840,
    monthlyPremium: "UGX 200,000 - UGX 650,000",
    deductible: "UGX 50,000 - UGX 150,000",
    coverageType: "premium",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Uganda's leading private health insurer",
      "Covers International Hospital Kampala and top private facilities",
      "Medical evacuation to Nairobi included",
    ],
    pros: [
      "Uganda's widest private hospital panel",
      "Medical evacuation coverage",
      "Strong maternity and newborn benefits",
      "Good customer service",
    ],
    cons: [
      "Network thin outside Kampala",
      "Dental covered as add-on",
      "International coverage limited to evacuation",
    ],
    affiliateUrl: "#",
    description:
      "Jubilee Insurance Uganda is part of the Jubilee Group operating across East Africa. The MediCare plan provides comprehensive private health coverage for Ugandan professionals and expatriates with access to Kampala's best private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Jubilee Uganda MediCare is the market-leading private health plan in Uganda, trusted by corporates and expatriates for its Kampala hospital network and evacuation coverage.",
    editorialSource: "Uganda Insurance Commission Market Report 2025",
  },
  {
    id: "ug-aon-uganda",
    name: "AON Uganda Corporate Health",
    provider: "AON Uganda",
    country: "Uganda",
    countryCode: "ug",
    logo: "/logos/aon-uganda.svg",
    rating: 4.0,
    reviewCount: 1620,
    monthlyPremium: "UGX 150,000 - UGX 500,000",
    deductible: "UGX 30,000 - UGX 100,000",
    coverageType: "standard",
    badges: ["Best for Corporates"],
    highlights: [
      "Global AON brokerage expertise tailored for Uganda",
      "Strong corporate group plan portfolio",
      "Access to international plans for NGO staff",
    ],
    pros: [
      "Global brokerage expertise",
      "Flexible benefit design for corporates",
      "International plan access for NGO employees",
    ],
    cons: [
      "Better suited to groups than individuals",
      "Local digital tools limited",
      "International access adds cost",
    ],
    affiliateUrl: "#",
    description:
      "AON Uganda operates as an insurance broker offering corporate health plan solutions. The Corporate Health package leverages AON's global expertise to design flexible group health benefits for Ugandan businesses and international NGOs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "AON Uganda brings global insurance brokerage expertise to Ugandan corporate health plan design, particularly valuable for NGOs requiring international coverage flexibility.",
    editorialSource: "Uganda Corporate Benefits Survey 2025",
  },

  // Senegal (XOF)
  {
    id: "sn-ipres-health",
    name: "IPRES Retraite Health Coverage",
    provider: "Institution de Prévoyance Retraite du Sénégal (IPRES)",
    country: "Senegal",
    countryCode: "sn",
    logo: "/logos/ipres-senegal.svg",
    rating: 3.6,
    reviewCount: 1830,
    monthlyPremium: "XOF 15,000 - XOF 45,000",
    deductible: "XOF 3,000 - XOF 12,000",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "Mandatory scheme for Senegalese private sector formal employees",
      "Hospital and clinical care at accredited facilities in Dakar",
      "Maternity benefits included",
    ],
    pros: [
      "Government-managed reliability",
      "Covers formal sector employees and dependants",
      "Low contribution rates",
    ],
    cons: [
      "Limited network outside Dakar",
      "Benefit package modest",
      "Long reimbursement timelines",
    ],
    affiliateUrl: "#",
    description:
      "IPRES is one of Senegal's main social protection institutions. The Health Coverage component provides mandatory health benefits for private sector formal employees in Senegal, covering essential medical care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "IPRES provides the mandatory health insurance backbone for Senegal's formal private sector, with coverage that is reliable if modest in scope.",
    editorialSource: "Senegal Social Protection Assessment 2025",
  },
  {
    id: "sn-allianz-senegal",
    name: "Allianz Senegal Santé Plus",
    provider: "Allianz Sénégal",
    country: "Senegal",
    countryCode: "sn",
    logo: "/logos/allianz-senegal.svg",
    rating: 4.0,
    reviewCount: 1240,
    monthlyPremium: "XOF 30,000 - XOF 90,000",
    deductible: "XOF 5,000 - XOF 20,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "International Allianz backing in West African market",
      "Best Dakar private clinic network",
      "Comprehensive maternity package",
    ],
    pros: [
      "International insurer credibility",
      "Strong Dakar private hospital network",
      "Comprehensive maternity benefits",
    ],
    cons: [
      "Premiums high for Senegalese market",
      "Network concentrated in Dakar",
      "No telehealth services",
    ],
    affiliateUrl: "#",
    description:
      "Allianz Sénégal is the leading private insurer in Senegal, backed by the global Allianz Group. The Santé Plus plan provides comprehensive private health coverage for Dakar-based professionals, expatriates, and corporate clients.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Allianz Sénégal Santé Plus is the premium choice for Dakar's professional and expatriate community seeking comprehensive private health coverage.",
    editorialSource: "West Africa Insurance Market Report 2025",
  },

  // Ivory Coast / Côte d'Ivoire (XOF)
  {
    id: "ci-snedai",
    name: "SNEDAI Individual Health Plan",
    provider: "SNEDAI (Société Nationale d'Édition et de Diffusion Assurances)",
    country: "Ivory Coast",
    countryCode: "ci",
    logo: "/logos/snedai.svg",
    rating: 3.7,
    reviewCount: 1420,
    monthlyPremium: "XOF 20,000 - XOF 65,000",
    deductible: "XOF 4,000 - XOF 15,000",
    coverageType: "standard",
    badges: ["Local Leader"],
    highlights: [
      "Strong presence in Abidjan's private healthcare sector",
      "Covers treatment at leading Abidjan clinics",
      "Affordable group plans for local businesses",
    ],
    pros: [
      "Well-established local insurer",
      "Good Abidjan clinic and hospital network",
      "Affordable group pricing for SMEs",
    ],
    cons: [
      "Limited outside Abidjan",
      "No international coverage",
      "Minimal digital capabilities",
    ],
    affiliateUrl: "#",
    description:
      "SNEDAI is one of Côte d'Ivoire's established insurance companies with a focus on individual and group health plans. The Individual Health Plan provides standard coverage for Abidjan-based professionals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "SNEDAI is a trusted local option for Ivory Coast residents seeking private health coverage beyond the public health system in Abidjan.",
    editorialSource: "Côte d'Ivoire Insurance Market Review 2025",
  },
  {
    id: "ci-nsia-assurance",
    name: "NSIA Assurance Santé Gold",
    provider: "NSIA Assurances Côte d'Ivoire",
    country: "Ivory Coast",
    countryCode: "ci",
    logo: "/logos/nsia-assurance.svg",
    rating: 4.0,
    reviewCount: 2210,
    monthlyPremium: "XOF 35,000 - XOF 100,000",
    deductible: "XOF 6,000 - XOF 22,000",
    coverageType: "premium",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Pan-African NSIA Group backing across 10 countries",
      "Comprehensive Abidjan private hospital and clinic access",
      "Strong corporate group plan capabilities",
    ],
    pros: [
      "Pan-African insurer with regional scale",
      "Best private hospital network in Abidjan",
      "Solid corporate plan portfolio",
      "Teleconsultation available in premium tiers",
    ],
    cons: [
      "International coverage limited to evacuation",
      "Higher premiums than local competitors",
      "Mental health benefits not covered",
    ],
    affiliateUrl: "#",
    description:
      "NSIA Assurances is part of the NSIA Group, one of West and Central Africa's leading insurance groups. The Santé Gold plan provides comprehensive private health coverage in Côte d'Ivoire for professionals and corporate clients.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "NSIA Assurance Santé Gold is the standout corporate health plan in Côte d'Ivoire, backed by NSIA's pan-African scale and professional-grade benefits.",
    editorialSource: "Francophone Africa Insurance Awards 2025",
  },

  // Cameroon (XAF)
  {
    id: "cm-activa-assurance",
    name: "Activa Assurance Cameroun Health",
    provider: "Activa Assurance Cameroun",
    country: "Cameroon",
    countryCode: "cm",
    logo: "/logos/activa-cameroon.svg",
    rating: 4.0,
    reviewCount: 1850,
    monthlyPremium: "XAF 25,000 - XAF 80,000",
    deductible: "XAF 5,000 - XAF 20,000",
    coverageType: "standard",
    badges: ["Most Popular", "Local Leader"],
    highlights: [
      "Cameroon's leading private insurer with 30+ years of history",
      "Network covers Yaoundé and Douala private hospitals",
      "Group and individual plans for employees and families",
    ],
    pros: [
      "Long-established market leader",
      "Good capital-city hospital networks",
      "Competitive group plan pricing",
    ],
    cons: [
      "Coverage limited outside Yaoundé and Douala",
      "No telehealth services",
      "International coverage not offered",
    ],
    affiliateUrl: "#",
    description:
      "Activa Assurance Cameroun is one of Central Africa's most established insurance companies. The Health plan provides standard private health coverage for Cameroonians in major cities and corporate employees.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Activa Assurance is Cameroon's most trusted private health insurer, with decades of market leadership and a solid urban hospital network.",
    editorialSource: "Central Africa Insurance Market Report 2025",
  },
  {
    id: "cm-nsia-cameroun",
    name: "NSIA Cameroun Santé Plus",
    provider: "NSIA Cameroun",
    country: "Cameroon",
    countryCode: "cm",
    logo: "/logos/nsia-cameroun.svg",
    rating: 3.9,
    reviewCount: 1120,
    monthlyPremium: "XAF 18,000 - XAF 60,000",
    deductible: "XAF 4,000 - XAF 16,000",
    coverageType: "basic",
    badges: ["Best Value"],
    highlights: [
      "Pan-African NSIA Group coverage in Cameroon",
      "Affordable individual and family plans",
      "Coverage at accredited Yaoundé and Douala facilities",
    ],
    pros: [
      "Pan-African group backing",
      "Affordable entry-level plans",
      "Simple and transparent plan structure",
    ],
    cons: [
      "Network limited to major cities",
      "No dental or optical",
      "Claims process primarily paper-based",
    ],
    affiliateUrl: "#",
    description:
      "NSIA Cameroun is part of the NSIA Group operating across West and Central Africa. The Santé Plus plan offers affordable basic-to-standard health coverage for Cameroonian residents and employees in Yaoundé and Douala.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "NSIA Cameroun Santé Plus is a reliable, budget-friendly health insurance option for Cameroonians seeking basic private coverage in the country's main urban centres.",
    editorialSource: "Central Africa Health Insurance Consumer Survey 2025",
  },

  // Algeria (DZD)
  {
    id: "dz-caar-algeria",
    name: "CAAR Algeria Health Complementary",
    provider: "Compagnie Algérienne d'Assurance et de Réassurance (CAAR)",
    country: "Algeria",
    countryCode: "dz",
    logo: "/logos/caar-algeria.svg",
    rating: 3.8,
    reviewCount: 3420,
    monthlyPremium: "DZD 5,000 - DZD 15,000",
    deductible: "DZD 1,000 - DZD 4,000",
    coverageType: "standard",
    badges: ["Government-Backed", "Most Popular"],
    highlights: [
      "Algeria's oldest and largest state-owned insurer",
      "Complementary coverage for CNAS social insurance members",
      "Wide acceptance at public and private hospitals across Algeria",
    ],
    pros: [
      "State-backed financial reliability",
      "Nationwide hospital acceptance",
      "Affordable premiums for complementary top-up",
    ],
    cons: [
      "Limited benefits beyond complementary role",
      "No international coverage",
      "Digital services underdeveloped",
    ],
    affiliateUrl: "#",
    description:
      "CAAR is Algeria's oldest and largest insurance company, state-owned since independence. The Health Complementary plan provides a top-up layer above Algeria's mandatory CNAS social health insurance, covering co-payments and specialist access.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "CAAR Health Complementary is Algeria's leading supplemental plan, providing millions of Algerians with financial protection beyond the mandatory CNAS coverage.",
    editorialSource: "Algeria Insurance Market Report 2025",
  },
  {
    id: "dz-trust-algeria",
    name: "Trust Algeria Health Premium",
    provider: "Trust Algeria Assurance",
    country: "Algeria",
    countryCode: "dz",
    logo: "/logos/trust-algeria.svg",
    rating: 3.9,
    reviewCount: 1820,
    monthlyPremium: "DZD 7,000 - DZD 22,000",
    deductible: "DZD 1,500 - DZD 6,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "Private Algerian insurer with growing market share",
      "Access to premium private clinics in Algiers",
      "Dental and optical add-ons available",
    ],
    pros: [
      "Best private hospital access in Algiers",
      "Dental and optical available",
      "Good corporate group plan terms",
    ],
    cons: [
      "Network concentrated in Algiers region",
      "No telehealth services",
      "International coverage not offered",
    ],
    affiliateUrl: "#",
    description:
      "Trust Algeria Assurance is one of Algeria's growing private insurance companies. The Health Premium plan provides comprehensive private health coverage for Algiers-based professionals and businesses seeking care at top private clinics.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Trust Algeria Health Premium is the leading private option in Algeria for professionals seeking premium private clinic access beyond the public health system.",
    editorialSource: "Algeria Private Sector Insurance Update 2025",
  },

  // Libya (LYD)
  {
    id: "ly-libyan-insurance",
    name: "Libyan Insurance Company Health Plan",
    provider: "Libyan Insurance Company",
    country: "Libya",
    countryCode: "ly",
    logo: "/logos/libyan-insurance.svg",
    rating: 3.5,
    reviewCount: 642,
    monthlyPremium: "LYD 60 - LYD 180",
    deductible: "LYD 10 - LYD 50",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "State-owned insurer operating in accessible Libyan cities",
      "Covers treatment at Tripoli and Benghazi private hospitals",
      "Low-cost plan for formal sector employees",
    ],
    pros: [
      "Government-backed operations despite instability",
      "Affordable premiums",
      "Accepted at major urban hospitals",
    ],
    cons: [
      "Operations severely impacted by conflict",
      "Coverage highly limited by security situation",
      "No digital infrastructure",
    ],
    affiliateUrl: "#",
    description:
      "Libyan Insurance Company is the main state-owned insurer in Libya, operating primarily in government-controlled areas. The Health Plan provides basic coverage at functional private and public hospitals in Tripoli and Benghazi.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Libyan Insurance Company operates the only viable formal health insurance in Libya, providing limited but functioning coverage in the country's challenging environment.",
    editorialSource: "MENA Frontier Markets Insurance Report 2025",
  },
  {
    id: "ly-al-jomhouria-insurance",
    name: "Al Jomhouria Insurance Libya Health",
    provider: "Al Jomhouria Insurance Company",
    country: "Libya",
    countryCode: "ly",
    logo: "/logos/al-jomhouria.svg",
    rating: 3.6,
    reviewCount: 408,
    monthlyPremium: "LYD 45 - LYD 140",
    deductible: "LYD 8 - LYD 40",
    coverageType: "basic",
    badges: ["Local Option"],
    highlights: [
      "Private Libyan insurer with Tripoli hospital access",
      "USD-indexed premiums for stability",
      "Corporate plan for oil sector employees",
    ],
    pros: [
      "USD payment option",
      "Oil sector corporate plan specialist",
      "Private hospital access in Tripoli",
    ],
    cons: [
      "Very limited geographic coverage",
      "No telehealth or digital services",
      "Claims settlement depends on security situation",
    ],
    affiliateUrl: "#",
    description:
      "Al Jomhouria Insurance Company is a private Libyan insurer focusing on urban markets. The Health plan is particularly used by the oil and gas sector for employee benefits, with USD-indexed premium options for stability.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Al Jomhouria is one of the few private health insurance options in Libya, serving the oil sector with USD-linked plans that maintain value despite currency volatility.",
    editorialSource: "Libya Energy Sector Insurance Review 2025",
  },

  // Mozambique (MZN)
  {
    id: "mz-emose",
    name: "EMOSE Mozambique Health Insurance",
    provider: "Empresa Moçambicana de Seguros (EMOSE)",
    country: "Mozambique",
    countryCode: "mz",
    logo: "/logos/emose.svg",
    rating: 3.7,
    reviewCount: 980,
    monthlyPremium: "MZN 1,500 - MZN 5,000",
    deductible: "MZN 300 - MZN 1,000",
    coverageType: "standard",
    badges: ["Market Leader"],
    highlights: [
      "Mozambique's largest insurer with state-owned origins",
      "Covers Maputo's private and public hospital network",
      "Corporate plans for mining and energy sector clients",
    ],
    pros: [
      "Dominant market presence and financial stability",
      "Good Maputo hospital network",
      "Corporate plan expertise for large employers",
    ],
    cons: [
      "Network very limited outside Maputo",
      "No international coverage",
      "Minimal digital tools",
    ],
    affiliateUrl: "#",
    description:
      "EMOSE is Mozambique's largest insurance company with state-owned origins, now partially privatised. The Health Insurance plan provides essential coverage for Mozambican employees and corporate clients in Maputo and accessible provincial centres.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "EMOSE is Mozambique's dominant health insurer, providing the most reliable private coverage for the country's growing formal sector workforce.",
    editorialSource: "Southern Africa Insurance Market Review 2025",
  },
  {
    id: "mz-britam-mozambique",
    name: "Britam Mozambique Health Plus",
    provider: "Britam Insurance Mozambique",
    country: "Mozambique",
    countryCode: "mz",
    logo: "/logos/britam-mozambique.svg",
    rating: 3.9,
    reviewCount: 640,
    monthlyPremium: "MZN 2,500 - MZN 7,500",
    deductible: "MZN 500 - MZN 2,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "Pan-African Britam Group coverage in Mozambique",
      "Best Maputo private clinic access",
      "International medical evacuation included",
    ],
    pros: [
      "Pan-African insurer reliability",
      "International evacuation included",
      "Best private facility access in Maputo",
    ],
    cons: [
      "Higher premiums than local competitors",
      "Network limited to Maputo",
      "No telehealth services",
    ],
    affiliateUrl: "#",
    description:
      "Britam Insurance operates in Mozambique as part of its pan-African presence. The Health Plus plan provides comprehensive private coverage for Mozambican professionals and expatriates, including medical evacuation to South Africa.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Britam Mozambique Health Plus is the top choice for expatriates and senior executives in Maputo seeking comprehensive private coverage with international evacuation.",
    editorialSource: "Mozambique Expatriate Benefits Survey 2025",
  },

  // Zimbabwe (ZWL)
  {
    id: "zw-cimas",
    name: "CIMAS Medical Aid Premier",
    provider: "CIMAS Medical Aid Society",
    country: "Zimbabwe",
    countryCode: "zw",
    logo: "/logos/cimas-zimbabwe.svg",
    rating: 4.2,
    reviewCount: 3840,
    monthlyPremium: "ZWL 150,000 - ZWL 450,000",
    deductible: "ZWL 20,000 - ZWL 80,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Zimbabwe's largest medical aid society",
      "Covers Harare's best private hospitals including Parirenyatwa",
      "Dental and optical included in Premier plan",
    ],
    pros: [
      "Largest member base and hospital network in Zimbabwe",
      "Dental and optical coverage included",
      "Strong chronic disease management",
      "USD payment option available",
    ],
    cons: [
      "Currency volatility affects premium stability",
      "International coverage limited",
      "Network outside Harare and Bulawayo is thin",
    ],
    affiliateUrl: "#",
    description:
      "CIMAS Medical Aid Society is Zimbabwe's largest medical aid provider, serving members across the country for decades. The Premier plan offers the most comprehensive benefits available in Zimbabwe's private medical sector.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "CIMAS Premier is Zimbabwe's gold-standard medical aid plan, offering the widest benefits and largest hospital network in the country's private health sector.",
    editorialSource: "Zimbabwe Medical Aid Market Report 2025",
  },
  {
    id: "zw-first-mutual-health",
    name: "First Mutual Health MedGold",
    provider: "First Mutual Health (Zimbabwe)",
    country: "Zimbabwe",
    countryCode: "zw",
    logo: "/logos/first-mutual-zw.svg",
    rating: 4.0,
    reviewCount: 2410,
    monthlyPremium: "ZWL 100,000 - ZWL 320,000",
    deductible: "ZWL 15,000 - ZWL 60,000",
    coverageType: "premium",
    badges: ["Best Value"],
    highlights: [
      "Zimbabwe's second-largest medical aid society",
      "Competitive premiums with solid Harare hospital access",
      "USD-denominated option available for stability",
    ],
    pros: [
      "Solid Harare and Bulawayo private hospital panel",
      "USD payment option",
      "Competitive premiums for level of coverage",
    ],
    cons: [
      "Network smaller than CIMAS nationally",
      "No telehealth services",
      "Dental requires additional contribution",
    ],
    affiliateUrl: "#",
    description:
      "First Mutual Health is Zimbabwe's second-largest medical aid society, part of the First Mutual Holdings group. The MedGold plan provides comprehensive inpatient and outpatient coverage for Zimbabwe's growing professional class.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "First Mutual Health MedGold is a strong value alternative to CIMAS in Zimbabwe, offering solid coverage at competitive premiums for individuals and corporate groups.",
    editorialSource: "Zimbabwe Consumer Financial Services Survey 2025",
  },

  // Botswana (BWP)
  {
    id: "bw-bpomas",
    name: "BPOMAS Premier Medical Aid",
    provider: "Botswana Public Officers Medical Aid Scheme (BPOMAS)",
    country: "Botswana",
    countryCode: "bw",
    logo: "/logos/bpomas.svg",
    rating: 4.1,
    reviewCount: 2140,
    monthlyPremium: "BWP 800 - BWP 2,200",
    deductible: "BWP 100 - BWP 500",
    coverageType: "comprehensive",
    badges: ["Government-Backed", "Most Popular"],
    highlights: [
      "Botswana's largest medical aid society for public officers",
      "Covers Princess Marina and Gaborone Private Hospital",
      "Comprehensive dental and optical benefits",
    ],
    pros: [
      "Comprehensive benefits including dental and optical",
      "Strong Gaborone hospital network",
      "Government employee preferred scheme",
      "Medical evacuation to South Africa included",
    ],
    cons: [
      "Primarily for public sector employees",
      "International coverage limited to evacuation",
      "Premiums increase significantly with family size",
    ],
    affiliateUrl: "#",
    description:
      "BPOMAS is Botswana's primary medical aid scheme for government and parastatal employees. The Premier plan provides comprehensive health benefits including dental, optical, and medical evacuation to South Africa.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "BPOMAS Premier is Botswana's most comprehensive medical aid, setting the standard for public sector health benefits in the country with full dental, optical, and evacuation coverage.",
    editorialSource: "Botswana Insurance Industry Report 2025",
  },
  {
    id: "bw-pula-medical",
    name: "Pula Medical Aid Standard",
    provider: "Pula Medical Aid Fund",
    country: "Botswana",
    countryCode: "bw",
    logo: "/logos/pula-medical.svg",
    rating: 3.9,
    reviewCount: 1560,
    monthlyPremium: "BWP 600 - BWP 1,600",
    deductible: "BWP 80 - BWP 350",
    coverageType: "standard",
    badges: ["Best for Private Sector"],
    highlights: [
      "Botswana's largest private sector medical aid",
      "Covers all major Gaborone and Francistown hospitals",
      "Straightforward plan design and claims process",
    ],
    pros: [
      "Most popular medical aid for private sector workers",
      "Simple claims process",
      "Good hospital network in Gaborone and Francistown",
    ],
    cons: [
      "Dental and optical sold as add-ons",
      "International coverage not included",
      "Digital tools need improvement",
    ],
    affiliateUrl: "#",
    description:
      "Pula Medical Aid Fund is Botswana's largest private sector medical aid scheme. The Standard plan provides solid inpatient and outpatient coverage for private sector employees across Botswana's main urban centres.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Pula Medical Aid Standard is the go-to medical aid for Botswana's private sector, offering reliable coverage at competitive premiums across the country's main cities.",
    editorialSource: "Botswana Consumer Insurance Guide 2025",
  },

  // Namibia (NAD)
  {
    id: "na-namdeb-medical",
    name: "NamSA Medical Aid Premier",
    provider: "Namibian Association of Medical Aid Funds (NAMAF) – NamSA Scheme",
    country: "Namibia",
    countryCode: "na",
    logo: "/logos/namsa.svg",
    rating: 4.0,
    reviewCount: 1720,
    monthlyPremium: "NAD 1,800 - NAD 5,000",
    deductible: "NAD 300 - NAD 1,200",
    coverageType: "comprehensive",
    badges: ["Most Popular"],
    highlights: [
      "Namibia's regulated medical aid framework",
      "Covers Windhoek Central Hospital and top private facilities",
      "Dental and optical included in Premier tier",
    ],
    pros: [
      "NAMAF-regulated ensuring plan standards",
      "Comprehensive benefits including dental and optical",
      "Good Windhoek private hospital network",
    ],
    cons: [
      "Network very limited outside Windhoek",
      "International coverage limited to evacuation",
      "Premiums high for smaller Namibian income levels",
    ],
    affiliateUrl: "#",
    description:
      "NamSA operates under the Namibian Association of Medical Aid Funds regulatory framework. The Premier plan provides comprehensive health coverage for Namibian employees and their families, including dental, optical, and emergency evacuation to South Africa.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "NamSA Premier is Namibia's leading regulated medical aid, providing comprehensive coverage in a market where NAMAF oversight ensures minimum benefit standards.",
    editorialSource: "Namibia Insurance Market Survey 2025",
  },
  {
    id: "na-old-mutual-namibia",
    name: "Old Mutual Namibia Health Plan",
    provider: "Old Mutual Namibia",
    country: "Namibia",
    countryCode: "na",
    logo: "/logos/old-mutual-namibia.svg",
    rating: 4.1,
    reviewCount: 2180,
    monthlyPremium: "NAD 2,200 - NAD 6,000",
    deductible: "NAD 400 - NAD 1,500",
    coverageType: "premium",
    badges: ["Editor's Choice"],
    highlights: [
      "Old Mutual's Namibian operation with regional scale",
      "Best Windhoek private hospital access",
      "International evacuation to South Africa covered",
    ],
    pros: [
      "Pan-African Old Mutual scale and financial strength",
      "Best Windhoek private hospital network",
      "International evacuation standard",
    ],
    cons: [
      "Higher premiums than local schemes",
      "Network outside Windhoek limited",
      "No telehealth services",
    ],
    affiliateUrl: "#",
    description:
      "Old Mutual Namibia is part of the pan-African Old Mutual financial services group. The Health Plan provides premium private health coverage for Namibian professionals and expatriates with access to Windhoek's best private medical facilities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Old Mutual Namibia Health Plan is the premium choice for Windhoek professionals seeking private health coverage with the backing of Africa's largest financial services group.",
    editorialSource: "Southern Africa Insurance Rankings 2025",
  },

  // Mauritius (MUR)
  {
    id: "mu-sun-insurance",
    name: "Sun Insurance Mauritius MediShield",
    provider: "Sun Insurance (Mauritius)",
    country: "Mauritius",
    countryCode: "mu",
    logo: "/logos/sun-insurance-mu.svg",
    rating: 4.3,
    reviewCount: 2840,
    monthlyPremium: "MUR 3,500 - MUR 9,000",
    deductible: "MUR 1,000 - MUR 4,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "One of Mauritius's leading private health insurers",
      "Access to Darné Clinic, C-DAC, and Apollo Bramwell Hospital",
      "Comprehensive dental, optical, and maternity",
    ],
    pros: [
      "Access to Mauritius's top private hospitals",
      "Comprehensive benefit package including dental and optical",
      "International treatment coverage for serious conditions",
      "Good digital health tools",
    ],
    cons: [
      "Higher premiums reflecting Mauritian private hospital costs",
      "Mental health sessions capped",
      "International coverage requires pre-approval",
    ],
    affiliateUrl: "#",
    description:
      "Sun Insurance is one of Mauritius's leading private health insurers. The MediShield plan provides comprehensive health coverage for Mauritian residents and expatriates with access to the island's premium private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Sun Insurance MediShield is Mauritius's most comprehensive private health plan, combining excellent local hospital access with international treatment coverage for complex cases.",
    editorialSource: "Mauritius Financial Services Insurance Report 2025",
  },
  {
    id: "mu-swan-insurance",
    name: "Swan Insurance Mauritius HealthCare",
    provider: "Swan Insurance Mauritius",
    country: "Mauritius",
    countryCode: "mu",
    logo: "/logos/swan-insurance-mu.svg",
    rating: 4.1,
    reviewCount: 2210,
    monthlyPremium: "MUR 2,800 - MUR 7,500",
    deductible: "MUR 800 - MUR 3,000",
    coverageType: "premium",
    badges: ["Top Rated", "Best Value"],
    highlights: [
      "Swan General Insurance Mauritius with 60-year history",
      "Wide access to Mauritius private clinics",
      "Good group corporate plan portfolio",
    ],
    pros: [
      "Long-established Mauritian insurer",
      "Comprehensive corporate group plans",
      "Good claims service track record",
    ],
    cons: [
      "International coverage limited in base plan",
      "Telehealth services limited",
      "Dental requires add-on contribution",
    ],
    affiliateUrl: "#",
    description:
      "Swan Insurance is a well-established Mauritian insurance company with over 60 years of operation. The HealthCare plan provides comprehensive private health coverage for individuals and businesses in Mauritius.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Swan Insurance HealthCare is a trusted and dependable private health plan in Mauritius, backed by decades of local insurance expertise and strong corporate relationships.",
    editorialSource: "Mauritius Consumer Financial Guide 2025",
  },

  // Madagascar (MGA)
  {
    id: "mg-ny-havana",
    name: "Ny Havana Assurance Santé",
    provider: "Ny Havana Assurance",
    country: "Madagascar",
    countryCode: "mg",
    logo: "/logos/ny-havana.svg",
    rating: 3.7,
    reviewCount: 1120,
    monthlyPremium: "MGA 200,000 - MGA 600,000",
    deductible: "MGA 40,000 - MGA 150,000",
    coverageType: "standard",
    badges: ["Local Leader", "Most Popular"],
    highlights: [
      "Madagascar's largest domestic insurer",
      "Coverage at Antananarivo's private clinics and hospitals",
      "Group plans for Malagasy businesses",
    ],
    pros: [
      "Dominant local market presence",
      "Good Antananarivo hospital network",
      "Competitive premiums for the market",
    ],
    cons: [
      "Network very limited outside Antananarivo",
      "No international coverage",
      "No digital tools or telehealth",
    ],
    affiliateUrl: "#",
    description:
      "Ny Havana Assurance is Madagascar's largest domestic insurer, operating for decades in Antananarivo. The Santé plan provides standard health coverage for Malagasy formal sector employees and their families.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Ny Havana is Madagascar's most trusted private health insurer, providing essential coverage for Antananarivo's formal workforce.",
    editorialSource: "Madagascar Insurance Market Assessment 2025",
  },
  {
    id: "mg-aro-assurance",
    name: "ARO Assurance Health Essential",
    provider: "ARO Assurance Madagascar",
    country: "Madagascar",
    countryCode: "mg",
    logo: "/logos/aro-madagascar.svg",
    rating: 3.6,
    reviewCount: 780,
    monthlyPremium: "MGA 150,000 - MGA 450,000",
    deductible: "MGA 30,000 - MGA 100,000",
    coverageType: "basic",
    badges: ["Best Value"],
    highlights: [
      "Affordable private health insurance for Madagascar's formal sector",
      "Basic hospitalisation and outpatient at partner facilities",
      "Simple plan structure suitable for SMEs",
    ],
    pros: [
      "Very affordable premiums",
      "Simple plan structure",
      "Good for basic SME employee coverage",
    ],
    cons: [
      "Very limited network",
      "No specialist coverage in base plan",
      "No digital tools",
    ],
    affiliateUrl: "#",
    description:
      "ARO Assurance is one of Madagascar's established private insurance companies. The Health Essential plan offers basic health coverage at affordable rates for small and medium businesses in Antananarivo.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "ARO Assurance Health Essential is the most accessible private health plan in Madagascar, offering basic protection at the lowest available premiums.",
    editorialSource: "Madagascar Financial Sector Survey 2025",
  },

  // DR Congo (CDF)
  {
    id: "cd-sonas",
    name: "SONAS DR Congo Health Assurance",
    provider: "Société Nationale d'Assurances (SONAS)",
    country: "DR Congo",
    countryCode: "cd",
    logo: "/logos/sonas-drc.svg",
    rating: 3.5,
    reviewCount: 1240,
    monthlyPremium: "CDF 200,000 - CDF 600,000",
    deductible: "CDF 40,000 - CDF 150,000",
    coverageType: "basic",
    badges: ["Government-Backed", "Market Leader"],
    highlights: [
      "DRC's state-owned insurer with national mandate",
      "Coverage at Kinshasa's main private clinics",
      "Affordable plans for DRC's formal sector",
    ],
    pros: [
      "State-backed financial stability",
      "National mandate with Kinshasa hospital acceptance",
      "Low premium cost",
    ],
    cons: [
      "Very limited benefits given DRC healthcare costs",
      "Claims process extremely slow",
      "No digital infrastructure",
    ],
    affiliateUrl: "#",
    description:
      "SONAS (Société Nationale d'Assurances) is the DRC's state-owned insurer holding a national insurance monopoly in several lines. The Health Assurance plan provides basic coverage for DRC formal sector employees at Kinshasa partner facilities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "SONAS is the only formal state health insurer in DR Congo, providing minimal but officially recognised coverage for the country's formal employees.",
    editorialSource: "DRC Financial Services Insurance Assessment 2025",
  },
  {
    id: "cd-rawsur-vie",
    name: "Rawsur Vie DRC Health Plan",
    provider: "Rawsur Vie Insurance",
    country: "DR Congo",
    countryCode: "cd",
    logo: "/logos/rawsur-drc.svg",
    rating: 3.7,
    reviewCount: 680,
    monthlyPremium: "CDF 350,000 - CDF 1,000,000",
    deductible: "CDF 60,000 - CDF 200,000",
    coverageType: "standard",
    badges: ["Best Private Option"],
    highlights: [
      "Private DRC insurer with USD premium options",
      "Best Kinshasa private clinic panel",
      "Corporate plans for mining and NGO sector",
    ],
    pros: [
      "USD premium option protects against CDF depreciation",
      "Best private Kinshasa clinic access",
      "Specialist in mining and NGO sector corporate plans",
    ],
    cons: [
      "High cost in USD equivalent",
      "Network only in Kinshasa",
      "No international coverage",
    ],
    affiliateUrl: "#",
    description:
      "Rawsur Vie is a private DRC insurance company operating primarily in Kinshasa. The Health Plan targets the mining sector, international NGOs, and corporate clients with USD-denominated premiums for financial stability.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Rawsur Vie is the leading private health insurer in DR Congo, serving the mining and NGO sector with USD-linked premiums and the best Kinshasa private clinic network.",
    editorialSource: "DRC Private Sector Insurance Update 2025",
  },

  // Angola (AOA)
  {
    id: "ao-ensa-angola",
    name: "ENSA Angola Health Insurance",
    provider: "Empresa Nacional de Seguros de Angola (ENSA)",
    country: "Angola",
    countryCode: "ao",
    logo: "/logos/ensa-angola.svg",
    rating: 3.8,
    reviewCount: 1820,
    monthlyPremium: "AOA 35,000 - AOA 100,000",
    deductible: "AOA 5,000 - AOA 20,000",
    coverageType: "standard",
    badges: ["Government-Backed", "Most Popular"],
    highlights: [
      "Angola's largest and oldest state-backed insurer",
      "Covers Luanda's main private hospitals and clinics",
      "Mandatory scheme for formal sector employees",
    ],
    pros: [
      "State-backed financial strength",
      "Nationwide brand recognition",
      "Good Luanda hospital network",
    ],
    cons: [
      "Benefits limited relative to oil-economy healthcare costs",
      "Network weak outside Luanda",
      "Digital services underdeveloped",
    ],
    affiliateUrl: "#",
    description:
      "ENSA is Angola's largest and oldest insurance company, partially state-owned. The Health Insurance plan provides standard coverage for Angolan employees and their families with access to Luanda's private healthcare sector.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "ENSA Angola is the most trusted name in Angolan insurance, providing the broadest health coverage network in a market dominated by oil sector corporate plans.",
    editorialSource: "Angola Insurance Market Report 2025",
  },
  {
    id: "ao-global-seguros",
    name: "Global Seguros Angola Premium",
    provider: "Global Seguros Angola",
    country: "Angola",
    countryCode: "ao",
    logo: "/logos/global-seguros.svg",
    rating: 4.0,
    reviewCount: 1240,
    monthlyPremium: "AOA 55,000 - AOA 160,000",
    deductible: "AOA 8,000 - AOA 30,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "Angola's growing private insurer with international backing",
      "Best Luanda private hospital and clinic access",
      "Medical evacuation to South Africa or Portugal",
    ],
    pros: [
      "International evacuation to South Africa or Portugal",
      "Best Luanda private facility access",
      "USD-denominated plan options",
    ],
    cons: [
      "High premiums relative to Angolan incomes",
      "Network concentrated in Luanda",
      "Mental health and dental excluded",
    ],
    affiliateUrl: "#",
    description:
      "Global Seguros Angola is a private insurer targeting Angola's oil sector executives, expatriates, and senior corporate professionals. The Premium plan includes international evacuation and access to Luanda's best private clinics.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Global Seguros Angola Premium is the go-to plan for Luanda's expatriate and senior executive community, offering international evacuation and top private hospital access.",
    editorialSource: "Angola Oil Sector Benefits Review 2025",
  },

  // Zambia (ZMW)
  {
    id: "zm-przez-health",
    name: "Madison Health Insurance Zambia",
    provider: "Madison General Insurance Zambia",
    country: "Zambia",
    countryCode: "zm",
    logo: "/logos/madison-zambia.svg",
    rating: 4.0,
    reviewCount: 1840,
    monthlyPremium: "ZMW 800 - ZMW 2,500",
    deductible: "ZMW 150 - ZMW 600",
    coverageType: "premium",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Zambia's most trusted private health insurer",
      "Wide Lusaka and Copperbelt hospital network",
      "Medical evacuation to South Africa included",
    ],
    pros: [
      "Zambia's largest private health insurer",
      "Medical evacuation to South Africa",
      "Good maternity and newborn coverage",
      "Responsive claims service",
    ],
    cons: [
      "Network thinner in Zambia's rural provinces",
      "Dental and optical sold separately",
      "International coverage limited to evacuation",
    ],
    affiliateUrl: "#",
    description:
      "Madison General Insurance is one of Zambia's leading private insurance companies. The Health Insurance plan provides comprehensive private coverage for Zambian employees and families across Lusaka and the Copperbelt mining region.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Madison Health Insurance is Zambia's leading private health plan, valued for its reliable claims service and medical evacuation to South Africa.",
    editorialSource: "Zambia Insurance Industry Report 2025",
  },
  {
    id: "zm-zbh-health",
    name: "Zambia State Insurance Health",
    provider: "Zambia State Insurance Corporation (ZSIC)",
    country: "Zambia",
    countryCode: "zm",
    logo: "/logos/zsic-zambia.svg",
    rating: 3.7,
    reviewCount: 1320,
    monthlyPremium: "ZMW 500 - ZMW 1,500",
    deductible: "ZMW 100 - ZMW 400",
    coverageType: "standard",
    badges: ["Government-Backed", "Best Value"],
    highlights: [
      "Zambia's state-owned insurer with national coverage",
      "Affordable plans for government and parastatal employees",
      "Accepted at University Teaching Hospital and private partners",
    ],
    pros: [
      "Government-backed stability",
      "Affordable contribution rates",
      "Wide Lusaka hospital acceptance",
    ],
    cons: [
      "Limited private hospital options",
      "Slow claims processing",
      "No digital tools",
    ],
    affiliateUrl: "#",
    description:
      "Zambia State Insurance Corporation (ZSIC) is Zambia's government-owned insurer providing affordable health coverage for public and parastatal sector employees. The Health plan covers treatment at public and accredited private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "ZSIC Health is the dependable, government-backed option for Zambian public sector employees, offering affordable coverage at national healthcare facilities.",
    editorialSource: "Zambia Social Protection Review 2025",
  },

  // Malawi (MWK)
  {
    id: "mw-nico-life-malawi",
    name: "NICO Life Malawi Health Insurance",
    provider: "NICO Life Insurance Company Malawi",
    country: "Malawi",
    countryCode: "mw",
    logo: "/logos/nico-life-malawi.svg",
    rating: 3.8,
    reviewCount: 1240,
    monthlyPremium: "MWK 80,000 - MWK 250,000",
    deductible: "MWK 10,000 - MWK 50,000",
    coverageType: "standard",
    badges: ["Local Leader", "Most Popular"],
    highlights: [
      "Malawi's largest insurance company by market share",
      "Covers Kamuzu Central Hospital and top Lilongwe private clinics",
      "Group plans for Malawian businesses and NGOs",
    ],
    pros: [
      "Dominant market presence",
      "Good Lilongwe and Blantyre hospital network",
      "Experienced in NGO sector group plans",
    ],
    cons: [
      "Network thin in rural Malawi",
      "No international coverage",
      "Digital tools minimal",
    ],
    affiliateUrl: "#",
    description:
      "NICO Life Insurance is Malawi's largest insurance company, providing health insurance for individuals, businesses, and NGOs across the country. The Health Insurance plan covers inpatient and outpatient care at Lilongwe and Blantyre partner facilities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "NICO Life is Malawi's most trusted private health insurer, with decades of experience serving both the corporate and NGO sectors across the country.",
    editorialSource: "Malawi Insurance Market Report 2025",
  },
  {
    id: "mw-old-mutual-malawi",
    name: "Old Mutual Malawi Health Plan",
    provider: "Old Mutual Malawi",
    country: "Malawi",
    countryCode: "mw",
    logo: "/logos/old-mutual-malawi.svg",
    rating: 3.9,
    reviewCount: 920,
    monthlyPremium: "MWK 100,000 - MWK 320,000",
    deductible: "MWK 15,000 - MWK 70,000",
    coverageType: "premium",
    badges: ["Best Private Option"],
    highlights: [
      "Old Mutual's Malawi operation with pan-African backing",
      "Best private hospital access in Lilongwe and Blantyre",
      "Medical evacuation to Zimbabwe or South Africa",
    ],
    pros: [
      "Pan-African Old Mutual financial stability",
      "Medical evacuation included",
      "Best Malawi private hospital access",
    ],
    cons: [
      "Higher cost than local competitors",
      "Network concentrated in Lilongwe and Blantyre",
      "No telehealth services",
    ],
    affiliateUrl: "#",
    description:
      "Old Mutual Malawi is part of the pan-African Old Mutual financial services group. The Health Plan provides premium private health coverage for Malawian professionals, expatriates, and senior corporate employees with medical evacuation capabilities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Old Mutual Malawi Health Plan is the premium option for Malawian executives and expatriates, combining reliable pan-African backing with the country's best private hospital network.",
    editorialSource: "Malawi Corporate Benefits Survey 2025",
  },
];
