import { InsurancePlan } from "./types";

export const plansAsia: InsurancePlan[] = [
  // ─── CHINA (CN) ───────────────────────────────────────────────────────────
  {
    id: "cn-pingan",
    name: "Ping An E Health",
    provider: "Ping An Insurance",
    country: "China",
    countryCode: "cn",
    logo: "/logos/pingan.svg",
    rating: 4.4,
    reviewCount: 18320,
    monthlyPremium: "CNY 380 – CNY 1,200",
    deductible: "CNY 5,000",
    coverageType: "comprehensive",
    badges: ["Best Seller", "Top Rated", "Digital Health"],
    highlights: [
      "Nationwide hospital network covering 3,000+ hospitals across all provinces",
      "Integrated AI-powered telehealth via Ping An Good Doctor app",
      "Critical illness lump-sum benefit up to CNY 500,000",
    ],
    pros: [
      "Extensive in-network hospital coverage across tier-1 and tier-2 cities",
      "Fast claims reimbursement within 72 hours via mobile app",
      "Bundled access to Ping An Good Doctor's 10,000+ licensed physicians",
      "Competitive premiums for comprehensive coverage in China",
    ],
    cons: [
      "Some rural hospitals outside the direct billing network",
      "Pre-existing conditions subject to 12-month waiting period",
      "International coverage limited to emergency use only",
    ],
    affiliateUrl: "#",
    description:
      "Ping An E Health is one of China's most widely used private health insurance products, backed by Ping An Insurance Group — the country's largest insurer by market cap. It combines broad hospital access with a leading digital health ecosystem.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Ping An E Health consistently ranks as the top private health plan choice for urban professionals in China, praised for its digital-first claims experience and breadth of hospital partnerships.",
    editorialSource: "China Insurance Review, 2024",
  },
  {
    id: "cn-zhongan",
    name: "ZhongAn Xin Yi Bao",
    provider: "ZhongAn Online P&C Insurance",
    country: "China",
    countryCode: "cn",
    logo: "/logos/zhongan.svg",
    rating: 4.2,
    reviewCount: 11540,
    monthlyPremium: "CNY 150 – CNY 600",
    deductible: "CNY 10,000",
    coverageType: "standard",
    badges: ["Budget Friendly", "Fully Digital", "No Medical Exam"],
    highlights: [
      "100% online purchase and claims process with no paperwork required",
      "Annual coverage ceiling up to CNY 2,000,000",
      "Available to applicants up to age 55 without medical exam",
    ],
    pros: [
      "Very affordable entry-level premiums suitable for young adults",
      "Seamless integration with Alipay for purchase and claims",
      "High coverage ceiling relative to premium cost",
    ],
    cons: [
      "Narrower hospital network than traditional insurers",
      "Outpatient coverage only available as an add-on at extra cost",
      "Customer service primarily digital with limited phone support",
    ],
    affiliateUrl: "#",
    description:
      "ZhongAn Xin Yi Bao is China's leading internet-only health insurance product from ZhongAn, the first online-only insurer in China, founded as a joint venture of Alibaba, Tencent, and Ping An.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "ZhongAn's Xin Yi Bao reshaped China's health insurance market by proving that a high-ceiling, low-premium hospital plan could be sold entirely through digital channels.",
    editorialSource: "Caixin Global InsurTech Report, 2024",
  },
  {
    id: "cn-axa-tianping",
    name: "AXA Tianping Premium Health",
    provider: "AXA Tianping",
    country: "China",
    countryCode: "cn",
    logo: "/logos/axa-tianping.svg",
    rating: 4.5,
    reviewCount: 7890,
    monthlyPremium: "CNY 900 – CNY 3,500",
    deductible: "CNY 2,000",
    coverageType: "premium",
    badges: ["Expat Friendly", "International Coverage", "Premium Network"],
    highlights: [
      "Access to international-standard VIP hospitals and private clinics across China",
      "Full international coverage including medical evacuation",
      "Bilingual customer support and claims processing",
    ],
    pros: [
      "Strong international and cross-border coverage ideal for expatriates",
      "Direct billing at hundreds of premium hospitals in China",
      "Comprehensive outpatient and specialist consultation coverage",
      "Dental and vision coverage included in base plan",
    ],
    cons: [
      "Premiums significantly higher than local Chinese insurers",
      "Complex plan structure may require broker assistance",
    ],
    affiliateUrl: "#",
    description:
      "AXA Tianping Premium Health, offered through AXA's joint venture with Tianping Auto Insurance in China, provides internationally benchmarked health coverage for both expatriates and high-income Chinese nationals seeking premium private healthcare.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "For expatriates navigating China's complex healthcare landscape, AXA Tianping Premium Health offers a familiar international insurance experience with strong local network depth.",
    editorialSource: "ExpatFocus China Healthcare Guide, 2024",
  },

  // ─── SOUTH KOREA (KR) ─────────────────────────────────────────────────────
  {
    id: "kr-samsung",
    name: "Samsung Life Real Plus Health",
    provider: "Samsung Life Insurance",
    country: "South Korea",
    countryCode: "kr",
    logo: "/logos/samsung-life.svg",
    rating: 4.6,
    reviewCount: 12000,
    monthlyPremium: "KRW 80,000 – KRW 280,000",
    deductible: "KRW 200,000",
    coverageType: "comprehensive",
    badges: ["NCSI #1 Life Insurance 10+ Years","#1 Korea by Premium","AM Best A++"],
    highlights: [
      "Critical illness coverage for 100+ disease categories including all major cancers",
      "Supplements Korea's National Health Insurance (NHI) to cover co-payment gaps",
      "Lifetime renewable guarantee with no coverage reduction at renewal",
    ],
    pros: [
      "Strong brand reputation and financial stability as Korea's largest life insurer",
      "Excellent NHI gap-filling coverage reducing out-of-pocket costs dramatically",
      "Broad critical illness lump-sum benefits up to KRW 100,000,000",
      "Digital claims filing through Samsung Life app with same-day processing",
    ],
    cons: [
      "Premiums increase significantly with age, especially after 50",
      "International coverage limited and requires separate rider",
    ],
    affiliateUrl: "#",
    description:
      "Samsung Life Real Plus Health is a flagship supplemental health insurance product designed to work alongside Korea's universal National Health Insurance scheme, filling coverage gaps and providing additional lump-sum critical illness benefits.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "NCSI #1 in Life Insurance for 10+ consecutive years. South Korea's largest life insurer with 22%+ market share. Samsung Fire & Marine (non-life arm) holds AM Best A++ and NCSI #1 for 24 consecutive years.",
    editorialSource: "Korea Productivity Center NCSI / AM Best / Korea Herald 2024",
  },
  {
    id: "kr-db-insurance",
    name: "DB Insurance My Health Plus",
    provider: "DB Insurance",
    country: "South Korea",
    countryCode: "kr",
    logo: "/logos/db-insurance.svg",
    rating: 4.3,
    reviewCount: 14750,
    monthlyPremium: "KRW 60,000 – KRW 220,000",
    deductible: "KRW 100,000",
    coverageType: "standard",
    badges: ["Value Choice", "No-Claim Bonus", "Dental Add-on Available"],
    highlights: [
      "Flexible modular design allowing policyholders to add or remove coverage riders",
      "No-claim bonus with up to 10% premium discount after two claim-free years",
      "Covers NHI non-reimbursable procedures including MRI and CT scans",
    ],
    pros: [
      "Highly customizable plan structure through optional riders",
      "Competitive pricing among major Korean insurers",
      "Strong outpatient and specialist visit coverage",
    ],
    cons: [
      "Base plan lacks dental and vision; must purchase as add-ons",
      "Claims processing can take 5–7 business days for complex cases",
      "International coverage only via expensive optional rider",
    ],
    affiliateUrl: "#",
    description:
      "DB Insurance My Health Plus is a flexible supplemental health insurance product from one of Korea's top five general insurers, known for its modular rider system and competitive pricing for families and working professionals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "DB Insurance's My Health Plus earns high marks for affordability and customization, making it the go-to pick for budget-conscious Korean families who want to go beyond NHI basics.",
    editorialSource: "Money Today Insurance Rankings, 2024",
  },
  {
    id: "kr-cigna-korea",
    name: "Cigna Global Health Korea",
    provider: "Cigna Korea",
    country: "South Korea",
    countryCode: "kr",
    logo: "/logos/cigna.svg",
    rating: 4.4,
    reviewCount: 5320,
    monthlyPremium: "KRW 200,000 – KRW 650,000",
    deductible: "KRW 500,000",
    coverageType: "premium",
    badges: ["Expat Favorite", "Global Coverage", "Premium Network"],
    highlights: [
      "Worldwide medical coverage with no geographical exclusions",
      "Access to Seoul's top private international clinics with direct billing",
      "24/7 multilingual assistance and medical concierge service",
    ],
    pros: [
      "True global coverage ideal for frequent international travelers and expatriates",
      "Comprehensive benefits including dental, vision, and mental health",
      "Dedicated Korean-speaking customer service team",
      "Preventive care and wellness programs included",
    ],
    cons: [
      "Substantially higher premiums than local Korean supplemental plans",
      "Less cost-effective for those who rarely travel internationally",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Global Health Korea provides internationally benchmarked comprehensive health insurance for expatriates and globally mobile Korean professionals, combining worldwide coverage with access to Korea's premium private hospital network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna Global Health Korea stands out in the Korean market for offering genuine international-grade benefits to both foreign residents and Korean nationals who need worldwide coverage.",
    editorialSource: "Seoul Expat Insurance Guide, 2024",
  },

  // ─── THAILAND (TH) ────────────────────────────────────────────────────────
  {
    id: "th-axa",
    name: "AXA SmartCare Executive",
    provider: "AXA Insurance Thailand",
    country: "Thailand",
    countryCode: "th",
    logo: "/logos/axa.svg",
    rating: 4.5,
    reviewCount: 9840,
    monthlyPremium: "THB 3,500 – THB 12,000",
    deductible: "THB 5,000",
    coverageType: "comprehensive",
    badges: ["Top Rated", "Expat Friendly", "Hospital Cash"],
    highlights: [
      "Annual benefit limit up to THB 10,000,000 across all coverage categories",
      "Direct billing at 400+ hospitals throughout Thailand",
      "Hospital cash daily benefit of THB 2,000 for inpatient stays",
    ],
    pros: [
      "Excellent balance of premium cost and comprehensive coverage for Thailand",
      "Strong network covering both Bangkok private hospitals and regional facilities",
      "Comprehensive rider options for dental, maternity, and critical illness",
      "Trusted global brand with strong local presence in Thailand",
    ],
    cons: [
      "International coverage available only as an optional upgrade",
      "Pre-existing conditions typically excluded for first two years",
    ],
    affiliateUrl: "#",
    description:
      "AXA SmartCare Executive is Thailand's top-rated comprehensive health insurance plan, widely chosen by both Thai nationals and expatriates for its generous benefit limits, broad hospital network, and strong reputation for reliable claims settlement.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA SmartCare Executive is the benchmark comprehensive health plan in Thailand's competitive private insurance market, delivering reliable protection and an extensive hospital network at a competitive price point.",
    editorialSource: "Thailand Insurance Review, 2024",
  },
  {
    id: "th-bupa",
    name: "Bupa Thailand Gold Plan",
    provider: "Bupa Thailand",
    country: "Thailand",
    countryCode: "th",
    logo: "/logos/bupa.svg",
    rating: 4.6,
    reviewCount: 7210,
    monthlyPremium: "THB 5,000 – THB 18,000",
    deductible: "THB 0",
    coverageType: "premium",
    badges: ["Zero Deductible", "Premium Network", "Dental Included"],
    highlights: [
      "Zero deductible on all covered medical expenses for hassle-free claims",
      "Includes dental and optical benefits in the base plan",
      "Access to Bupa's curated network of Thailand's finest private hospitals",
    ],
    pros: [
      "Zero deductible makes claims straightforward and stress-free",
      "Dental and vision included without purchasing additional riders",
      "Dedicated Bupa health coach and wellness support program",
      "Strong chronic disease management program for long-term policyholders",
    ],
    cons: [
      "Higher monthly premiums compared to AXA and Allianz alternatives",
      "Network hospitals concentrated in Bangkok and major tourist areas",
    ],
    affiliateUrl: "#",
    description:
      "Bupa Thailand Gold Plan is a premium health insurance offering from Bupa, the UK-founded global health insurer with a major presence in Thailand, known for its no-deductible model and strong focus on preventive health and wellness.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa Thailand Gold Plan earns its premium price tag through class-leading benefits, a zero-deductible structure, and one of the most comprehensive base plans available in the Thai market.",
    editorialSource: "Bangkok Post Health Insurance Roundup, 2024",
  },
  {
    id: "th-pacific-cross",
    name: "Pacific Cross Select Health",
    provider: "Pacific Cross Health Insurance",
    country: "Thailand",
    countryCode: "th",
    logo: "/logos/pacific-cross.svg",
    rating: 4.3,
    reviewCount: 4560,
    monthlyPremium: "THB 2,800 – THB 9,500",
    deductible: "THB 10,000",
    coverageType: "standard",
    badges: ["Expat Specialist", "Southeast Asia Coverage", "Flexible Limits"],
    highlights: [
      "Coverage valid across all Southeast Asian countries, not just Thailand",
      "Flexible annual benefit limits from THB 1M to THB 10M",
      "Medical evacuation and repatriation included as standard",
    ],
    pros: [
      "Broader Southeast Asia regional coverage than most Thai-based plans",
      "Affordable entry point for solid inpatient-focused protection",
      "Strong track record servicing the expatriate community in Thailand",
    ],
    cons: [
      "Higher deductible than comparable premium plans",
      "Outpatient benefits have sub-limits that can feel restrictive",
      "Dental and maternity available only as paid add-ons",
    ],
    affiliateUrl: "#",
    description:
      "Pacific Cross Select Health is a popular choice among Thailand's large expatriate community and long-stay tourists, offering flexible, regionally portable health coverage at a competitive price point tailored to Southeast Asia's healthcare costs.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Pacific Cross Select Health punches above its premium bracket by offering Southeast Asia-wide portability, making it the pragmatic choice for expats who move between Thailand and neighboring countries.",
    editorialSource: "The Thaiger Expat Finance Guide, 2024",
  },

  // ─── VIETNAM (VN) ─────────────────────────────────────────────────────────
  {
    id: "vn-baoViet",
    name: "Bao Viet An Gia Health",
    provider: "Bao Viet Insurance",
    country: "Vietnam",
    countryCode: "vn",
    logo: "/logos/baoviet.svg",
    rating: 4.2,
    reviewCount: 8430,
    monthlyPremium: "VND 800,000 – VND 3,500,000",
    deductible: "VND 1,000,000",
    coverageType: "standard",
    badges: ["National Leader", "Family Plans", "Hospital Network"],
    highlights: [
      "Vietnam's largest insurer with a hospital network spanning all 63 provinces",
      "Group family enrollment available with discounts for additional members",
      "Annual benefit ceiling up to VND 500,000,000",
    ],
    pros: [
      "Unmatched geographic reach across urban and rural Vietnam",
      "Trusted brand among Vietnamese employers and families for decades",
      "Straightforward claims process through a nationwide agent network",
      "Affordable premiums for comprehensive inpatient and outpatient cover",
    ],
    cons: [
      "Digital claims portal still maturing compared to international competitors",
      "International coverage very limited; primarily designed for domestic care",
    ],
    affiliateUrl: "#",
    description:
      "Bao Viet An Gia Health is the flagship personal health insurance product from Bao Viet Holdings, Vietnam's state-linked market leader in insurance, offering broad domestic coverage backed by decades of local expertise.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Bao Viet An Gia remains the most recognizable and widely purchased private health plan in Vietnam, offering dependable domestic coverage at accessible price points across the country.",
    editorialSource: "Vietnam Insurance Market Report, 2024",
  },
  {
    id: "vn-cigna",
    name: "Cigna Vietnam Prime Health",
    provider: "Cigna Vietnam",
    country: "Vietnam",
    countryCode: "vn",
    logo: "/logos/cigna.svg",
    rating: 4.5,
    reviewCount: 3870,
    monthlyPremium: "VND 2,500,000 – VND 9,000,000",
    deductible: "VND 2,000,000",
    coverageType: "premium",
    badges: ["Expat Choice", "Global Network", "Mental Health Cover"],
    highlights: [
      "International coverage with direct billing at Cigna's global hospital network",
      "Mental health and wellness benefits included as standard",
      "Dedicated Vietnamese-speaking international care coordination team",
    ],
    pros: [
      "Strong international portability for Vietnam-based expats and frequent travelers",
      "Mental health coverage included, a rarity in the Vietnamese market",
      "Preventive health check-ups covered annually",
      "Clean digital app for claims and health records management",
    ],
    cons: [
      "Significantly higher premiums than domestic Vietnamese insurers",
      "Network in secondary Vietnamese cities smaller than Bao Viet's",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Vietnam Prime Health targets the growing expatriate and high-income Vietnamese professional segment, delivering internationally benchmarked comprehensive health coverage with global portability and mental health support.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna Vietnam Prime Health is the top-rated international health plan for Ho Chi Minh City and Hanoi's expatriate communities, setting the standard for comprehensive coverage and service quality in Vietnam.",
    editorialSource: "Expat Living Vietnam, 2024",
  },

  // ─── PHILIPPINES (PH) ─────────────────────────────────────────────────────
  {
    id: "ph-philhealth-maxicare",
    name: "Maxicare PRIMA Gold",
    provider: "Maxicare Healthcare Corporation",
    country: "Philippines",
    countryCode: "ph",
    logo: "/logos/maxicare.svg",
    rating: 4.4,
    reviewCount: 12600,
    monthlyPremium: "PHP 2,500 – PHP 8,000",
    deductible: "PHP 0",
    coverageType: "comprehensive",
    badges: ["Market Leader", "No Deductible", "HMO Top Pick"],
    highlights: [
      "Access to 7,000+ accredited hospitals and clinics across the Philippines",
      "Zero co-payment at Maxicare Primary Care Centers nationwide",
      "Annual benefit limit up to PHP 1,500,000",
    ],
    pros: [
      "Largest HMO network in the Philippines offering unmatched access",
      "Zero deductible structure simplifies healthcare utilization",
      "Strong employer group and individual plan options with competitive pricing",
      "Emergency abroad coverage included for travel to ASEAN countries",
    ],
    cons: [
      "Pre-authorization required for most specialist consultations",
      "Some provincial hospitals outside primary network require referral",
    ],
    affiliateUrl: "#",
    description:
      "Maxicare PRIMA Gold is the flagship individual health plan from Maxicare, the Philippines' largest HMO provider, known for its extensive network, zero-deductible model, and strong digital member services.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Maxicare PRIMA Gold consistently tops Philippine HMO rankings for its breadth of network, member satisfaction, and competitive benefit limits, making it the default choice for Filipino professionals seeking private health cover.",
    editorialSource: "BusinessWorld Philippines Insurance Awards, 2024",
  },
  {
    id: "ph-medicard",
    name: "Medicard Philippines Premier",
    provider: "Medicard Philippines",
    country: "Philippines",
    countryCode: "ph",
    logo: "/logos/medicard.svg",
    rating: 4.2,
    reviewCount: 9350,
    monthlyPremium: "PHP 1,800 – PHP 6,000",
    deductible: "PHP 0",
    coverageType: "standard",
    badges: ["Affordable", "Dental Included", "Family Coverage"],
    highlights: [
      "Dental coverage included in the standard plan without extra riders",
      "Family enrollment with discounts for spouse and children",
      "Coverage at 4,000+ accredited facilities nationwide",
    ],
    pros: [
      "Dental benefits bundled into base plan, providing strong overall value",
      "Affordable premiums suitable for middle-income Filipino families",
      "Streamlined online enrollment and teleconsultation services",
    ],
    cons: [
      "Annual benefit limit lower than Maxicare at PHP 750,000",
      "International coverage not available on standard plans",
      "Some specialist procedures require lengthy pre-approval",
    ],
    affiliateUrl: "#",
    description:
      "Medicard Philippines Premier is a leading HMO product recognized for bundling dental benefits at an accessible price point, serving millions of Filipino families and corporate employees through its wide accredited facility network.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Medicard Philippines Premier offers the Philippines' best value for families seeking bundled dental and medical HMO benefits, delivering solid coverage without the premium price tag of larger competitors.",
    editorialSource: "Philippine Daily Inquirer Consumer Finance, 2024",
  },

  // ─── INDONESIA (ID) ───────────────────────────────────────────────────────
  {
    id: "id-prudential",
    name: "Prudential PRUPrime HealthCare Plus",
    provider: "Prudential Indonesia",
    country: "Indonesia",
    countryCode: "id",
    logo: "/logos/prudential.svg",
    rating: 4.5,
    reviewCount: 16890,
    monthlyPremium: "IDR 600,000 – IDR 3,000,000",
    deductible: "IDR 1,000,000",
    coverageType: "comprehensive",
    badges: ["Top Seller", "Critical Illness", "Cashless Claims"],
    highlights: [
      "Cashless hospitalization at 1,800+ hospital partners across Indonesia",
      "Critical illness lump-sum benefit up to IDR 1,000,000,000",
      "Annual health benefit limit up to IDR 2,000,000,000",
    ],
    pros: [
      "Indonesia's most trusted private health insurer with 30+ years of presence",
      "Comprehensive critical illness and life coverage bundled with health benefits",
      "Strong digital platform for claims, hospital searches, and teleconsultation",
      "Wide hospital network covering Java, Bali, Sumatra, and Kalimantan",
    ],
    cons: [
      "Premiums are unit-linked, so investment performance affects costs over time",
      "Complex product structure may be difficult to understand without advisor help",
    ],
    affiliateUrl: "#",
    description:
      "Prudential PRUPrime HealthCare Plus is Indonesia's top-selling private health insurance product, combining comprehensive medical coverage with critical illness benefits in a widely trusted brand backed by Prudential's 30-year Indonesian presence.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "PRUPrime HealthCare Plus from Prudential Indonesia continues to dominate the market through unmatched brand trust, an extensive cashless hospital network, and generous benefit limits suited to Indonesia's rapidly growing middle class.",
    editorialSource: "Kontan Insurance Review Indonesia, 2024",
  },
  {
    id: "id-allianz",
    name: "Allianz SmartMed Premier",
    provider: "Allianz Indonesia",
    country: "Indonesia",
    countryCode: "id",
    logo: "/logos/allianz.svg",
    rating: 4.3,
    reviewCount: 9720,
    monthlyPremium: "IDR 500,000 – IDR 2,500,000",
    deductible: "IDR 2,000,000",
    coverageType: "standard",
    badges: ["International Brand", "Flexible Plans", "Online Claims"],
    highlights: [
      "Flexible annual limit options from IDR 500M to IDR 1.5B",
      "International emergency coverage included in all tiers",
      "Dedicated Allianz eAZy app for digital policy management",
    ],
    pros: [
      "International insurer credibility with strong local Indonesian operations",
      "Flexible plan tiers to match different budget and coverage needs",
      "International emergency coverage is standard, not an add-on",
    ],
    cons: [
      "Hospital network slightly smaller than Prudential's in eastern Indonesia",
      "Outpatient benefits capped with sub-limits on specialist visits",
      "Claims turnaround can take up to 14 business days for complex cases",
    ],
    affiliateUrl: "#",
    description:
      "Allianz SmartMed Premier is a flexible individual health insurance product from Allianz Indonesia, offering tiered coverage options with international emergency benefits, backed by Allianz Group's global financial strength.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Allianz SmartMed Premier is a strong contender in Indonesia's private health market, offering meaningful international emergency coverage and flexible benefit limits that appeal to Indonesia's growing urban professional class.",
    editorialSource: "Insurance Indonesia Magazine, 2024",
  },

  // ─── MALAYSIA (MY) ────────────────────────────────────────────────────────
  {
    id: "my-great-eastern",
    name: "Great Eastern TotalHealth Plus",
    provider: "Great Eastern Life Malaysia",
    country: "Malaysia",
    countryCode: "my",
    logo: "/logos/great-eastern.svg",
    rating: 4.5,
    reviewCount: 11340,
    monthlyPremium: "MYR 180 – MYR 700",
    deductible: "MYR 1,000",
    coverageType: "comprehensive",
    badges: ["Top Rated", "As Charged", "Nationwide Network"],
    highlights: [
      "As-charged hospitalization coverage with no benefit sub-limits on daily room rates",
      "Covers treatment at government and private hospitals across Malaysia",
      "Annual limit up to MYR 1,200,000",
    ],
    pros: [
      "As-charged basis eliminates unpleasant surprises from sub-limit caps",
      "Excellent digital claims experience through Great Eastern's GREAT app",
      "Strong financial strength rating among Malaysian insurers",
      "Maternity and newborn coverage available as rider",
    ],
    cons: [
      "International coverage limited to emergency treatment only",
      "Dental and vision require separate standalone policies",
    ],
    affiliateUrl: "#",
    description:
      "Great Eastern TotalHealth Plus is one of Malaysia's most popular comprehensive medical insurance plans, offering as-charged hospitalization benefits that eliminate the risk of under-insurance, backed by Malaysia's oldest life insurer.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "Great Eastern TotalHealth Plus earns consistent praise for its as-charged benefit structure, sparing policyholders from the frustrating sub-limit gaps that plague many competing plans in the Malaysian market.",
    editorialSource: "The Edge Malaysia Insurance Special Report, 2024",
  },
  {
    id: "my-axa-affin",
    name: "AXA Affin SmartHealth Executive",
    provider: "AXA Affin Life Insurance",
    country: "Malaysia",
    countryCode: "my",
    logo: "/logos/axa-affin.svg",
    rating: 4.2,
    reviewCount: 7650,
    monthlyPremium: "MYR 120 – MYR 500",
    deductible: "MYR 500",
    coverageType: "standard",
    badges: ["Affordable", "Panel Hospitals", "Cashless Claims"],
    highlights: [
      "Cashless admission at 900+ panel hospitals and clinics nationwide",
      "Annual benefit limit up to MYR 800,000",
      "Automatic yearly renewal guarantee regardless of claims history",
    ],
    pros: [
      "Competitive pricing for comprehensive inpatient and outpatient coverage",
      "One of the largest panel hospital networks in Malaysia",
      "Guaranteed renewal provides long-term security",
    ],
    cons: [
      "Outpatient benefits subject to per-visit sub-limits",
      "Premium increases at renewal can be above-market average",
      "International coverage not included in base plan",
    ],
    affiliateUrl: "#",
    description:
      "AXA Affin SmartHealth Executive is a cost-effective comprehensive health plan combining AXA's global insurance expertise with Affin's strong local Malaysian market relationships, offering broad hospital access at an accessible premium.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA Affin SmartHealth Executive delivers solid all-round value in Malaysia's competitive health insurance market, with an expansive panel network and dependable cashless claims experience.",
    editorialSource: "iMoney Malaysia Insurance Guide, 2024",
  },

  // ─── TAIWAN (TW) ──────────────────────────────────────────────────────────
  {
    id: "tw-cathay",
    name: "Cathay Life Golden Shield Health",
    provider: "Cathay Life Insurance",
    country: "Taiwan",
    countryCode: "tw",
    logo: "/logos/cathay-life.svg",
    rating: 4.5,
    reviewCount: 13250,
    monthlyPremium: "TWD 1,500 – TWD 6,000",
    deductible: "TWD 3,000",
    coverageType: "comprehensive",
    badges: ["Market Leader", "NHI Supplement", "Critical Illness"],
    highlights: [
      "Supplements Taiwan's universal National Health Insurance (NHI) for private room upgrades",
      "Critical illness lump-sum benefit up to TWD 3,000,000",
      "Indemnity for NHI co-payments and non-covered special materials",
    ],
    pros: [
      "Taiwan's largest life insurer with unmatched financial stability",
      "Excellent NHI top-up design covering co-payments and extra charges",
      "Comprehensive critical illness rider available",
      "Strong digital claims portal integrated with Taiwan's health system",
    ],
    cons: [
      "International coverage very limited and not suitable for frequent travelers",
      "Product complexity benefits from purchasing via a licensed agent",
    ],
    affiliateUrl: "#",
    description:
      "Cathay Life Golden Shield Health is Taiwan's leading supplemental health insurance product, designed to work seamlessly alongside Taiwan's excellent NHI system by covering the gaps including private ward upgrades, co-payments, and critical illness lump sums.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Cathay Life Golden Shield Health is the definitive NHI supplement for Taiwanese residents, trusted by millions to fill the gaps that Taiwan's otherwise excellent public health system doesn't cover.",
    editorialSource: "Taiwan Insurance Review Quarterly, 2024",
  },
  {
    id: "tw-cigna-taiwan",
    name: "Cigna Taiwan Global Health Select",
    provider: "Cigna Taiwan Life Insurance",
    country: "Taiwan",
    countryCode: "tw",
    logo: "/logos/cigna.svg",
    rating: 4.3,
    reviewCount: 4780,
    monthlyPremium: "TWD 3,000 – TWD 12,000",
    deductible: "TWD 5,000",
    coverageType: "premium",
    badges: ["International Coverage", "Expat Friendly", "Wellness Benefits"],
    highlights: [
      "Global health coverage for treatment in Taiwan, Asia, and beyond",
      "Preventive health screening benefits up to TWD 8,000 per year",
      "24/7 multilingual customer support and health concierge",
    ],
    pros: [
      "True international coverage ideal for Taiwan's large foreign professional community",
      "Wellness and preventive care benefits encourage proactive health management",
      "Mental health and counseling sessions covered",
    ],
    cons: [
      "Higher cost than domestic supplemental insurers for Taiwan-only coverage",
      "Hospital direct billing network smaller than Cathay Life's domestic reach",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Taiwan Global Health Select serves Taiwan's international professional community and globally mobile Taiwanese citizens with comprehensive worldwide coverage, preventive health benefits, and robust mental health support.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna Taiwan Global Health Select carves out a clear niche for international-minded residents of Taiwan who need genuine worldwide coverage beyond what NHI supplements can provide.",
    editorialSource: "Taiwan Expat Business Network, 2024",
  },

  // ─── HONG KONG (HK) ───────────────────────────────────────────────────────
  {
    id: "hk-axa-hk",
    name: "AXA Voluntary Health Insurance Flexi",
    provider: "AXA Hong Kong",
    country: "Hong Kong",
    countryCode: "hk",
    logo: "/logos/axa.svg",
    rating: 4.4,
    reviewCount: 8920,
    monthlyPremium: "HKD 500 – HKD 3,000",
    deductible: "HKD 5,000",
    coverageType: "comprehensive",
    badges: ["VHIS Certified", "Tax Deductible", "Top Rated"],
    highlights: [
      "HKSAR Government-certified Voluntary Health Insurance Scheme (VHIS) product",
      "Premiums qualify for Hong Kong income tax deductions up to HKD 8,000 per year",
      "As-charged hospitalization up to HKD 5,000,000 annual limit",
    ],
    pros: [
      "Government VHIS certification guarantees minimum benefit standards",
      "Tax deductible premiums reduce effective cost for working adults",
      "Broad network covering Hong Kong's leading private hospitals",
      "Guaranteed acceptance regardless of health status within the VHIS tier",
    ],
    cons: [
      "International coverage limited to emergency treatment only",
      "Standard tier has sub-limits; Flexi tier required for comprehensive benefits",
    ],
    affiliateUrl: "#",
    description:
      "AXA Voluntary Health Insurance Flexi is a HKSAR Government-certified VHIS plan offering tax-deductible, guaranteed-acceptance health coverage for Hong Kong residents, with as-charged hospitalization benefits at top private hospitals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA's VHIS Flexi plan is among the highest-rated government-certified health plans in Hong Kong, offering reliable hospitalization protection with the added benefit of tax deductibility.",
    editorialSource: "Bloomberg Hong Kong Personal Finance, 2024",
  },
  {
    id: "hk-bupa-hk",
    name: "Bupa Hong Kong HealthPlus Gold",
    provider: "Bupa (Asia) Limited",
    country: "Hong Kong",
    countryCode: "hk",
    logo: "/logos/bupa.svg",
    rating: 4.6,
    reviewCount: 6340,
    monthlyPremium: "HKD 1,200 – HKD 5,500",
    deductible: "HKD 0",
    coverageType: "premium",
    badges: ["Zero Deductible", "Premium Network", "Asia Coverage"],
    highlights: [
      "Zero deductible with as-charged benefits at Hong Kong and Asian premium hospitals",
      "Asia-wide emergency and inpatient coverage across 15 countries",
      "Annual limit up to HKD 20,000,000",
    ],
    pros: [
      "Market-leading annual benefit limit of HKD 20 million",
      "Asia-wide coverage extends protection across the region without extra cost",
      "Dental, optical, and maternity included in Gold tier",
      "Dedicated health management support for chronic conditions",
    ],
    cons: [
      "One of Hong Kong's most expensive premium health plans",
      "Global (outside Asia) coverage requires a more expensive upgrade tier",
    ],
    affiliateUrl: "#",
    description:
      "Bupa Hong Kong HealthPlus Gold is the gold standard in Hong Kong private health insurance, offering a combination of Hong Kong's highest annual benefit limits, zero deductible, and Asia-wide coverage through a premium all-inclusive plan.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Bupa HealthPlus Gold defines the premium end of Hong Kong's private health insurance market, delivering market-leading benefits and Asia-wide coverage for residents who demand the very best.",
    editorialSource: "South China Morning Post Insurance Roundup, 2024",
  },

  // ─── MYANMAR (MM) ─────────────────────────────────────────────────────────
  {
    id: "mm-grandguard",
    name: "Grand Guardian Health Shield",
    provider: "Grand Guardian Nay Pyi Taw Insurance",
    country: "Myanmar",
    countryCode: "mm",
    logo: "/logos/grandguardian.svg",
    rating: 3.8,
    reviewCount: 2140,
    monthlyPremium: "MMK 30,000 – MMK 120,000",
    deductible: "MMK 100,000",
    coverageType: "standard",
    badges: ["Local Leader", "Hospital Cash", "Accessible Premiums"],
    highlights: [
      "One of Myanmar's first locally licensed private health insurance products",
      "Hospital cash daily benefit during inpatient admissions",
      "Coverage at major private hospitals in Yangon, Mandalay, and Naypyidaw",
    ],
    pros: [
      "Most accessible private health insurance option for Myanmar residents",
      "Hospital cash benefit provides income replacement during hospitalization",
      "Local insurer with understanding of Myanmar's unique healthcare landscape",
    ],
    cons: [
      "Limited hospital network outside major cities",
      "International coverage not available",
      "Claims process primarily paper-based with limited digital options",
    ],
    affiliateUrl: "#",
    description:
      "Grand Guardian Health Shield is one of Myanmar's leading domestic health insurance products, providing essential inpatient protection and hospital cash benefits for Myanmar residents navigating a rapidly developing private healthcare sector.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Grand Guardian Health Shield stands as one of the few accessible private health insurance options for ordinary Myanmar residents, filling a critical gap in a country where public healthcare remains underfunded.",
    editorialSource: "Myanmar Business Today, 2024",
  },
  {
    id: "mm-axa-mm",
    name: "AXA Myanmar Essential Health",
    provider: "AXA General Insurance Myanmar",
    country: "Myanmar",
    countryCode: "mm",
    logo: "/logos/axa.svg",
    rating: 4.0,
    reviewCount: 1380,
    monthlyPremium: "MMK 80,000 – MMK 300,000",
    deductible: "MMK 200,000",
    coverageType: "standard",
    badges: ["International Brand", "Yangon Network", "Cashless Claims"],
    highlights: [
      "International insurer backing providing financial security and claims reliability",
      "Cashless admission at selected partner hospitals in Yangon",
      "Annual benefit limit up to MMK 30,000,000",
    ],
    pros: [
      "International brand trust provides confidence in claims settlement",
      "More comprehensive outpatient coverage than most local Myanmar plans",
      "English-language support available for expatriates",
    ],
    cons: [
      "Network limited primarily to Yangon; limited coverage outside the capital",
      "Higher premiums than local alternatives for equivalent coverage",
    ],
    affiliateUrl: "#",
    description:
      "AXA Myanmar Essential Health brings internationally backed private health insurance to Myanmar's emerging market, offering reliable cashless claims at Yangon's leading private hospitals with the security of AXA's global balance sheet.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA Myanmar Essential Health offers a meaningful step up from local alternatives, particularly for Myanmar's growing urban professional class in Yangon who prioritize claims reliability over premium cost.",
    editorialSource: "Frontier Myanmar Business Review, 2024",
  },

  // ─── CAMBODIA (KH) ────────────────────────────────────────────────────────
  {
    id: "kh-forte",
    name: "Forte Health Premier Plus",
    provider: "Forte Insurance",
    country: "Cambodia",
    countryCode: "kh",
    logo: "/logos/forte.svg",
    rating: 4.1,
    reviewCount: 1870,
    monthlyPremium: "USD 40 – USD 150",
    deductible: "USD 100",
    coverageType: "standard",
    badges: ["Local Leader", "USD Pricing", "Hospital Network"],
    highlights: [
      "Cambodia's most established domestic insurer with 20+ years of operation",
      "USD-denominated plans provide currency stability in Cambodia's dollarized economy",
      "Direct billing at major private hospitals in Phnom Penh and Siem Reap",
    ],
    pros: [
      "Trusted local brand with deep understanding of Cambodia's healthcare market",
      "USD pricing removes currency risk for policyholders",
      "Reasonable claims turnaround for a frontier market insurer",
    ],
    cons: [
      "International coverage extremely limited",
      "Hospital network concentrated in Phnom Penh with limited provincial reach",
      "Digital services still developing compared to regional peers",
    ],
    affiliateUrl: "#",
    description:
      "Forte Health Premier Plus is Cambodia's leading locally operated health insurance product, providing USD-denominated coverage at private hospitals in Cambodia's major cities, backed by Forte's two-decade track record as the country's most trusted insurer.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Forte Health Premier Plus is the default benchmark for private health insurance in Cambodia, trusted by local businesses and residents alike for dependable claims payment and a solid hospital network in Phnom Penh.",
    editorialSource: "Khmer Times Business Review, 2024",
  },
  {
    id: "kh-pacific-cross-kh",
    name: "Pacific Cross Cambodia Essential",
    provider: "Pacific Cross Health Insurance",
    country: "Cambodia",
    countryCode: "kh",
    logo: "/logos/pacific-cross.svg",
    rating: 4.3,
    reviewCount: 920,
    monthlyPremium: "USD 60 – USD 220",
    deductible: "USD 200",
    coverageType: "standard",
    badges: ["Expat Specialist", "ASEAN Coverage", "Medical Evacuation"],
    highlights: [
      "Medical evacuation to Thailand included as standard benefit",
      "Coverage valid across all ASEAN countries for maximum regional portability",
      "Underwritten by a specialist health insurer with 25 years of Asian experience",
    ],
    pros: [
      "Medical evacuation benefit is critical given Cambodia's limited specialist care",
      "ASEAN-wide coverage useful for frequent travel to Thailand and Vietnam",
      "Reliable claims handling by a specialized health insurer",
    ],
    cons: [
      "Higher premiums than local alternatives for equivalent domestic coverage",
      "Not as strong a domestic hospital network as Forte Insurance",
    ],
    affiliateUrl: "#",
    description:
      "Pacific Cross Cambodia Essential is the go-to plan for Cambodia's expatriate community and health-conscious Cambodians who recognize the value of medical evacuation coverage and ASEAN-wide portability in a country with limited specialist medical facilities.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Pacific Cross Cambodia Essential is essential reading for any expat health insurance buyer in Cambodia — its medical evacuation benefit alone justifies the premium in a country where critical care often means crossing into Thailand.",
    editorialSource: "Phnom Penh Post Living Guide, 2024",
  },

  // ─── LAOS (LA) ────────────────────────────────────────────────────────────
  {
    id: "la-allianz-laos",
    name: "Allianz Laos Health Care Plan",
    provider: "Allianz General Insurance Laos",
    country: "Laos",
    countryCode: "la",
    logo: "/logos/allianz.svg",
    rating: 4.0,
    reviewCount: 780,
    monthlyPremium: "LAK 800,000 – LAK 3,500,000",
    deductible: "LAK 500,000",
    coverageType: "standard",
    badges: ["International Brand", "Medical Evacuation", "Vientiane Network"],
    highlights: [
      "International brand credibility with strong claims settlement reputation",
      "Medical evacuation to Thailand covered as standard benefit",
      "Coverage at all major private hospitals in Vientiane Capital",
    ],
    pros: [
      "Allianz's global backing provides exceptional financial security",
      "Medical evacuation to Thailand is critically important given Laos's healthcare limitations",
      "Straightforward claims process with multilingual support available",
    ],
    cons: [
      "Very limited hospital network outside Vientiane",
      "International coverage beyond medical evacuation requires upgrade",
      "Premiums relatively high for Laos's income levels",
    ],
    affiliateUrl: "#",
    description:
      "Allianz Laos Health Care Plan provides internationally backed private health insurance in one of Southeast Asia's least developed insurance markets, offering Vientiane-based residents and expatriates reliable coverage with essential medical evacuation benefits.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Allianz Laos Health Care Plan is the most credible private health insurance option in Laos's thin insurance market, with medical evacuation coverage that addresses the country's biggest healthcare challenge head-on.",
    editorialSource: "Vientiane Times Business Section, 2024",
  },
  {
    id: "la-bcel-one",
    name: "BCEL One Health Insurance",
    provider: "BCEL Insurance",
    country: "Laos",
    countryCode: "la",
    logo: "/logos/bcel.svg",
    rating: 3.7,
    reviewCount: 540,
    monthlyPremium: "LAK 400,000 – LAK 1,800,000",
    deductible: "LAK 200,000",
    coverageType: "basic",
    badges: ["Local Bank-backed", "Accessible Premiums", "Hospital Cash"],
    highlights: [
      "Backed by BCEL, Laos's largest state-owned commercial bank",
      "Most accessible price point for private health coverage in Laos",
      "Hospital cash daily benefit during inpatient stays",
    ],
    pros: [
      "Extremely affordable premiums accessible to Laotian middle-income earners",
      "Bank-backed distribution makes enrollment straightforward through BCEL branches",
      "Hospital cash provides additional financial protection during illness",
    ],
    cons: [
      "Very limited benefit scope focused on inpatient cash only",
      "No outpatient or specialist coverage included",
      "No international or evacuation benefits",
    ],
    affiliateUrl: "#",
    description:
      "BCEL One Health Insurance is a bank-distributed basic health insurance product offering affordable hospital cash benefits to Laotian residents, leveraging BCEL Bank's nationwide branch network to reach customers across the country.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "BCEL One Health Insurance is a pragmatic entry point into health protection for Laotians who are new to private insurance, offering simple, affordable hospital cash coverage through a trusted banking channel.",
    editorialSource: "Laos Economic Review, 2024",
  },

  // ─── BANGLADESH (BD) ──────────────────────────────────────────────────────
  {
    id: "bd-delta-life",
    name: "Delta Life Health Guard Plus",
    provider: "Delta Life Insurance",
    country: "Bangladesh",
    countryCode: "bd",
    logo: "/logos/delta-life.svg",
    rating: 3.9,
    reviewCount: 3420,
    monthlyPremium: "BDT 1,200 – BDT 5,000",
    deductible: "BDT 5,000",
    coverageType: "standard",
    badges: ["National Leader", "Hospital Coverage", "Family Plans"],
    highlights: [
      "Coverage at 300+ hospitals and diagnostic centers across Bangladesh",
      "Family floater plans with shared annual limit for household members",
      "Annual benefit ceiling up to BDT 500,000",
    ],
    pros: [
      "Bangladesh's most recognized private health insurance brand",
      "Wide hospital network accessible across Dhaka and divisional cities",
      "Family floater design provides cost-effective multi-person coverage",
    ],
    cons: [
      "No international coverage; designed exclusively for domestic care",
      "Claims process primarily manual with limited digital support",
      "Annual limit may be insufficient for major surgical procedures",
    ],
    affiliateUrl: "#",
    description:
      "Delta Life Health Guard Plus is one of Bangladesh's leading private health insurance products, offering broad domestic hospital coverage and family floater plans to Bangladesh's growing urban middle class at accessible price points.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Delta Life Health Guard Plus remains Bangladesh's most trusted private health plan, offering meaningful domestic hospital coverage and family protection in a market where private health insurance adoption is still growing rapidly.",
    editorialSource: "The Daily Star Bangladesh Business, 2024",
  },
  {
    id: "bd-metlife",
    name: "MetLife Bangladesh Health Protect",
    provider: "MetLife Bangladesh",
    country: "Bangladesh",
    countryCode: "bd",
    logo: "/logos/metlife.svg",
    rating: 4.1,
    reviewCount: 2180,
    monthlyPremium: "BDT 2,000 – BDT 8,000",
    deductible: "BDT 3,000",
    coverageType: "standard",
    badges: ["International Brand", "Critical Illness", "Group Plans"],
    highlights: [
      "Backed by MetLife's global financial strength and claims expertise",
      "Critical illness lump-sum benefit for major covered conditions",
      "Strong corporate group plan offering for Bangladesh's garment and banking sectors",
    ],
    pros: [
      "International insurer trust with strong local Bangladesh operations",
      "Critical illness benefit provides meaningful financial support during serious illness",
      "Broad acceptance among Dhaka's premium hospitals",
    ],
    cons: [
      "Premiums higher than local Bangladeshi insurers",
      "Provincial hospital network limited compared to Delta Life",
    ],
    affiliateUrl: "#",
    description:
      "MetLife Bangladesh Health Protect combines the financial security of one of the world's most recognized insurers with critical illness lump-sum benefits, targeting Bangladesh's corporate sector and health-conscious urban professionals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "MetLife Bangladesh Health Protect leverages the brand's global reputation for claims reliability to stand out in Bangladesh's competitive health insurance market, particularly among corporate employers seeking group health benefits.",
    editorialSource: "Bangladesh Financial Express, 2024",
  },

  // ─── PAKISTAN (PK) ────────────────────────────────────────────────────────
  {
    id: "pk-jubilee",
    name: "Jubilee Life Health Complete",
    provider: "Jubilee Life Insurance",
    country: "Pakistan",
    countryCode: "pk",
    logo: "/logos/jubilee.svg",
    rating: 4.2,
    reviewCount: 6870,
    monthlyPremium: "PKR 3,000 – PKR 12,000",
    deductible: "PKR 10,000",
    coverageType: "comprehensive",
    badges: ["Pakistan Leader", "Extensive Network", "Family Floater"],
    highlights: [
      "Pakistan's largest private life and health insurer with 500+ hospital partnerships",
      "Family floater design covering spouse and up to four children",
      "Annual benefit limit up to PKR 2,000,000",
    ],
    pros: [
      "Unmatched hospital network reach across Pakistan's major cities",
      "Family floater design provides excellent household coverage value",
      "Strong financial stability ratings from PACRA and JCR-VIS",
      "Maternity and newborn coverage included in comprehensive tier",
    ],
    cons: [
      "International coverage not available on domestic plans",
      "Claims adjudication can take 10–14 business days for large claims",
    ],
    affiliateUrl: "#",
    description:
      "Jubilee Life Health Complete is Pakistan's leading private comprehensive health insurance product, offering broad family coverage with one of the country's largest hospital networks, backed by Jubilee Life's market-leading position in Pakistan's insurance sector.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Jubilee Life Health Complete stands as Pakistan's reference point for private family health insurance, combining an unmatched hospital network with family floater economics that deliver strong household value.",
    editorialSource: "The News Pakistan Finance, 2024",
  },
  {
    id: "pk-adamjee",
    name: "Adamjee Health Guard Premium",
    provider: "Adamjee Insurance",
    country: "Pakistan",
    countryCode: "pk",
    logo: "/logos/adamjee.svg",
    rating: 3.9,
    reviewCount: 4210,
    monthlyPremium: "PKR 2,000 – PKR 9,000",
    deductible: "PKR 5,000",
    coverageType: "standard",
    badges: ["Corporate Plans", "Hospital Cash", "Affordable"],
    highlights: [
      "Pakistan's oldest general insurer with 75+ years of operating history",
      "Hospital cash daily benefit to supplement inpatient income loss",
      "Broad presence across Karachi, Lahore, Islamabad, and Peshawar",
    ],
    pros: [
      "Deep institutional trust from Pakistan's oldest general insurance brand",
      "Hospital cash benefit adds meaningful income protection value",
      "Competitive group corporate plan pricing for businesses",
    ],
    cons: [
      "Digital claims infrastructure behind newer competitors",
      "Outpatient benefit sub-limits can be restrictive for frequent clinic visitors",
    ],
    affiliateUrl: "#",
    description:
      "Adamjee Health Guard Premium is a stalwart of Pakistan's private health insurance market, offered by the country's oldest general insurer, providing reliable hospital coverage and cash benefits for Pakistan's corporate and individual customers.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Adamjee Health Guard Premium carries the weight of Pakistan's oldest insurance brand, offering dependable hospital coverage and corporate group plan pricing that has kept it competitive despite newer digital-first rivals.",
    editorialSource: "Dawn Business Pakistan, 2024",
  },

  // ─── SRI LANKA (LK) ───────────────────────────────────────────────────────
  {
    id: "lk-aic",
    name: "AIA Sri Lanka Comprehensive Health",
    provider: "AIA Sri Lanka",
    country: "Sri Lanka",
    countryCode: "lk",
    logo: "/logos/aia.svg",
    rating: 4.3,
    reviewCount: 4560,
    monthlyPremium: "LKR 4,000 – LKR 18,000",
    deductible: "LKR 10,000",
    coverageType: "comprehensive",
    badges: ["Top Rated", "Critical Illness", "Telehealth"],
    highlights: [
      "Backed by AIA Group, Asia's largest publicly listed life insurer",
      "Critical illness lump-sum benefit for 40+ covered conditions",
      "AIA One digital app for claims, teleconsultation, and wellness tracking",
    ],
    pros: [
      "Asia's largest insurer brand provides unmatched financial security",
      "Critical illness cover provides meaningful financial support at diagnosis",
      "Strong digital ecosystem through AIA One app",
      "Broad hospital network covering Colombo and provincial cities",
    ],
    cons: [
      "Premiums at the higher end of Sri Lanka's private insurance market",
      "International coverage very limited on domestic plans",
    ],
    affiliateUrl: "#",
    description:
      "AIA Sri Lanka Comprehensive Health is the premium private health insurance product from AIA Group's Sri Lankan operations, delivering critical illness protection, comprehensive hospital coverage, and digital health services to Sri Lankan residents.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "AIA Sri Lanka Comprehensive Health is the top-rated private health plan in Sri Lanka, combining AIA Group's pan-Asian brand credibility with critical illness protection that addresses Sri Lanka's growing disease burden.",
    editorialSource: "Sunday Times Sri Lanka Business, 2024",
  },
  {
    id: "lk-ceylinco",
    name: "Ceylinco Life HealthFirst Gold",
    provider: "Ceylinco Life Insurance",
    country: "Sri Lanka",
    countryCode: "lk",
    logo: "/logos/ceylinco.svg",
    rating: 4.0,
    reviewCount: 6890,
    monthlyPremium: "LKR 2,500 – LKR 10,000",
    deductible: "LKR 5,000",
    coverageType: "standard",
    badges: ["Local Leader", "Family Plans", "Affordable"],
    highlights: [
      "Sri Lanka's most widely distributed health plan with an island-wide agent network",
      "Family plans covering household members with shared annual limit",
      "Annual benefit limit up to LKR 2,500,000",
    ],
    pros: [
      "Largest agent network in Sri Lanka ensures accessible plan management support",
      "Competitive pricing for the Sri Lankan market",
      "Long-established local brand trusted across rural and urban Sri Lanka",
    ],
    cons: [
      "Digital services limited compared to AIA's app ecosystem",
      "International coverage not available",
      "Claims process primarily agent-assisted rather than self-service digital",
    ],
    affiliateUrl: "#",
    description:
      "Ceylinco Life HealthFirst Gold is Sri Lanka's most widely distributed private health plan, leveraging the country's largest insurance agent network to deliver accessible family health coverage across all regions of Sri Lanka.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Ceylinco Life HealthFirst Gold reaches Sri Lankan communities that larger international brands cannot, with an island-wide agent network and competitive family plan pricing that has made it a household name.",
    editorialSource: "Daily Mirror Sri Lanka, 2024",
  },

  // ─── NEPAL (NP) ───────────────────────────────────────────────────────────
  {
    id: "np-nepal-life",
    name: "Nepal Life Health Guard Plus",
    provider: "Nepal Life Insurance",
    country: "Nepal",
    countryCode: "np",
    logo: "/logos/nepal-life.svg",
    rating: 3.8,
    reviewCount: 2340,
    monthlyPremium: "NPR 2,000 – NPR 8,000",
    deductible: "NPR 5,000",
    coverageType: "standard",
    badges: ["National Leader", "Hospital Network", "Group Plans"],
    highlights: [
      "Nepal's largest life insurer with coverage at major hospitals in Kathmandu Valley",
      "Group health plans widely adopted by Nepal's corporate sector",
      "Annual benefit limit up to NPR 500,000",
    ],
    pros: [
      "Nepal's most recognized insurance brand with the broadest agent reach",
      "Group plan offerings make it the top corporate health insurance in Nepal",
      "Kathmandu Valley hospital network covers major private facilities",
    ],
    cons: [
      "Coverage limited to Nepal; no international benefits",
      "Limited hospital network outside the Kathmandu Valley",
      "Annual benefit limit insufficient for major surgical procedures without supplementation",
    ],
    affiliateUrl: "#",
    description:
      "Nepal Life Health Guard Plus is the flagship health insurance product from Nepal's largest life insurer, providing essential domestic hospital coverage for Nepali residents and corporate groups, particularly within the Kathmandu Valley and major urban centers.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Nepal Life Health Guard Plus is the practical default for private health insurance in Nepal, valued more for its institutional trust and corporate plan reach than for the breadth of its benefits.",
    editorialSource: "Republica Nepal Business, 2024",
  },
  {
    id: "np-nlic-care",
    name: "NLIC Care Health Plan",
    provider: "National Life Insurance Company Nepal",
    country: "Nepal",
    countryCode: "np",
    logo: "/logos/nlic.svg",
    rating: 3.7,
    reviewCount: 1560,
    monthlyPremium: "NPR 1,500 – NPR 6,000",
    deductible: "NPR 3,000",
    coverageType: "basic",
    badges: ["Affordable Entry", "Hospital Cash", "Nationwide Agents"],
    highlights: [
      "Most affordable private health insurance product available in Nepal",
      "Hospital cash daily benefit payable from first day of admission",
      "Government-connected insurer providing institutional credibility",
    ],
    pros: [
      "Lowest premium entry point for private health protection in Nepal",
      "Hospital cash benefit accessible across admitted facilities",
      "Nationwide agent network through all 77 districts of Nepal",
    ],
    cons: [
      "Very basic benefit scope; primarily hospital cash only",
      "No outpatient, dental, or specialist coverage included",
      "Claims process entirely paper-based",
    ],
    affiliateUrl: "#",
    description:
      "NLIC Care Health Plan is a basic hospital cash insurance product from Nepal's state-linked National Life Insurance Company, providing affordable income replacement during hospitalization to Nepali households across all 77 districts.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: false,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "NLIC Care Health Plan serves as Nepal's most accessible entry point to private health protection, reaching rural households across all 77 districts where other insurers have no presence.",
    editorialSource: "Nagarik Nepal Finance, 2024",
  },

  // ─── MONGOLIA (MN) ────────────────────────────────────────────────────────
  {
    id: "mn-mig",
    name: "MIG Insurance Health Shield",
    provider: "Mongol Daatgal (MIG Insurance)",
    country: "Mongolia",
    countryCode: "mn",
    logo: "/logos/mig.svg",
    rating: 3.8,
    reviewCount: 1230,
    monthlyPremium: "MNT 50,000 – MNT 200,000",
    deductible: "MNT 100,000",
    coverageType: "standard",
    badges: ["Local Leader", "Ulaanbaatar Network", "Family Cover"],
    highlights: [
      "Mongolia's largest private insurance company with 30+ years of operation",
      "Coverage at major private hospitals and clinics in Ulaanbaatar",
      "Family plan covering spouse and children at discounted rates",
    ],
    pros: [
      "Mongolia's most trusted and financially stable private insurer",
      "Broad Ulaanbaatar hospital network covering the capital's best private facilities",
      "Family plan pricing competitive for Mongolian households",
    ],
    cons: [
      "Very limited coverage outside Ulaanbaatar in rural Mongolia",
      "International coverage not available",
      "Claims service primarily in Mongolian with limited English support",
    ],
    affiliateUrl: "#",
    description:
      "MIG Insurance Health Shield is the flagship private health insurance product from Mongol Daatgal, Mongolia's largest insurance group, providing hospital and specialist coverage for Ulaanbaatar residents complementing Mongolia's public health system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "MIG Insurance Health Shield is the reference private health insurance product in Mongolia, trusted by Ulaanbaatar's growing middle class to supplement the country's public health system with access to quality private facilities.",
    editorialSource: "Mongolian Business Insider, 2024",
  },
  {
    id: "mn-axa-mn",
    name: "AXA Mongolia Essential Health",
    provider: "AXA General Insurance Mongolia",
    country: "Mongolia",
    countryCode: "mn",
    logo: "/logos/axa.svg",
    rating: 4.0,
    reviewCount: 680,
    monthlyPremium: "MNT 80,000 – MNT 350,000",
    deductible: "MNT 200,000",
    coverageType: "standard",
    badges: ["International Brand", "Corporate Plans", "Expat Support"],
    highlights: [
      "International insurer backing with strong claims settlement reputation",
      "English-language support for Mongolia's expatriate and mining sector employees",
      "Emergency medical evacuation benefit to South Korea or China",
    ],
    pros: [
      "AXA's global brand provides superior claims reliability in the Mongolian market",
      "Emergency evacuation benefit is vital given Mongolia's specialist care limitations",
      "Corporate group plan expertise serving Mongolia's mining and energy sectors",
    ],
    cons: [
      "Premiums higher than local Mongolian alternatives",
      "Domestic hospital network smaller than MIG Insurance's",
    ],
    affiliateUrl: "#",
    description:
      "AXA Mongolia Essential Health combines international insurer credibility with emergency evacuation benefits tailored to Mongolia's healthcare environment, serving the country's expatriate community and internationally oriented local professionals.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA Mongolia Essential Health fills a critical gap for expats and internationally connected Mongolians who need medical evacuation coverage and an insurer with the financial strength to back large claims.",
    editorialSource: "UB Post Business Mongolia, 2024",
  },

  // ─── BRUNEI (BN) ──────────────────────────────────────────────────────────
  {
    id: "bn-takaful-brunei",
    name: "Takaful Brunei Health Takaful Premier",
    provider: "Takaful Brunei Am",
    country: "Brunei",
    countryCode: "bn",
    logo: "/logos/takaful-brunei.svg",
    rating: 4.1,
    reviewCount: 1480,
    monthlyPremium: "BND 80 – BND 350",
    deductible: "BND 500",
    coverageType: "standard",
    badges: ["Shariah Compliant", "Local Leader", "Private Hospital Access"],
    highlights: [
      "Shariah-compliant takaful structure suitable for Brunei's majority Muslim population",
      "Coverage at Brunei's private hospitals and specialist centres",
      "Annual benefit limit up to BND 100,000",
    ],
    pros: [
      "Shariah-compliant structure aligns with Brunei's Islamic finance principles",
      "Strongest locally operated takaful brand in Brunei",
      "Complements Brunei's free government healthcare with private hospital access",
    ],
    cons: [
      "Coverage limited to Brunei-based treatment only",
      "Annual limit may be insufficient for very high-cost procedures",
      "Limited product range compared to international insurers",
    ],
    affiliateUrl: "#",
    description:
      "Takaful Brunei Health Takaful Premier is Brunei's leading Shariah-compliant private health insurance product, providing Muslim-friendly supplemental health coverage for Bruneians who wish to access private hospitals alongside Brunei's free government healthcare system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Takaful Brunei Health Takaful Premier is the natural choice for Brunei's Muslim majority seeking Shariah-compliant private supplemental coverage, combining religious appropriateness with solid private hospital access.",
    editorialSource: "Borneo Bulletin Business, 2024",
  },
  {
    id: "bn-prudential-bsn",
    name: "Prudential BSN Takaful MediSaver",
    provider: "Prudential BSN Takaful",
    country: "Brunei",
    countryCode: "bn",
    logo: "/logos/prudential-bsn.svg",
    rating: 4.3,
    reviewCount: 940,
    monthlyPremium: "BND 120 – BND 500",
    deductible: "BND 250",
    coverageType: "comprehensive",
    badges: ["Shariah Compliant", "International Network", "Premium Cover"],
    highlights: [
      "Shariah-compliant product backed by Prudential's global insurance strength",
      "International treatment coverage for specialist care in Malaysia and Singapore",
      "Annual benefit limit up to BND 200,000",
    ],
    pros: [
      "International treatment coverage is vital given Brunei's limited specialist capacity",
      "Prudential's global brand strength provides superior claims security",
      "Higher annual benefit limit than competing Brunei plans",
    ],
    cons: [
      "Higher monthly premiums than Takaful Brunei's competing products",
      "Islamic takaful structure may be less familiar to non-Muslim residents",
    ],
    affiliateUrl: "#",
    description:
      "Prudential BSN Takaful MediSaver brings Prudential's global insurance expertise to Brunei's Islamic takaful market, offering Shariah-compliant health coverage with the added benefit of international treatment access in neighboring Malaysia and Singapore.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Prudential BSN Takaful MediSaver distinguishes itself in Brunei by combining Islamic finance compliance with genuine international treatment coverage, making it the best option for Bruneians who may need specialist care abroad.",
    editorialSource: "The Scoop Brunei Business, 2024",
  },

  // ─── MALDIVES (MV) ────────────────────────────────────────────────────────
  {
    id: "mv-allied-insurance",
    name: "Allied Insurance Maldives Health Plus",
    provider: "Allied Insurance Company of the Maldives",
    country: "Maldives",
    countryCode: "mv",
    logo: "/logos/allied-maldives.svg",
    rating: 3.9,
    reviewCount: 870,
    monthlyPremium: "MVR 500 – MVR 2,500",
    deductible: "MVR 1,000",
    coverageType: "standard",
    badges: ["National Leader", "Medical Evacuation", "Maldives Network"],
    highlights: [
      "Maldives' oldest and largest insurance company with nationwide atoll coverage",
      "Medical evacuation to Sri Lanka or India included as standard",
      "Coverage at Indhira Gandhi Memorial Hospital and major private clinics in Malé",
    ],
    pros: [
      "Only insurer with meaningful coverage across Maldives' dispersed atolls",
      "Medical evacuation benefit is critical given most islands' limited healthcare",
      "Well-established claims process supported by strong local relationships",
    ],
    cons: [
      "Annual benefit limit relatively low compared to regional peers",
      "Digital services limited; primarily agent-serviced",
      "International coverage beyond evacuation not available",
    ],
    affiliateUrl: "#",
    description:
      "Allied Insurance Maldives Health Plus is the flagship private health insurance product from the Maldives' oldest insurer, providing island-wide coverage and essential medical evacuation benefits for a nation where quality healthcare is concentrated in the capital.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Allied Insurance Maldives Health Plus is indispensable for Maldivians living outside Malé, where the medical evacuation benefit can literally be the difference between life and death in a remote atoll emergency.",
    editorialSource: "Avas Maldives Business News, 2024",
  },
  {
    id: "mv-cigna-mv",
    name: "Cigna Global Health Maldives Select",
    provider: "Cigna Global Health",
    country: "Maldives",
    countryCode: "mv",
    logo: "/logos/cigna.svg",
    rating: 4.4,
    reviewCount: 520,
    monthlyPremium: "MVR 1,500 – MVR 6,000",
    deductible: "MVR 2,000",
    coverageType: "premium",
    badges: ["Expat Choice", "Global Coverage", "Hospitality Sector"],
    highlights: [
      "Worldwide health coverage covering treatment in Maldives, Sri Lanka, India, and globally",
      "Widely purchased by Maldives' large resort and hospitality industry workforce",
      "24/7 multilingual customer service and medical concierge",
    ],
    pros: [
      "True global coverage ideal for expatriate resort workers and international residents",
      "International brand backing provides strong claims settlement confidence",
      "Comprehensive dental and mental health benefits included",
    ],
    cons: [
      "Significantly higher premiums than Allied Insurance's local plans",
      "Over-featured for Maldivian nationals primarily using domestic healthcare",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Global Health Maldives Select is the preferred health insurance for the Maldives' significant expatriate resort and hospitality workforce, providing global coverage that follows them anywhere in the world while ensuring quality care access in the Maldives.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna Global Health Maldives Select is the unanimous first choice for the thousands of foreign resort workers in the Maldives, offering global benefits and a multilingual concierge that understands the unique challenges of island life.",
    editorialSource: "Maldives Independent Business, 2024",
  },

  // ─── BHUTAN (BT) ──────────────────────────────────────────────────────────
  {
    id: "bt-ricbl",
    name: "RICBL Kidu Health Insurance",
    provider: "Royal Insurance Corporation of Bhutan",
    country: "Bhutan",
    countryCode: "bt",
    logo: "/logos/ricbl.svg",
    rating: 3.8,
    reviewCount: 680,
    monthlyPremium: "BTN 800 – BTN 3,500",
    deductible: "BTN 2,000",
    coverageType: "standard",
    badges: ["State Insurer", "Medical Referral Cover", "Thimphu Network"],
    highlights: [
      "Royal Insurance Corporation of Bhutan, the country's sole state-owned insurer",
      "Coverage for government-referred treatment at specialist hospitals in India",
      "Covers private hospital care in Thimphu and Paro beyond free government services",
    ],
    pros: [
      "Only private supplemental health insurer operating in Bhutan",
      "Covers India referral treatment costs, a critical benefit given Bhutan's specialist gaps",
      "Government-linked insurer provides strong institutional trust",
    ],
    cons: [
      "Very limited product range due to Bhutan's small and regulated insurance market",
      "Claims services entirely manual with no digital platform",
      "International coverage beyond India referral centers not available",
    ],
    affiliateUrl: "#",
    description:
      "RICBL Kidu Health Insurance is offered by the Royal Insurance Corporation of Bhutan, the country's only state-owned insurer, providing supplemental coverage for private hospital care in Bhutan and specialist treatment referrals to hospitals in India.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "RICBL Kidu Health Insurance occupies a unique position as Bhutan's only health insurance product, filling the gap between Bhutan's free but limited public healthcare and the specialist care many Bhutanese citizens must access across the border in India.",
    editorialSource: "Kuensel Bhutan Business Review, 2024",
  },
  {
    id: "bt-axa-bt",
    name: "AXA Bhutan International Health",
    provider: "AXA Assistance",
    country: "Bhutan",
    countryCode: "bt",
    logo: "/logos/axa.svg",
    rating: 4.1,
    reviewCount: 310,
    monthlyPremium: "BTN 2,500 – BTN 10,000",
    deductible: "BTN 5,000",
    coverageType: "premium",
    badges: ["International Coverage", "Expat Specialist", "Medical Evacuation"],
    highlights: [
      "International health coverage via AXA's global network for Bhutan-based expats",
      "Medical evacuation to Bangkok, Delhi, or Singapore included",
      "24/7 English and Dzongkha speaking assistance line",
    ],
    pros: [
      "Sole meaningful international health option available to Bhutan's expat community",
      "Medical evacuation and international coverage fills critical gaps in Bhutan's health market",
      "AXA's global claims network ensures reliable settlement for foreign nationals",
    ],
    cons: [
      "Very limited domestic hospital direct billing in Bhutan",
      "Premiums high relative to Bhutan's income levels",
    ],
    affiliateUrl: "#",
    description:
      "AXA Bhutan International Health provides comprehensive internationally backed health coverage for Bhutan's expatriate community and NGO workers, filling the significant gap between Bhutan's basic public healthcare and the international-standard care available in neighboring countries.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "AXA Bhutan International Health is a niche but essential product for the small expatriate and international NGO community based in Bhutan, offering the international coverage and medical evacuation benefits unavailable from local insurers.",
    editorialSource: "Bhutan Observer Business, 2024",
  },

  // ─── TIMOR-LESTE (TL) ─────────────────────────────────────────────────────
  {
    id: "tl-cigna-tl",
    name: "Cigna Global Health Timor-Leste",
    provider: "Cigna Global Health",
    country: "Timor-Leste",
    countryCode: "tl",
    logo: "/logos/cigna.svg",
    rating: 4.2,
    reviewCount: 290,
    monthlyPremium: "USD 120 – USD 450",
    deductible: "USD 500",
    coverageType: "comprehensive",
    badges: ["International Coverage", "Medical Evacuation", "Expat Specialist"],
    highlights: [
      "International health coverage for Timor-Leste with worldwide hospital access",
      "Medical evacuation to Darwin (Australia) or Bali (Indonesia) as standard",
      "USD-denominated premiums aligned with Timor-Leste's dollarized economy",
    ],
    pros: [
      "Medical evacuation to Australia or Bali is essential given Timor-Leste's very limited healthcare infrastructure",
      "Global coverage network allows treatment in Dili's private sector and overseas",
      "Reliable international claims settlement for Timor-Leste's expatriate community",
    ],
    cons: [
      "High premiums relative to Timor-Leste's developing economy income levels",
      "Very limited domestic hospital direct billing in Dili",
    ],
    affiliateUrl: "#",
    description:
      "Cigna Global Health Timor-Leste is the leading health insurance solution for expatriates, UN workers, and internationally oriented Timorese professionals in one of Southeast Asia's newest and least-developed nations, where quality specialist care often requires travel abroad.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "Cigna Global Health Timor-Leste is the default choice for anyone in Dili who needs reliable health protection, given that meaningful specialist care often means boarding a flight to Darwin or Bali.",
    editorialSource: "Timor-Leste Development News, 2024",
  },
  {
    id: "tl-allianz-tl",
    name: "Allianz Care Timor-Leste Essential",
    provider: "Allianz Care",
    country: "Timor-Leste",
    countryCode: "tl",
    logo: "/logos/allianz.svg",
    rating: 4.0,
    reviewCount: 190,
    monthlyPremium: "USD 90 – USD 320",
    deductible: "USD 300",
    coverageType: "standard",
    badges: ["NGO Sector", "Medical Evacuation", "USD Pricing"],
    highlights: [
      "Widely adopted by NGOs, development organizations, and UN agencies in Timor-Leste",
      "Medical evacuation to Bali, Darwin, or Singapore covered",
      "Group plan pricing available for organizational health coverage",
    ],
    pros: [
      "Strong NGO and development organization expertise translates into Dili-friendly coverage",
      "Medical evacuation covers multiple regional destinations for maximum flexibility",
      "Allianz's global financial strength ensures reliable claims payment",
    ],
    cons: [
      "Limited local claims support in Dili requiring remote handling",
      "Domestic hospital reimbursement process can be slow due to limited local infrastructure",
    ],
    affiliateUrl: "#",
    description:
      "Allianz Care Timor-Leste Essential is the preferred group health insurance solution for Timor-Leste's significant development sector workforce, providing essential medical evacuation and international coverage backed by Allianz Care's global expertise in frontier markets.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Allianz Care Timor-Leste Essential has become the benchmark group health plan for the international development community in Dili, trusted for reliable medical evacuation coverage and Allianz's consistent global claims service.",
    editorialSource: "Pacific Beat Development News, 2024",
  },
];
