import { InsurancePlan } from "./types";

export const plansOceania: InsurancePlan[] = [
  // New Zealand (NZD)
  {
    id: "nz-southern-cross",
    name: "Southern Cross Wellbeing Two",
    provider: "Southern Cross Health Society",
    country: "New Zealand",
    countryCode: "nz",
    logo: "/logos/southern-cross-nz.svg",
    rating: 4.7,
    reviewCount: 18240,
    monthlyPremium: "NZD 85 - NZD 280",
    deductible: "NZD 0 - NZD 500",
    coverageType: "comprehensive",
    badges: ["S&P A+","Reader's Digest Most Trusted 2017-2025","Not-for-Profit"],
    highlights: [
      "New Zealand's largest health insurer with 900,000+ members",
      "Covers specialist consultations, surgery, and imaging",
      "No-claims discount rewards healthy members",
    ],
    pros: [
      "New Zealand's most trusted health insurance brand",
      "Comprehensive specialist and surgical coverage",
      "No-claims discount of up to 10%",
      "Fast pre-approval for surgical procedures",
    ],
    cons: [
      "GP visits not covered in standard Wellbeing Two plan",
      "Dental and optical sold separately",
      "Premiums increase with age",
    ],
    affiliateUrl: "#",
    description:
      "Southern Cross Health Society is a not-for-profit health insurer and New Zealand's market leader with over 900,000 members. The Wellbeing Two plan is the country's most popular private health plan, covering specialist consultations, diagnostic tests, and elective surgery.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: true,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: true,
    },
    editorialExcerpt:
      "NZ's largest health insurer with 951,000+ members. S&P A+ (Strong). Reader's Digest Most Trusted Health Insurance Brand 2017-2025 (consecutive). Pays 93.3 cents per premium dollar in claims.",
    editorialSource: "Southern Cross Annual Report 2024 / MoneyHub NZ / Reader's Digest",
  },
  {
    id: "nz-nib-nz",
    name: "nib New Zealand Ultimate Health",
    provider: "nib New Zealand",
    country: "New Zealand",
    countryCode: "nz",
    logo: "/logos/nib-nz.svg",
    rating: 4.5,
    reviewCount: 9840,
    monthlyPremium: "NZD 100 - NZD 340",
    deductible: "NZD 0 - NZD 750",
    coverageType: "comprehensive",
    badges: ["S&P A","Canstar Outstanding Value 7 Years","NZ #2 Insurer"],
    highlights: [
      "Comprehensive coverage including GP visits and dental",
      "Strong international coverage for New Zealanders overseas",
      "Leading digital health tools and teleconsultation",
    ],
    pros: [
      "Covers GP visits in Ultimate Health plan",
      "Strong international and travel health coverage",
      "Best-in-class digital health app in NZ",
      "Comprehensive mental health benefits",
    ],
    cons: [
      "Higher premiums than Southern Cross for equivalent tier",
      "Excess choices can be confusing",
      "Maternity care limited in base plan",
    ],
    affiliateUrl: "#",
    description:
      "nib New Zealand is part of the ASX-listed nib Holdings Group. The Ultimate Health plan is the most comprehensive individual plan in nib's NZ range, covering GP visits, specialist care, dental, and offering strong international coverage for New Zealanders abroad.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: true,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: true,
    },
    editorialExcerpt:
      "NZ's 2nd-largest health insurer. S&P A (Strong). Won Canstar Outstanding Value Working Visa Health Cover for 7 consecutive years. Solvency ratio 157% (March 2025).",
    editorialSource: "PolicyWise NZ / Canstar NZ 2025 / MoneyHub NZ",
  },
  {
    id: "nz-accuro",
    name: "Accuro Health Insurance Essential Care",
    provider: "Accuro Health Insurance",
    country: "New Zealand",
    countryCode: "nz",
    logo: "/logos/accuro-nz.svg",
    rating: 4.3,
    reviewCount: 5620,
    monthlyPremium: "NZD 65 - NZD 200",
    deductible: "NZD 0 - NZD 500",
    coverageType: "standard",
    badges: ["Best Value", "Members-Owned"],
    highlights: [
      "New Zealand-owned and member-governed not-for-profit insurer",
      "Highly competitive premiums for solid specialist and surgical coverage",
      "Strong member loyalty with consistent low premium increases",
    ],
    pros: [
      "Not-for-profit structure passes savings to members",
      "Competitive premiums relative to benefit level",
      "Good member satisfaction scores",
    ],
    cons: [
      "Smaller brand than Southern Cross or nib",
      "GP visits not covered",
      "International coverage limited",
    ],
    affiliateUrl: "#",
    description:
      "Accuro Health Insurance is a New Zealand-owned, not-for-profit health insurer governed by its members. The Essential Care plan provides solid private health coverage focused on specialist consultations and elective surgery at competitive rates.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Accuro Essential Care is New Zealand's best-value private health plan for members who want solid surgical and specialist coverage without paying a premium for brand recognition.",
    editorialSource: "NZ Health Insurance Value Index 2025",
  },

  // Fiji (FJD)
  {
    id: "fj-colonial-fiji",
    name: "Colonial Fiji Health Insurance Premier",
    provider: "Colonial Fiji Life Limited",
    country: "Fiji",
    countryCode: "fj",
    logo: "/logos/colonial-fiji.svg",
    rating: 4.2,
    reviewCount: 3240,
    monthlyPremium: "FJD 120 - FJD 380",
    deductible: "FJD 50 - FJD 200",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Fiji's largest life and health insurer",
      "Covers treatment at Colonial War Memorial Hospital and Suva Private Hospital",
      "Medical evacuation to Australia or New Zealand",
    ],
    pros: [
      "Fiji's most trusted and financially stable health insurer",
      "Medical evacuation to Australia or NZ included",
      "Comprehensive maternity and newborn coverage",
      "Dental and optical in Premier plan",
    ],
    cons: [
      "Premiums high relative to Fijian income levels",
      "Network mostly in Suva and Lautoka",
      "International treatment requires pre-approval",
    ],
    affiliateUrl: "#",
    description:
      "Colonial Fiji Life Limited is part of the Pacific-wide Colonial Group and is Fiji's largest life and health insurer. The Premier Health plan provides comprehensive coverage for Fijian residents, including medical evacuation to Australia or New Zealand for conditions not treatable locally.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: true,
      vision: true,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Colonial Fiji Premier is the gold standard for private health insurance in Fiji, combining local hospital access with critical international evacuation coverage for complex medical cases.",
    editorialSource: "Pacific Island Insurance Market Report 2025",
  },
  {
    id: "fj-anz-life-fiji",
    name: "Tower Fiji Health Essential",
    provider: "Tower Insurance Fiji",
    country: "Fiji",
    countryCode: "fj",
    logo: "/logos/tower-fiji.svg",
    rating: 3.9,
    reviewCount: 1820,
    monthlyPremium: "FJD 80 - FJD 240",
    deductible: "FJD 30 - FJD 150",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "New Zealand-linked insurer with Fijian operations",
      "Affordable basic to mid-range health plans",
      "Covers outpatient and hospitalisation in Suva and Lautoka",
    ],
    pros: [
      "Competitive premiums for solid basic coverage",
      "NZ-backed financial stability",
      "Simple plan structure easy to understand",
    ],
    cons: [
      "International evacuation not standard",
      "Dental and optical excluded",
      "Telehealth not offered",
    ],
    affiliateUrl: "#",
    description:
      "Tower Insurance operates in Fiji as part of its Pacific region insurance business. The Health Essential plan provides affordable standard health coverage for Fijian residents seeking private hospital and outpatient care at competitive premiums.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Tower Fiji Health Essential is the most accessible private health plan in Fiji for families and employees who need reliable basic-to-standard coverage at affordable rates.",
    editorialSource: "Fiji Pacific Insurance Consumer Survey 2025",
  },

  // Papua New Guinea (PGK)
  {
    id: "pg-nib-png",
    name: "nib PNG Health Cover",
    provider: "nib PNG",
    country: "Papua New Guinea",
    countryCode: "pg",
    logo: "/logos/nib-png.svg",
    rating: 4.1,
    reviewCount: 2840,
    monthlyPremium: "PGK 350 - PGK 1,100",
    deductible: "PGK 100 - PGK 500",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Leading private health insurer in PNG",
      "Covers Port Moresby General Hospital and Pacific International Hospital",
      "Medical evacuation to Australia via Pacific SOS",
    ],
    pros: [
      "Australia-backed insurer with PNG market expertise",
      "Medical evacuation to Australia",
      "Wide Port Moresby hospital and clinic network",
      "Good corporate plan portfolio for mining sector",
    ],
    cons: [
      "Network limited to major PNG cities",
      "Premiums high for average PNG income",
      "International coverage for non-emergency limited",
    ],
    affiliateUrl: "#",
    description:
      "nib PNG is part of the ASX-listed nib Holdings Group and is the leading private health insurer in Papua New Guinea. The Health Cover plan provides comprehensive coverage for PNG residents including medical evacuation to Australia for cases exceeding local capability.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "nib PNG Health Cover is the premier private health plan in Papua New Guinea, trusted by the mining sector and expatriate community for its reliable medical evacuation capabilities.",
    editorialSource: "PNG Mining Sector Employee Benefits Review 2025",
  },
  {
    id: "pg-pngfha",
    name: "PNGFHA Corporate Health Plan",
    provider: "PNG First Home Assurance (PNGFHA)",
    country: "Papua New Guinea",
    countryCode: "pg",
    logo: "/logos/pngfha.svg",
    rating: 3.8,
    reviewCount: 1240,
    monthlyPremium: "PGK 250 - PGK 750",
    deductible: "PGK 80 - PGK 350",
    coverageType: "standard",
    badges: ["Local Leader"],
    highlights: [
      "PNG-owned insurer with growing health plan portfolio",
      "Affordable group plans for PNG SMEs",
      "Covers Port Moresby private clinic network",
    ],
    pros: [
      "Local PNG insurer understanding market needs",
      "Competitive group plan pricing for SMEs",
      "Good Port Moresby clinic access",
    ],
    cons: [
      "No international coverage",
      "Network limited to Port Moresby primarily",
      "No digital health tools",
    ],
    affiliateUrl: "#",
    description:
      "PNGFHA is a locally owned Papua New Guinea insurer expanding into health insurance for the growing local business sector. The Corporate Health Plan provides standard group health coverage for PNG-based SMEs at competitive group rates.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "PNGFHA Corporate Health is a dependable local option for PNG businesses seeking group health coverage without the premium pricing of international insurers.",
    editorialSource: "PNG SME Insurance Market Analysis 2025",
  },
  {
    id: "pg-pacific-sos",
    name: "Pacific SOS Health and Evacuation",
    provider: "Pacific SOS",
    country: "Papua New Guinea",
    countryCode: "pg",
    logo: "/logos/pacific-sos.svg",
    rating: 4.3,
    reviewCount: 1860,
    monthlyPremium: "PGK 500 - PGK 1,500",
    deductible: "PGK 150 - PGK 600",
    coverageType: "premium",
    badges: ["Best for Evacuation", "Best for Expats"],
    highlights: [
      "Specialised PNG evacuation and health plan for remote workers",
      "24/7 emergency coordination centre in Port Moresby",
      "Medical evacuation to Australia in under 6 hours",
    ],
    pros: [
      "Unmatched PNG evacuation capability",
      "24/7 emergency coordination",
      "Tailored for mining, oil, and remote sector workers",
      "Fast response times in remote PNG regions",
    ],
    cons: [
      "Higher cost than standard health plans",
      "Routine outpatient benefits less comprehensive",
      "Primarily suited for high-risk remote assignments",
    ],
    affiliateUrl: "#",
    description:
      "Pacific SOS is a PNG-based emergency medical services and health insurance specialist. The Health and Evacuation plan is designed for remote-site workers in PNG's mining, oil, and gas sectors, providing rapid medical evacuation to Australia and comprehensive emergency care.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Pacific SOS is the indispensable health and evacuation solution for workers in Papua New Guinea's remote resource sector, where rapid medical evacuation can be life-saving.",
    editorialSource: "PNG Resources Sector Safety Review 2025",
  },

  // Samoa (WST)
  {
    id: "ws-npu-samoa",
    name: "Samoa NPF Member Health Cover",
    provider: "National Provident Fund Samoa (NPF)",
    country: "Samoa",
    countryCode: "ws",
    logo: "/logos/npf-samoa.svg",
    rating: 3.7,
    reviewCount: 1120,
    monthlyPremium: "WST 80 - WST 250",
    deductible: "WST 20 - WST 80",
    coverageType: "basic",
    badges: ["Government-Backed"],
    highlights: [
      "Government-mandated social protection for Samoan employees",
      "Covers treatment at Tupua Tamasese Meaole National Hospital",
      "Affordable contributions for formal sector workers",
    ],
    pros: [
      "Mandatory coverage with government backing",
      "Low contribution cost for employees",
      "Covers inpatient and outpatient at national hospital",
    ],
    cons: [
      "Limited benefit package",
      "Private hospital access not included",
      "No international coverage",
    ],
    affiliateUrl: "#",
    description:
      "Samoa's National Provident Fund administers social protection benefits including health coverage components for Samoan formal sector employees. The Member Health Cover provides basic access to Samoa's national hospital system.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: false,
      telehealth: false,
    },
    editorialExcerpt:
      "Samoa's NPF Member Health Cover provides the essential baseline of health protection for Samoan formal sector workers through the national hospital system.",
    editorialSource: "Pacific Islands Social Protection Review 2025",
  },
  {
    id: "ws-colonial-samoa",
    name: "Colonial Samoa Health Plan",
    provider: "Colonial Life Insurance Samoa",
    country: "Samoa",
    countryCode: "ws",
    logo: "/logos/colonial-samoa.svg",
    rating: 4.0,
    reviewCount: 840,
    monthlyPremium: "WST 150 - WST 420",
    deductible: "WST 30 - WST 100",
    coverageType: "standard",
    badges: ["Best Private Option"],
    highlights: [
      "Pacific-wide Colonial Group coverage in Samoa",
      "Medical evacuation to New Zealand for complex cases",
      "Covers private clinic visits in Apia",
    ],
    pros: [
      "Pacific Group financial backing",
      "Medical evacuation to New Zealand",
      "Good private Apia clinic access",
    ],
    cons: [
      "Higher cost than NPF contribution",
      "Network limited to Apia",
      "Dental and optical not covered",
    ],
    affiliateUrl: "#",
    description:
      "Colonial Life Insurance Samoa is part of the Pacific-wide Colonial Group. The Health Plan provides standard private health coverage for Samoan residents with access to Apia's private clinics and medical evacuation to New Zealand for serious cases.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Colonial Samoa Health Plan is the leading private option in Samoa, valued for its New Zealand evacuation capability and Apia private clinic access.",
    editorialSource: "Pacific Insurance Consumer Guide 2025",
  },

  // Tonga (TOP)
  {
    id: "to-tonga-insurance",
    name: "Tonga Insurance Health Cover",
    provider: "Tonga Insurance Limited",
    country: "Tonga",
    countryCode: "to",
    logo: "/logos/tonga-insurance.svg",
    rating: 3.8,
    reviewCount: 720,
    monthlyPremium: "TOP 120 - TOP 360",
    deductible: "TOP 25 - TOP 100",
    coverageType: "standard",
    badges: ["Local Leader", "Most Popular"],
    highlights: [
      "Tonga's leading domestic insurer",
      "Covers Vaiola Hospital and private clinic network in Nuku'alofa",
      "Medical evacuation to New Zealand or Fiji",
    ],
    pros: [
      "Dominant local insurer with Tonga-specific expertise",
      "Medical evacuation to New Zealand or Fiji",
      "Good local hospital and clinic network",
    ],
    cons: [
      "Limited coverage outside Tongatapu",
      "Dental and optical not included",
      "No telehealth services",
    ],
    affiliateUrl: "#",
    description:
      "Tonga Insurance Limited is the dominant insurance company in Tonga. The Health Cover plan provides standard private health coverage for Tongan residents with access to Nuku'alofa's private clinics and medical evacuation to New Zealand or Fiji for advanced treatment.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Tonga Insurance Health Cover is the most accessible and trusted private health plan in Tonga, with medical evacuation access critical given the country's limited specialist healthcare capacity.",
    editorialSource: "Tonga Financial Services Market Report 2025",
  },
  {
    id: "to-colonial-tonga",
    name: "Colonial Tonga Health Basic",
    provider: "Colonial Life Insurance Tonga",
    country: "Tonga",
    countryCode: "to",
    logo: "/logos/colonial-tonga.svg",
    rating: 3.9,
    reviewCount: 520,
    monthlyPremium: "TOP 90 - TOP 270",
    deductible: "TOP 20 - TOP 80",
    coverageType: "basic",
    badges: ["Best Value"],
    highlights: [
      "Pacific Group-backed health coverage in Tonga",
      "Affordable entry-level plan for Tongan families",
      "Emergency evacuation to Fiji or New Zealand",
    ],
    pros: [
      "Pacific Group financial backing",
      "Affordable entry-level premiums",
      "Emergency evacuation included",
    ],
    cons: [
      "Very basic benefit package",
      "Outpatient benefits limited",
      "No dental, optical, or mental health",
    ],
    affiliateUrl: "#",
    description:
      "Colonial Life Insurance Tonga provides entry-level private health coverage for Tongan residents seeking affordable protection beyond the public health system. Emergency medical evacuation to Fiji or New Zealand is a key benefit.",
    coverageDetails: {
      hospitalization: true,
      outpatient: false,
      dental: false,
      vision: false,
      mental: false,
      maternity: false,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Colonial Tonga Health Basic is a practical, budget-friendly option for Tongan families who need essential hospitalization protection and access to overseas evacuation.",
    editorialSource: "Pacific Pacific Financial Services Survey 2025",
  },

  // Vanuatu (VUV)
  {
    id: "vu-qbe-vanuatu",
    name: "QBE Vanuatu Health Insurance",
    provider: "QBE Insurance Vanuatu",
    country: "Vanuatu",
    countryCode: "vu",
    logo: "/logos/qbe-vanuatu.svg",
    rating: 4.1,
    reviewCount: 1120,
    monthlyPremium: "VUV 20,000 - VUV 60,000",
    deductible: "VUV 5,000 - VUV 20,000",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Australia-backed QBE with strong Vanuatu presence",
      "Medical evacuation to Australia or New Zealand",
      "Covers Port Vila Central Hospital and private clinics",
    ],
    pros: [
      "ASX-listed QBE's financial strength",
      "Medical evacuation to Australia or NZ",
      "Best private clinic access in Port Vila",
      "Comprehensive plan for expatriates and NGO staff",
    ],
    cons: [
      "High cost relative to Vanuatu income levels",
      "Network very limited outside Port Vila and Luganville",
      "Dental not included in base plan",
    ],
    affiliateUrl: "#",
    description:
      "QBE Insurance Vanuatu is part of the global QBE Group and is the leading private health insurer in Vanuatu. The Health Insurance plan provides comprehensive coverage for Vanuatu residents and expatriates, including critical medical evacuation to Australia or New Zealand.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "QBE Vanuatu Health Insurance is the definitive private health plan in Vanuatu, with unmatched medical evacuation access critical in a country with very limited specialist healthcare capacity.",
    editorialSource: "Pacific Insurance Market Review 2025",
  },
  {
    id: "vu-nib-vanuatu",
    name: "Pacific MMI Vanuatu Health",
    provider: "Pacific MMI Insurance Vanuatu",
    country: "Vanuatu",
    countryCode: "vu",
    logo: "/logos/pacific-mmi-vanuatu.svg",
    rating: 3.8,
    reviewCount: 680,
    monthlyPremium: "VUV 14,000 - VUV 42,000",
    deductible: "VUV 3,000 - VUV 12,000",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "Pacific MMI's Vanuatu operation with regional expertise",
      "Affordable standard plan for Vanuatu residents",
      "Emergency evacuation to Fiji or Australia",
    ],
    pros: [
      "More affordable than QBE for similar basic coverage",
      "Emergency evacuation included",
      "Pacific region insurance expertise",
    ],
    cons: [
      "Benefits less comprehensive than QBE",
      "Network limited to Port Vila",
      "No dental or optical coverage",
    ],
    affiliateUrl: "#",
    description:
      "Pacific MMI Insurance operates in Vanuatu as part of its Pacific-wide insurance operations. The Health plan provides standard private coverage for Vanuatu residents at more accessible price points than international competitors.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Pacific MMI Vanuatu Health is a reliable mid-market alternative to QBE for Vanuatu residents seeking solid private health coverage with evacuation access at lower premium rates.",
    editorialSource: "Vanuatu Insurance Consumer Report 2025",
  },

  // Solomon Islands (SBD)
  {
    id: "sb-qbe-solomon",
    name: "QBE Solomon Islands Health Plan",
    provider: "QBE Insurance Solomon Islands",
    country: "Solomon Islands",
    countryCode: "sb",
    logo: "/logos/qbe-solomon.svg",
    rating: 4.0,
    reviewCount: 840,
    monthlyPremium: "SBD 800 - SBD 2,500",
    deductible: "SBD 150 - SBD 600",
    coverageType: "comprehensive",
    badges: ["Editor's Choice", "Most Popular"],
    highlights: [
      "Leading private health insurer in the Solomon Islands",
      "Covers National Referral Hospital and Honiara private clinics",
      "Medical evacuation to Australia or Papua New Guinea",
    ],
    pros: [
      "Australia-backed QBE financial strength",
      "Medical evacuation to Australia",
      "Best Honiara clinic and hospital network",
      "Good corporate group plans for NGOs and government contractors",
    ],
    cons: [
      "Premiums high for Solomon Islands income levels",
      "Network limited to Honiara",
      "Dental and vision excluded",
    ],
    affiliateUrl: "#",
    description:
      "QBE Insurance Solomon Islands is the leading private health insurer in the country. The Health Plan provides comprehensive coverage for Solomon Islands residents, expatriates, and NGO workers with medical evacuation to Australia for advanced treatment.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "QBE Solomon Islands Health Plan is the premier private health option in the country, indispensable for expatriates and NGO workers who need reliable medical evacuation capability.",
    editorialSource: "Solomon Islands Insurance Market Assessment 2025",
  },
  {
    id: "sb-pacific-mmi-solomon",
    name: "Pacific MMI Solomon Islands Health",
    provider: "Pacific MMI Insurance Solomon Islands",
    country: "Solomon Islands",
    countryCode: "sb",
    logo: "/logos/pacific-mmi-solomon.svg",
    rating: 3.8,
    reviewCount: 520,
    monthlyPremium: "SBD 550 - SBD 1,700",
    deductible: "SBD 100 - SBD 450",
    coverageType: "standard",
    badges: ["Best Value"],
    highlights: [
      "Pacific MMI's Solomon Islands operation for local and NGO clients",
      "Affordable alternative to QBE for standard coverage needs",
      "Emergency medical evacuation to Papua New Guinea or Fiji",
    ],
    pros: [
      "More accessible premiums than QBE",
      "Emergency evacuation included",
      "Pacific region insurance expertise",
    ],
    cons: [
      "Benefits less comprehensive than QBE",
      "Evacuation destination may be PNG rather than Australia",
      "Network limited to Honiara",
    ],
    affiliateUrl: "#",
    description:
      "Pacific MMI Insurance Solomon Islands provides standard private health coverage at more accessible price points than the market leader QBE. The Health plan targets Solomon Islands residents and smaller NGOs seeking cost-effective private health protection.",
    coverageDetails: {
      hospitalization: true,
      outpatient: true,
      dental: false,
      vision: false,
      mental: false,
      maternity: true,
      prescription: true,
      emergency: true,
      international: true,
      telehealth: false,
    },
    editorialExcerpt:
      "Pacific MMI Solomon Islands Health is the best-value alternative to QBE in the country, providing essential private coverage with evacuation access at more affordable premiums.",
    editorialSource: "Solomon Islands Financial Services Review 2025",
  },
];
